import type { TerrainDef, TerrainId } from "../core/types";

export const TERRAIN: Record<TerrainId, TerrainDef> = {
  road: {
    id: "road",
    name: "道路",
    moveCost: 1,
    defense: -0.1,
    vehiclePassable: true,
    passable: true,
    regen: 0,
    rangeBonus: 0,
    attackBonus: 0,
  },
  plain: {
    id: "plain",
    name: "平原",
    moveCost: 2,
    defense: 0,
    vehiclePassable: true,
    passable: true,
    regen: 0,
    rangeBonus: 0,
    attackBonus: 0,
  },
  forest: {
    id: "forest",
    name: "森林",
    moveCost: 3,
    defense: 0.25,
    vehiclePassable: false,
    passable: true,
    regen: 0,
    rangeBonus: 0,
    attackBonus: 0,
  },
  hill: {
    id: "hill",
    name: "高地",
    moveCost: 4,
    defense: 0.35,
    vehiclePassable: true,
    passable: true,
    regen: 0,
    rangeBonus: 1,
    attackBonus: 0.1,
  },
  village: {
    id: "village",
    name: "小镇",
    moveCost: 2,
    defense: 0.25,
    vehiclePassable: true,
    passable: true,
    regen: 12,
    rangeBonus: 0,
    attackBonus: 0,
  },
  fort: {
    id: "fort",
    name: "要塞",
    moveCost: 3,
    defense: 0.45,
    vehiclePassable: true,
    passable: true,
    regen: 16,
    rangeBonus: 0,
    attackBonus: 0.05,
  },
  river: {
    id: "river",
    name: "河流",
    moveCost: 6,
    defense: -0.2,
    vehiclePassable: false,
    passable: true,
    regen: 0,
    rangeBonus: 0,
    attackBonus: 0,
  },
  cliff: {
    id: "cliff",
    name: "峭壁",
    moveCost: 99,
    defense: 0,
    vehiclePassable: false,
    passable: false,
    regen: 0,
    rangeBonus: 0,
    attackBonus: 0,
  },
};

export const TERRAIN_CHARS: Record<string, TerrainId> = {
  "=": "road",
  ".": "plain",
  F: "forest",
  "^": "hill",
  V: "village",
  B: "fort",
  "~": "river",
  "#": "cliff",
};

export const WEATHER_EFFECT = {
  clear: { rangedDamage: 0, movePenalty: 0 },
  overcast: { rangedDamage: -0.04, movePenalty: 0 },
  rain: {
    /** 射程大于 1 的攻击伤害修正 */
    rangedDamage: -0.15,
    movePenalty: 1,
  },
  snow: { rangedDamage: -0.08, movePenalty: 1 },
  fog: { rangedDamage: -0.18, movePenalty: 0 },
};
