import type { UnitTypeDef, UnitTypeId } from "../core/types";
import { PROGRESS, levelFromExp } from "./progress";

export const UNIT_TYPES: Record<UnitTypeId, UnitTypeDef> = {
  rifle: {
    id: "rifle",
    name: "步兵",
    move: 6,
    minRange: 1,
    maxRange: 1,
    attack: 22,
    maxHp: 100,
    vehicle: false,
    canCapture: true,
    indirect: false,
    setupBonus: 0,
    role: "能占领目标，耐打，是战线主体",
  },
  mg: {
    id: "mg",
    name: "机枪",
    move: 4,
    minRange: 1,
    maxRange: 2,
    attack: 24,
    maxHp: 90,
    vehicle: false,
    canCapture: true,
    indirect: false,
    setupBonus: 0.35,
    role: "本回合未移动则伤害大增，亦可踩点占领；克步兵，对装甲较弱",
  },
  mortar: {
    id: "mortar",
    name: "迫击炮",
    move: 4,
    minRange: 2,
    maxRange: 3,
    attack: 22,
    maxHp: 70,
    vehicle: false,
    canCapture: false,
    indirect: true,
    setupBonus: 0,
    role: "营级曲射：地形防御减半且不受反击；射程短，只覆盖局部",
  },
  artillery: {
    id: "artillery",
    name: "炮兵",
    move: 2,
    minRange: 4,
    maxRange: 7,
    attack: 30,
    maxHp: 65,
    vehicle: false,
    canCapture: false,
    indirect: true,
    setupBonus: 0.12,
    role: "师属远程火力：极慢、怕近战；需提前展开才能覆盖战线",
  },
  tank: {
    id: "tank",
    name: "坦克",
    move: 8,
    minRange: 1,
    maxRange: 2,
    attack: 34,
    maxHp: 140,
    vehicle: true,
    canCapture: true,
    indirect: false,
    setupBonus: 0,
    role: "突破与夺点核心，机动与火力最强，但受地形限制且怕反坦克武器",
  },
  armored_car: {
    id: "armored_car",
    name: "装甲车",
    move: 7,
    minRange: 1,
    maxRange: 2,
    attack: 28,
    maxHp: 110,
    vehicle: true,
    canCapture: true,
    indirect: false,
    setupBonus: 0,
    role: "公路侦察与火力支援，可占领；弱于坦克、强于步兵直射",
  },
  logistics: {
    id: "logistics",
    name: "后勤",
    move: 5,
    minRange: 1,
    maxRange: 0,
    attack: 0,
    maxHp: 115,
    vehicle: false,
    canCapture: false,
    indirect: false,
    setupBonus: 0,
    role: "邻接友军补充兵员：回复生命并降低疲劳；无进攻能力",
  },
};

/** 后勤补充：人员守恒调拨 + 疲劳/弹药服务。 */
export const LOGISTICS = {
  personnelPerAction: 28,
  minimumPersonnel: 55,
  fatigueRelief: 18,
  ammoRestoreTurns: 3,
};

/** 克制系数：MATCHUP[攻方][守方] */
export const MATCHUP: Record<UnitTypeId, Record<UnitTypeId, number>> = {
  rifle: {
    rifle: 1.0,
    mg: 1.1,
    mortar: 1.25,
    artillery: 1.3,
    tank: 0.45,
    armored_car: 0.65,
    logistics: 1.2,
  },
  mg: {
    rifle: 1.3,
    mg: 1.0,
    mortar: 1.2,
    artillery: 1.25,
    tank: 0.3,
    armored_car: 0.45,
    logistics: 1.25,
  },
  mortar: {
    rifle: 1.1,
    mg: 1.25,
    mortar: 1.0,
    artillery: 1.05,
    tank: 0.6,
    armored_car: 0.75,
    logistics: 1.15,
  },
  artillery: {
    rifle: 1.2,
    mg: 1.25,
    mortar: 1.15,
    artillery: 1.0,
    tank: 0.55,
    armored_car: 0.7,
    logistics: 1.2,
  },
  tank: {
    rifle: 1.4,
    mg: 1.45,
    mortar: 1.5,
    artillery: 1.55,
    tank: 1.0,
    armored_car: 1.25,
    logistics: 1.35,
  },
  armored_car: {
    rifle: 1.25,
    mg: 1.3,
    mortar: 1.35,
    artillery: 1.4,
    tank: 0.7,
    armored_car: 1.0,
    logistics: 1.3,
  },
  logistics: {
    rifle: 0,
    mg: 0,
    mortar: 0,
    artillery: 0,
    tank: 0,
    armored_car: 0,
    logistics: 0,
  },
};

export { levelFromExp, PROGRESS };
