import type { ConditionTree, ContentPack } from "../core/types";

const always: ConditionTree = { all: [] };

/**
 * 《连城诀》最短合法路线所需的最小内容包。
 * IDs and reconstructed walkthrough structure only — no original art, music, or dialogue text.
 */
export const lianchengContent: ContentPack = {
  id: "liancheng-slice",
  startLocationId: "home",
  startKnownLocations: ["home", "nanxian_house"],
  playerId: "player",
  partyMax: 6,
  locations: [
    { id: "home", sceneId: "home", exits: ["nanxian_house"] },
    { id: "nanxian_house", sceneId: "nanxian_house", exits: ["home", "jiangnan_cave"] },
    { id: "jiangnan_cave", sceneId: "jiangnan_cave", exits: ["nanxian_house", "beichou_house"] },
    { id: "beichou_house", sceneId: "beichou_house", exits: ["jiangnan_cave", "tianning_temple"] },
    { id: "tianning_temple", sceneId: "tianning_temple", exits: ["beichou_house"] },
  ],
  items: [
    { id: "compass", name: "compass", category: "key", stackable: false },
    { id: "tang_poetry", name: "tang_poetry", category: "plot", stackable: false },
    { id: "liancheng_book", name: "liancheng_book", category: "heaven-book", stackable: false },
  ],
  characters: [
    {
      id: "player",
      name: "player",
      level: 1,
      maxHp: 50,
      attack: 20,
      defence: 10,
      speed: 10,
      internalType: "NONE",
    },
    {
      id: "nanxian",
      name: "nanxian",
      level: 1,
      maxHp: 1,
      attack: 0,
      defence: 0,
      speed: 0,
      internalType: "NONE",
    },
    {
      id: "beichou",
      name: "beichou",
      level: 1,
      maxHp: 1,
      attack: 0,
      defence: 0,
      speed: 0,
      internalType: "NONE",
    },
    {
      id: "tianning_monk",
      name: "tianning_monk",
      level: 1,
      maxHp: 12,
      attack: 8,
      defence: 5,
      speed: 5,
      internalType: "NONE",
    },
  ],
  interactables: [
    { id: "nanxian", sceneId: "nanxian_house", kind: "npc" },
    { id: "cave_poetry", sceneId: "jiangnan_cave", kind: "object" },
    { id: "beichou", sceneId: "beichou_house", kind: "npc" },
    { id: "water", sceneId: "beichou_house", kind: "object" },
    { id: "tianning_monk", sceneId: "tianning_temple", kind: "npc" },
    { id: "statue", sceneId: "tianning_temple", kind: "object" },
  ],
  events: [
    {
      id: "talk_nanxian",
      sceneId: "nanxian_house",
      trigger: "TALK",
      actorId: "nanxian",
      conditions: always,
      actions: [
        { type: "dialogue", id: "nanxian-hint" },
        { type: "unlockLocation", locationId: "jiangnan_cave" },
        { type: "addItem", itemId: "compass", count: 1 },
      ],
      priority: 10,
      repeatable: false,
    },
    {
      id: "take_cave_poetry",
      sceneId: "jiangnan_cave",
      trigger: "INTERACT",
      targetId: "cave_poetry",
      conditions: { not: { hasItem: "tang_poetry" } },
      actions: [
        { type: "addItem", itemId: "tang_poetry", count: 1 },
        { type: "unlockLocation", locationId: "beichou_house" },
        { type: "dialogue", id: "found-tang-poetry" },
      ],
      priority: 10,
      repeatable: false,
    },
    {
      id: "soak_tang_poetry",
      sceneId: "beichou_house",
      trigger: "USE_ITEM",
      itemId: "tang_poetry",
      targetId: "water",
      conditions: { hasItem: "tang_poetry" },
      actions: [
        { type: "setFlag", flag: "poetry_revealed", value: true },
        { type: "unlockLocation", locationId: "tianning_temple" },
        { type: "dialogue", id: "poetry-revealed" },
      ],
      priority: 10,
      repeatable: false,
    },
    {
      id: "tianning_ambush",
      sceneId: "tianning_temple",
      trigger: "ENTER",
      conditions: { not: { battleWon: "tianning_guard" } },
      actions: [{ type: "startBattle", battleId: "tianning_guard" }],
      priority: 20,
      repeatable: false,
    },
    {
      id: "tianning_cleared",
      sceneId: "tianning_temple",
      trigger: "BATTLE_WIN",
      targetId: "tianning_guard",
      conditions: always,
      actions: [
        { type: "setFlag", flag: "tianning_cleared", value: true },
        { type: "dialogue", id: "temple-quiet" },
      ],
      priority: 10,
      repeatable: false,
    },
    {
      id: "take_liancheng_book",
      sceneId: "tianning_temple",
      trigger: "INTERACT",
      targetId: "statue",
      conditions: {
        all: [{ battleWon: "tianning_guard" }, { not: { hasItem: "liancheng_book" } }],
      },
      actions: [
        { type: "addItem", itemId: "liancheng_book", count: 1 },
        { type: "addHeavenBook", bookId: "liancheng" },
        { type: "setFlag", flag: "heaven_book_liancheng", value: true },
        { type: "dialogue", id: "found-liancheng" },
      ],
      priority: 10,
      repeatable: false,
    },
  ],
  battles: {
    tianning_guard: {
      id: "tianning_guard",
      width: 5,
      height: 5,
      units: [
        {
          id: "player",
          side: "player",
          x: 1,
          y: 2,
          hp: 50,
          maxHp: 50,
          attack: 20,
          defence: 10,
          speed: 10,
          alive: true,
        },
        {
          id: "tianning_monk",
          side: "enemy",
          x: 3,
          y: 2,
          hp: 12,
          maxHp: 12,
          attack: 8,
          defence: 5,
          speed: 5,
          alive: true,
        },
      ],
    },
  },
};
