import type { BattleUnit, ConditionTree, ContentPack, EventDefinition } from "../core/types";

const always: ConditionTree = { all: [] };

function fighter(
  id: string,
  side: BattleUnit["side"],
  x: number,
  y: number,
  stats: Pick<BattleUnit, "hp" | "attack" | "defence" | "speed" | "skillPower">,
): BattleUnit {
  return { id, side, x, y, maxHp: stats.hp, alive: true, ...stats };
}

function once(
  partial: Omit<EventDefinition, "repeatable" | "priority"> & { priority?: number },
): EventDefinition {
  return { priority: 10, repeatable: false, ...partial };
}

/**
 * 《连城诀》重建包。坐标与步骤来自公开 DOS 攻略，不是原版二进制实测。
 * 不含原作美术、音乐或台词文件。
 */
export const lianchengContent: ContentPack = {
  id: "liancheng-slice",
  startLocationId: "home",
  startKnownLocations: ["home", "heluo_inn"],
  startMoral: 50,
  startInventory: {},
  playerId: "player",
  partyMax: 6,
  locations: [
    { id: "home", sceneId: "home", title: "自宅", worldX: 352, worldY: 233, exits: ["heluo_inn"] },
    {
      id: "heluo_inn",
      sceneId: "heluo_inn",
      title: "河洛客栈",
      worldX: 359,
      worldY: 229,
      exits: ["home", "nanxian_house", "fuwei_biaoju"],
    },
    {
      id: "nanxian_house",
      sceneId: "nanxian_house",
      title: "南贤居",
      worldX: 388,
      worldY: 325,
      exits: ["heluo_inn", "dalun_temple"],
    },
    {
      id: "fuwei_biaoju",
      sceneId: "fuwei_biaoju",
      title: "福威镖局",
      worldX: 369,
      worldY: 258,
      exits: ["heluo_inn", "jiangnan_cave"],
    },
    {
      id: "jiangnan_cave",
      sceneId: "jiangnan_cave",
      title: "唐诗山洞",
      worldX: 364,
      worldY: 279,
      exits: ["fuwei_biaoju"],
    },
    {
      id: "dalun_temple",
      sceneId: "dalun_temple",
      title: "大轮寺",
      worldX: 114,
      worldY: 297,
      exits: ["nanxian_house"],
    },
    {
      id: "beichou_house",
      sceneId: "beichou_house",
      title: "北丑居",
      worldX: 51,
      worldY: 109,
      exits: ["tianning_temple"],
    },
    {
      id: "tianning_temple",
      sceneId: "tianning_temple",
      title: "天宁寺",
      worldX: 330,
      worldY: 237,
      exits: ["beichou_house"],
    },
  ],
  items: [
    { id: "silver", name: "silver", category: "money", stackable: true },
    { id: "jingqi_pill", name: "jingqi_pill", category: "medicine", stackable: true },
    { id: "ginseng", name: "ginseng", category: "medicine", stackable: true },
    { id: "xiaohuandan", name: "xiaohuandan", category: "medicine", stackable: true },
    { id: "huanglian_pill", name: "huanglian_pill", category: "medicine", stackable: true },
    { id: "compass", name: "compass", category: "key", stackable: false },
    { id: "tang_poetry", name: "tang_poetry", category: "plot", stackable: false },
    { id: "orange_key", name: "orange_key", category: "key", stackable: false },
    { id: "blood_knife", name: "blood_knife", category: "weapon", stackable: false },
    { id: "blood_knife_script", name: "blood_knife_script", category: "manual", stackable: false },
    { id: "shenzhao_script", name: "shenzhao_script", category: "manual", stackable: false },
    { id: "wucan_armor", name: "wucan_armor", category: "armor", stackable: false },
    { id: "liancheng_book", name: "liancheng_book", category: "heaven-book", stackable: false },
  ],
  characters: [
    {
      id: "player",
      name: "player",
      level: 1,
      maxHp: 50,
      attack: 30,
      defence: 10,
      speed: 10,
      internalType: "NONE",
    },
    {
      id: "nanxian",
      name: "nanxian",
      level: 1,
      maxHp: 1,
      attack: 0,
      defence: 0,
      speed: 0,
      internalType: "NONE",
    },
    {
      id: "beichou",
      name: "beichou",
      level: 1,
      maxHp: 1,
      attack: 0,
      defence: 0,
      speed: 0,
      internalType: "NONE",
    },
    {
      id: "diyun",
      name: "diyun",
      level: 10,
      maxHp: 80,
      attack: 40,
      defence: 20,
      speed: 8,
      internalType: "NONE",
    },
  ],
  interactables: [
    { id: "home_chest", sceneId: "home", kind: "object" },
    { id: "waiter", sceneId: "heluo_inn", kind: "npc" },
    { id: "inn_crowd", sceneId: "heluo_inn", kind: "npc" },
    { id: "nanxian", sceneId: "nanxian_house", kind: "npc" },
    { id: "nanxian_cabinet", sceneId: "nanxian_house", kind: "object" },
    { id: "nanxian_mirror", sceneId: "nanxian_house", kind: "object" },
    { id: "cave_trail", sceneId: "fuwei_biaoju", kind: "object" },
    { id: "cave_poetry", sceneId: "jiangnan_cave", kind: "object" },
    { id: "diyun_cell", sceneId: "dalun_temple", kind: "object" },
    { id: "diyun", sceneId: "dalun_temple", kind: "npc" },
    { id: "beichou", sceneId: "beichou_house", kind: "npc" },
    { id: "basin", sceneId: "beichou_house", kind: "object" },
    { id: "statue_back", sceneId: "tianning_temple", kind: "object" },
  ],
  events: [
    once({
      id: "loot_home_chest",
      sceneId: "home",
      trigger: "INTERACT",
      targetId: "home_chest",
      conditions: always,
      actions: [
        { type: "addItem", itemId: "jingqi_pill", count: 1 },
        { type: "addItem", itemId: "ginseng", count: 1 },
        { type: "addItem", itemId: "xiaohuandan", count: 1 },
        { type: "addItem", itemId: "huanglian_pill", count: 1 },
        { type: "addItem", itemId: "silver", count: 10 },
        { type: "dialogue", id: "home-chest" },
      ],
    }),
    once({
      id: "tip_waiter",
      sceneId: "heluo_inn",
      trigger: "TALK",
      actorId: "waiter",
      conditions: { hasItem: "silver" },
      actions: [
        { type: "removeItem", itemId: "silver", count: 1 },
        { type: "unlockLocation", locationId: "nanxian_house" },
        { type: "dialogue", id: "waiter-tip" },
      ],
    }),
    {
      id: "waiter_broke",
      sceneId: "heluo_inn",
      trigger: "TALK",
      actorId: "waiter",
      conditions: { not: { hasItem: "silver" } },
      actions: [{ type: "dialogue", id: "waiter-broke" }],
      priority: 1,
      repeatable: true,
    },
    once({
      id: "inn_fuwei_rumor",
      sceneId: "heluo_inn",
      trigger: "TALK",
      actorId: "inn_crowd",
      conditions: always,
      actions: [
        { type: "unlockLocation", locationId: "fuwei_biaoju" },
        { type: "dialogue", id: "inn-rumor" },
      ],
    }),
    once({
      id: "talk_nanxian",
      sceneId: "nanxian_house",
      trigger: "TALK",
      actorId: "nanxian",
      conditions: always,
      actions: [{ type: "dialogue", id: "nanxian-quest" }],
    }),
    once({
      id: "take_compass",
      sceneId: "nanxian_house",
      trigger: "INTERACT",
      targetId: "nanxian_cabinet",
      conditions: always,
      actions: [
        { type: "addItem", itemId: "compass", count: 1 },
        { type: "unlockLocation", locationId: "dalun_temple" },
        { type: "dialogue", id: "nanxian-cabinet" },
      ],
    }),
    {
      id: "look_mirror",
      sceneId: "nanxian_house",
      trigger: "INTERACT",
      targetId: "nanxian_mirror",
      conditions: always,
      actions: [{ type: "dialogue", id: "nanxian-mirror" }],
      priority: 5,
      repeatable: true,
    },
    once({
      id: "find_cave_trail",
      sceneId: "fuwei_biaoju",
      trigger: "INTERACT",
      targetId: "cave_trail",
      conditions: always,
      actions: [
        { type: "unlockLocation", locationId: "jiangnan_cave" },
        { type: "dialogue", id: "fuwei-cave-trail" },
      ],
    }),
    once({
      id: "take_cave_poetry",
      sceneId: "jiangnan_cave",
      trigger: "INTERACT",
      targetId: "cave_poetry",
      conditions: { not: { hasItem: "tang_poetry" } },
      actions: [
        { type: "addItem", itemId: "tang_poetry", count: 1 },
        { type: "unlockLocation", locationId: "beichou_house" },
        { type: "dialogue", id: "found-tang-poetry" },
      ],
    }),
    {
      id: "talk_beichou",
      sceneId: "beichou_house",
      trigger: "TALK",
      actorId: "beichou",
      conditions: always,
      actions: [{ type: "dialogue", id: "beichou-riddle" }],
      priority: 5,
      repeatable: true,
    },
    once({
      id: "soak_tang_poetry",
      sceneId: "beichou_house",
      trigger: "USE_ITEM",
      itemId: "tang_poetry",
      targetId: "basin",
      conditions: { hasItem: "tang_poetry" },
      actions: [
        { type: "setFlag", flag: "poetry_revealed", value: true },
        { type: "unlockLocation", locationId: "tianning_temple" },
        { type: "dialogue", id: "poetry-revealed" },
      ],
    }),
    once({
      id: "tianning_ambush",
      sceneId: "tianning_temple",
      trigger: "ENTER",
      conditions: { not: { battleWon: "tianning_raid" } },
      actions: [
        { type: "startBattle", battleId: "tianning_raid" },
        { type: "dialogue", id: "temple-fight" },
      ],
      priority: 20,
    }),
    once({
      id: "tianning_cleared",
      sceneId: "tianning_temple",
      trigger: "BATTLE_WIN",
      targetId: "tianning_raid",
      conditions: always,
      actions: [
        { type: "setFlag", flag: "tianning_cleared", value: true },
        { type: "dialogue", id: "temple-quiet" },
      ],
    }),
    once({
      id: "take_liancheng_book",
      sceneId: "tianning_temple",
      trigger: "INTERACT",
      targetId: "statue_back",
      conditions: {
        all: [{ battleWon: "tianning_raid" }, { not: { hasItem: "liancheng_book" } }],
      },
      actions: [
        { type: "addItem", itemId: "liancheng_book", count: 1 },
        { type: "addHeavenBook", bookId: "liancheng" },
        { type: "setFlag", flag: "heaven_book_liancheng", value: true },
        { type: "dialogue", id: "found-liancheng" },
      ],
    }),
    once({
      id: "dalun_ambush",
      sceneId: "dalun_temple",
      trigger: "ENTER",
      conditions: { not: { battleWon: "dalun_monks" } },
      actions: [
        { type: "startBattle", battleId: "dalun_monks" },
        { type: "dialogue", id: "dalun-fight" },
      ],
      priority: 20,
    }),
    once({
      id: "dalun_cleared",
      sceneId: "dalun_temple",
      trigger: "BATTLE_WIN",
      targetId: "dalun_monks",
      conditions: always,
      actions: [
        { type: "addItem", itemId: "orange_key", count: 1 },
        { type: "reputation", delta: 2 },
        { type: "dialogue", id: "dalun-key" },
      ],
    }),
    once({
      id: "open_diyun_cell",
      sceneId: "dalun_temple",
      trigger: "INTERACT",
      targetId: "diyun_cell",
      conditions: { hasItem: "orange_key" },
      actions: [
        { type: "setFlag", flag: "diyun_freed", value: true },
        { type: "moral", delta: 2 },
        { type: "dialogue", id: "diyun-freed" },
      ],
    }),
    once({
      id: "recruit_diyun",
      sceneId: "dalun_temple",
      trigger: "TALK",
      actorId: "diyun",
      conditions: { all: [{ flag: "diyun_freed" }, { moral: { min: 60 } }] },
      actions: [
        { type: "addParty", characterId: "diyun" },
        { type: "addItem", itemId: "blood_knife", count: 1 },
        { type: "addItem", itemId: "blood_knife_script", count: 1 },
        { type: "addItem", itemId: "shenzhao_script", count: 1 },
        { type: "addItem", itemId: "wucan_armor", count: 1 },
        { type: "unlockLocation", locationId: "jiangnan_cave" },
        { type: "dialogue", id: "diyun-join" },
      ],
      priority: 20,
    }),
    once({
      id: "diyun_wrong_coords",
      sceneId: "dalun_temple",
      trigger: "TALK",
      actorId: "diyun",
      conditions: { all: [{ flag: "diyun_freed" }, { not: { moral: { min: 60 } } }] },
      actions: [
        { type: "setFlag", flag: "diyun_lied", value: true },
        { type: "dialogue", id: "diyun-refuse" },
      ],
      priority: 10,
    }),
  ],
  battles: {
    tianning_raid: {
      id: "tianning_raid",
      width: 5,
      height: 5,
      units: [
        fighter("player", "player", 1, 2, { hp: 50, attack: 30, defence: 10, speed: 10, skillPower: 30 }),
        fighter("raider_a", "enemy", 3, 1, { hp: 18, attack: 14, defence: 6, speed: 6, skillPower: 20 }),
        fighter("raider_b", "enemy", 3, 3, { hp: 18, attack: 14, defence: 6, speed: 5, skillPower: 20 }),
      ],
    },
    dalun_monks: {
      id: "dalun_monks",
      width: 5,
      height: 5,
      units: [
        fighter("player", "player", 1, 2, { hp: 50, attack: 30, defence: 10, speed: 10, skillPower: 30 }),
        fighter("monk_a", "enemy", 3, 2, { hp: 16, attack: 12, defence: 5, speed: 5, skillPower: 18 }),
      ],
    },
  },
};
