import type { MissionConfig } from "./schema";

const PVA_EARLY = {
  artillery: "75毫米山炮",
  logistics: "辎重分队",
  rifle: "三八式／中正式步枪、手榴弹",
  mg: "捷克式ZB-26轻机枪",
  mortar: "31式60毫米迫击炮",
  tank: "缴获反坦克武器",
} as const;

const PVA_LATE = {
  artillery: "苏制榴弹炮／山炮",
  logistics: "汽车辎重队",
  rifle: "莫辛-纳甘步枪、50式冲锋枪",
  mg: "DP-28轻机枪／24式重机枪",
  mortar: "82毫米迫击炮",
  /** 默认不宣称局部坦克；仅 m11 等有直接史料处改用 PVA_LATE_ARMOR */
  tank: "反坦克火力与炮火支援",
} as const;

const PVA_LATE_ARMOR = {
  ...PVA_LATE,
  tank: "T-34-85装甲支援（独立坦克第4团局部配属）",
} as const;

const pva = (id: string, name: string, role: string, formation: string, portrait?: string) => ({
  id,
  name,
  faction: "player" as const,
  role,
  formation,
  portrait: portrait ?? id,
  historicalRank: "职务制（无军衔徽章）",
});

const un = (
  id: string,
  name: string,
  role: string,
  formation: string,
  portrait: string | undefined,
  historicalRank: string,
  rankInsignia?: string,
) => ({
  id,
  name,
  faction: "enemy" as const,
  role,
  formation,
  portrait: portrait ?? id,
  historicalRank,
  rankInsignia,
});

/**
 * 12关按时间顺序覆盖志愿军入朝、运动战、阵地战与停战前反击。
 * 棋盘是团/营级战术抽象，不宣称按比例复刻整场战役。
 */
export const HISTORICAL_MISSIONS: MissionConfig[] = [
  {
    id: "m1-onjong",
    name: "温井初战",
    kind: "breakthrough",
    date: "1950年10月25日",
    location: "朝鲜温井—北镇公路",
    historicalOutcome: "志愿军第40军在温井地区击破韩军先头部队，第一次战役由此展开。",
    historicalNote: "当面部队为韩国陆军第6师第2团第3营先头部队及炮兵中队；高大全为虚构指挥连接；随行班底与配属多为真实志愿军人物，敌军主将以精英单位上场。",
    commanders: [
      pva("wen-yucheng", "温玉成", "第40军军长", "中国人民志愿军第40军"),
      un("kim-jong-oh", "金钟五", "第6师师长", "韩国陆军第6步兵师", undefined, "准将", "rok-brigadier-general"),
    ],
    brief: "隐蔽进入两水洞峡谷两侧高地，待韩军先头营进入谷底后拦头、截尾，再向南夺取温井。敌军会沿温井—北镇公路续进；高大全必须生还。",
    mapNote: "北在上；中央纵路是温井—北镇公路，伏击线夹在239.8、216与409.5高地之间，温井位于地图南端，九龙江沿南侧限制机动。",
    weather: { options: ["clear", "overcast"], label: "深秋寒夜", detail: "低温、天黑后能见度下降；长射程火力略受影响。" },
    playerEquipment: PVA_EARLY,
    enemyDamageMultiplier: 0.6,
    maxTurns: 17,
    map: [
      "^^^FF^^^F..F^^^FF^^^",
      "^^FF^^^^F==F^^^^FF^^",
      "^^F^^^^^F==F^^^^^F^^",
      "^^^^^F...==...F^^^^^",
      "^^^^F....==....F^^^^",
      "^^^F^^F..==..F^^F^^^",
      "^^^^F...=VV=...F^^^^",
      "^^^^^F...==...F^^^^^",
      "FFFF^^F..==..F^^FFFF",
      "FFFF..F..==..F..FFFF",
      "~~~~~~...==...~~~~~~",
      "FFFFF....==....FFFFF",
      "FFFFF...=VV=...FFFFF",
      "FFFFF....==....FFFFF"
    ],
    playerSpawns: [{ x: 4, y: 5 }, { x: 5, y: 5 }, { x: 14, y: 5 }, { x: 15, y: 5 }, { x: 4, y: 7 }, { x: 5, y: 7 }, { x: 14, y: 7 }, { x: 15, y: 7 }],
    storyAllies: [
      { commander: "王兆才", type: "rifle", level: 2, weapon: "type38", duty: "第40军第118师配属尖兵" },
      { commander: "刘维汉", type: "mg", level: 1, weapon: "zb26", duty: "第40军机枪配属分队" },
      { commander: "蒋庆泉", type: "rifle", level: 1, weapon: "type38", duty: "第118师温井方向配属" },
    ],
    equipmentEra: "early" as const,
    weaponRewards: ["zhongzheng", "type92_infantry_gun"],
    attachmentRewards: ["field_telephone"],
    enemies: [
      { type: "rifle", x: 9, y: 4, name: "韩6师2团3营前卫连", equipment: "M1加兰德步枪", exp: 55, commanderId: "kim-jong-oh", title: "敌军主将", dropOptions: ["field_manual", "medkit"] },
      { type: "rifle", x: 10, y: 7, name: "韩6师2团3营先遣连", equipment: "M1卡宾枪", exp: 48 },
      { type: "mg", x: 9, y: 6, name: "韩6师2团3营机枪排", equipment: "勃朗宁M1919机枪", exp: 60 },
      { type: "mortar", x: 11, y: 10, name: "韩6师2团配属炮兵中队", equipment: "M2 60毫米迫击炮", exp: 48 },
      { type: "rifle", x: 10, y: 9, name: "温井警戒排", equipment: "M1加兰德步枪", exp: 40 },
    ],
    variantSlots: [],
    waves: [
      { window: [3, 4], units: [{ type: "rifle", x: 10, y: 2, name: "韩军后续纵队", equipment: "M1加兰德步枪", exp: 40 }] },
    ],
    objectives: [
      { id: "ambush-line", name: "两水洞伏击封锁线", kind: "capture", x: 9, y: 6, owner: "enemy" },
      { id: "onjong", name: "温井", kind: "capture", x: 9, y: 12, owner: "enemy" },
    ],
    evacZone: [],
    itemDrops: [{ x: 6, y: 8, options: ["medkit", "bandage", "ration"] }, { x: 13, y: 8, options: ["medkit", "bandage", "ration"] }],
    places: [
      { x: 9, y: 12, name: "温井" },
      { x: 9, y: 6, name: "两水洞峡谷" },
      { x: 10, y: 2, name: "北镇方向" },
    ],
    scripted: [
      { kind: "nightAssault", turns: [1, 3], attackBonus: 0.18, note: "黄昏夜袭：志愿军近战火力占优" },
    ],
    victory: { requiredCaptures: 2, holdTurns: 1, minSurvivors: 2 },
  },
  {
    id: "m2-unsan",
    name: "云山合围",
    kind: "breakthrough",
    date: "1950年11月1—3日",
    location: "朝鲜云山—城南公路桥",
    historicalOutcome: "志愿军第39军攻入云山并切断南撤通路，美骑兵第1师第8团遭受重创。",
    historicalNote: "美军与韩军正处于换防过程；关卡用两处据点表现云山城与城南撤退公路桥，未核实专名不进入任务。",
    commanders: [
      pva("wu-xinquan", "吴信泉", "第39军军长", "中国人民志愿军第39军", "wu-xinquan"),
      un("hobart-gay", "霍巴特·盖伊", "师长", "美国陆军骑兵第1师", undefined, "少将", "us-major-general"),
      un("paik-sun-yup", "白善烨", "师长", "韩国陆军第1步兵师", undefined, "准将（1950年11月）", "rok-brigadier-general"),
    ],
    brief: "趁美韩换防间隙从北、西北两翼压缩云山，夺取城区后向南封锁公路桥。美军后卫会沿唯一撤退轴接应，必须保留火力封住桥头。",
    mapNote: "北在上；云山城位于河谷中央，城南公路越过支流后继续向清川江方向；目标统一使用功能名“城南公路桥”。",
    weather: { options: ["clear", "overcast"], label: "寒冷夜战", detail: "入夜后气温下降，山谷间有薄雾。" },
    playerEquipment: PVA_EARLY,
    enemyDamageMultiplier: 0.75,
    // 取消“溃散后自动推进”后，夺取第二个据点需要显式行军；保留两回合机动窗口。
    maxTurns: 24,
    map: [
      "^^^^^F..F....F..^^^^",
      "^^^^FF..F.==.F..F^^^",
      "^^^FF...F.==.F...F^^",
      "^^F.....F.==.F....F^",
      "FFFF^^^..=V=..^^^FFF",
      "FFFF.....=.=.....FFF",
      "^^^^^F...==...F^^^^^",
      "FFFF.....==.....FFFF",
      "~~~~~~~~~==~~~~~~~~~",
      "FFFFF^^.B==B.^^FFFFF",
      "FFFF..F..===..F.FFFF",
      "^^^^^....==....^^^^^",
      "^^^^^....==....^^^^^",
      "^^^^^F...==...F^^^^^"
    ],
    playerSpawns: [{ x: 4, y: 2 }, { x: 5, y: 3 }, { x: 7, y: 2 }, { x: 3, y: 4 }, { x: 4, y: 5 }, { x: 6, y: 4 }, { x: 8, y: 3 }, { x: 9, y: 4 }],
    storyAllies: [
      { commander: "曹辉章", type: "rifle", level: 2, weapon: "zhongzheng", attachment: "field_telephone", duty: "第39军云山方向配属步兵" },
      { commander: "张明禄", type: "mortar", level: 2, weapon: "mortar60", duty: "第39军迫击炮配属" },
    ],
    equipmentEra: "early" as const,
    weaponRewards: ["zb26"],
    attachmentRewards: ["ammo_carrier"],
    enemies: [
      { type: "rifle", x: 10, y: 4, name: "美骑8团步兵", equipment: "M1加兰德步枪", exp: 55, commanderId: "hobart-gay", title: "敌军主将", dropOptions: ["field_manual", "at_charge"], dropWeapons: ["bar_m1918a2"] },
      { type: "rifle", x: 12, y: 6, name: "韩军换防部队", equipment: "M1卡宾枪", exp: 48 },
      { type: "mg", x: 9, y: 4, name: "美骑8团火力排", equipment: "勃朗宁M1919机枪", exp: 58 },
      { type: "mg", x: 11, y: 10, name: "桥头机枪班", equipment: "勃朗宁M1919机枪", exp: 45 },
      { type: "mortar", x: 13, y: 7, name: "城南迫击炮组", equipment: "M1型81毫米迫击炮", exp: 42 },
      { type: "artillery", x: 14, y: 12, name: "城南师属炮兵", equipment: "M2A1 105毫米榴弹炮", exp: 50 },
    ],
    variantSlots: [],
    waves: [
      { window: [4, 5], units: [
        { type: "rifle", x: 10, y: 12, name: "美骑5团接应队", equipment: "M1加兰德步枪", exp: 42 },
        { type: "mg", x: 12, y: 11, name: "桥头增援机枪", equipment: "勃朗宁M1919机枪", exp: 40 },
      ] },
    ],
    objectives: [
      { id: "unsan-town", name: "云山城", kind: "capture", x: 10, y: 4, owner: "enemy" },
      { id: "south-road-bridge", name: "城南公路桥", kind: "capture", x: 10, y: 10, owner: "enemy" },
    ],
    evacZone: [],
    itemDrops: [{ x: 5, y: 8, options: ["medkit", "at_charge", "satchel", "field_manual"] }, { x: 14, y: 8, options: ["at_charge"] }],
    places: [
      { x: 10, y: 4, name: "云山城" },
      { x: 10, y: 10, name: "城南公路桥" },
      { x: 4, y: 8, name: "清川支流" },
    ],
    supplyPoints: [{ x: 5, y: 5 }, { x: 14, y: 9 }],
    scripted: [
      { kind: "nightAssault", turns: [1, 4], attackBonus: 0.2, note: "夜袭换防间隙：近战加成" },
      { kind: "supplyWindow", untilTurn: 8, penalty: 0.1, note: "合围后弹药见底" },
    ],
    victory: { requiredCaptures: 2, holdTurns: 1, minSurvivors: 2 },
  },
  {
    id: "m3-chongchon",
    name: "清川江穿插",
    kind: "breakthrough",
    date: "1950年11月25日—12月2日",
    location: "朝鲜德川—三所里—龙源里",
    historicalOutcome: "志愿军第二次战役西线突破韩军防线并向三所里穿插，迫使美第8集团军全面后撤。",
    historicalNote: "关卡聚焦第38军第113师向敌后公路穿插的战术片段（约14小时/145华里为战史叙事）；不表现整条清川江渡河战线。",
    commanders: [
      pva("liang-xingchu", "梁兴初", "第38军军长", "中国人民志愿军第38军（含第113师穿插）"),
      un("walton-walker", "沃尔顿·沃克", "第8集团军司令", "美国陆军第8集团军", undefined, "中将", "us-lieutenant-general"),
    ],
    brief: "沿山脊绕开正面火力，抢占三所里与龙源里两个公路节点，截断南撤车队。时间比歼敌更重要，过度恋战会错过窗口。",
    mapNote: "北在上；关卡聚焦军隅里以南的敌后道路网。三所里与龙源里位于横向撤退道路上，南北山路是第38军急行穿插轴；清川江只作为北缘战役背景。",
    weather: { options: ["snow", "overcast"], label: "初雪与冻土", detail: "寒潮到来，山路结冰，部队移动与远射均受影响。" },
    playerEquipment: PVA_EARLY,
    enemyDamageMultiplier: 0.8,
    maxTurns: 16,
    map: [
      "~~~~~~~~~..~~~~~~~~~",
      "~~~~~~~~~==~~~~~~~~~",
      "~~~~~~~~~==~~~~~~~~~",
      "FFFFF^^..==..^^FFFFF",
      "^^^^F....==....F^^^^",
      "=======V=====V======",
      "^^^^^F...==...F^^^^^",
      "FFFF^^F..==..F^^FFFF",
      "^^^^F....==....F^^^^",
      "FFFFF^^..==..^^FFFFF",
      "FFFF.....==.....FFFF",
      "^^^^^F...==...F^^^^^",
      "^^^^^F...==...F^^^^^",
      "^^^^^FF..==..FF^^^^^"
    ],
    playerSpawns: [{ x: 8, y: 12 }, { x: 9, y: 12 }, { x: 10, y: 12 }, { x: 11, y: 12 }, { x: 7, y: 11 }, { x: 9, y: 11 }, { x: 10, y: 11 }, { x: 12, y: 11 }],
    storyAllies: [
      { commander: "杨育才", type: "rifle", level: 2, weapon: "zhongzheng", duty: "第38军穿插配属尖兵" },
      { commander: "周厚刚", type: "mortar", level: 2, weapon: "mortar60", duty: "第38军迫击炮配属" },
      { commander: "倪恩德", type: "rifle", level: 1, weapon: "type38", duty: "第113师穿插配属" },
    ],
    equipmentEra: "early" as const,
    weaponRewards: ["mortar60"],
    attachmentRewards: ["camouflage_net"],
    enemies: [
      { type: "rifle", x: 5, y: 5, name: "美2师后卫", equipment: "M1加兰德步枪", exp: 85 },
      { type: "rifle", x: 14, y: 5, name: "韩军警戒营", equipment: "M1卡宾枪", exp: 45, title: "精锐指挥官", dropOptions: ["field_manual", "satchel"], dropWeapons: ["m2hb"] },
      { type: "mg", x: 10, y: 5, name: "公路护卫火力组", equipment: "勃朗宁M1919机枪", exp: 95 },
      { type: "mortar", x: 12, y: 2, name: "美军迫击炮组", equipment: "M1型81毫米迫击炮", exp: 55 },
      { type: "rifle", x: 10, y: 4, name: "军隅里后卫", equipment: "M1加兰德步枪", exp: 50 },
    
    ],
    variantSlots: [],
    waves: [{ window: [3, 4], units: [{ type: "rifle", x: 10, y: 1, name: "南撤公路纵队", equipment: "M1加兰德步枪", exp: 80 }] }],
    objectives: [
      { id: "samsori", name: "三所里", kind: "capture", x: 5, y: 5, owner: "enemy" },
      { id: "yongwon", name: "龙源里", kind: "capture", x: 14, y: 5, owner: "enemy" },
    ],
    evacZone: [],
    itemDrops: [{ x: 4, y: 8, options: ["medkit", "bandage", "ration"] }, { x: 15, y: 8, options: ["at_charge", "arty_support"] }],
    places: [
      { x: 5, y: 5, name: "三所里" },
      { x: 14, y: 5, name: "龙源里" },
      { x: 5, y: 1, name: "清川江战线" },
    ],
    scripted: [
      { kind: "nightAssault", turns: [1, 3], attackBonus: 0.15, note: "穿插夜战：近战加成" },
      { kind: "supplyWindow", untilTurn: 6, penalty: 0.16, note: "携行弹药见底：攻击衰减" },
    ],
    victory: { requiredCaptures: 2, holdTurns: 3, minSurvivors: 2 },
  },
  {
    id: "m4-chosin",
    name: "长津湖断路",
    kind: "withdraw",
    date: "1950年11月27日—12月3日",
    location: "朝鲜长津湖柳潭里—下碣隅里公路",
    historicalOutcome: "志愿军第9兵团围攻美第10军部队；美陆战1师经下碣隅里向兴南有组织撤出，双方均伤亡惨重。",
    historicalNote: "Fox连始终守住死鹰岭通路；本关只抽象志愿军第59师方向在主补给路附近设置的临时路障，结束点是接到脱离命令，不宣称最终控制Toktong Pass。",
    commanders: [
      pva("song-shilun", "宋时轮", "第9兵团司令员", "中国人民志愿军第9兵团", "song-shilun"),
      un("oliver-smith", "奥利弗·史密斯", "师长", "美国海军陆战队第1师", "oliver-smith", "少将", "us-major-general"),
      un("edward-almond", "爱德华·阿尔蒙德", "第10军军长", "美国陆军第10军", undefined, "少将（1950年11月）", "us-major-general"),
    ],
    brief: "在极寒中依托主补给路北、南两段临时路障，反复迟滞由柳潭里向下碣隅里收缩的陆战队纵队。敌军会从公路两端夹击清障；坚持到脱离命令下达并保存高大全。",
    mapNote: "北在上；道路由西北柳潭里方向斜向东南下碣隅里，长津湖占据东侧。两处目标是主补给路沿线临时路障；Fox连控制的死鹰岭高地仍属美军通路防御体系。",
    weather: { options: ["snow"], label: "极寒暴雪", detail: "约零下二三十摄氏度的严寒；积雪降低移动力与远程火力。" },
    enemyDamageMultiplier: 1.15,
    playerEquipment: PVA_EARLY,
    maxTurns: 20,
    map: [
      "FFFF^^....~~~~~~~~~~",
      "FFFF^^=...~~~~~~~~~~",
      "FFFF^^=...~~~~~~~~~~",
      "FFFFF^==..~~~~~~~~~~",
      "FFFF^^.==.~~~~~~~~~~",
      "^^^^^F..==..~~~~~~~~",
      "FFFF^^..B=..~~~~~~~~",
      "FFFFF^^..=B..~~~~~~~",
      "^^^^^FF...==..~~~~~~",
      "FFFF^^FF...==..~~~~~",
      "FFFFF^^FF...==..~~~~",
      "FFFF^^FFF....==..~~~",
      "FFFF^^FFF....==.....",
      "FFFF^^FFF....==....."
    ],
    playerSpawns: [{ x: 5, y: 6 }, { x: 6, y: 6 }, { x: 7, y: 6 }, { x: 11, y: 7 }, { x: 12, y: 7 }, { x: 6, y: 7 }, { x: 7, y: 7 }, { x: 12, y: 8 }],
    storyAllies: [
      { commander: "杨根思", type: "rifle", level: 2, weapon: "zhongzheng", duty: "第20军58师172团3连连长" },
      { commander: "李玉安", type: "mg", level: 2, weapon: "zb26", duty: "冰雕连火力骨干" },
      { commander: "陈德忠", type: "logistics", level: 2, weapon: "supply_cart", duty: "第9兵团极寒辎重配属" },
    ],
    equipmentEra: "early" as const,
    weaponRewards: ["mosin"],
    attachmentRewards: ["winter_kit", "medic_team"],
    enemies: [
      { type: "rifle", x: 6, y: 1, name: "陆战5团先头分队", equipment: "M1加兰德步枪", exp: 75 },
      { type: "rifle", x: 15, y: 12, name: "下碣隅里接应队", equipment: "M1加兰德步枪", exp: 75 },
      { type: "mg", x: 7, y: 3, name: "陆战7团2营F连通路警戒", equipment: "BAR／勃朗宁M1919机枪", exp: 60, commanderId: "oliver-smith", title: "敌军主将", dropOptions: ["medkit", "field_manual"] },
      { type: "rifle", x: 8, y: 8, name: "公路搜索班", equipment: "M1卡宾枪", exp: 30 },
    ],
    variantSlots: [],
    waves: [
      { window: [6, 7], units: [{ type: "rifle", x: 6, y: 1, name: "柳潭里撤退纵队", equipment: "M1加兰德步枪", exp: 55 }, { type: "mg", x: 7, y: 3, name: "纵队火力", equipment: "勃朗宁M1919机枪", exp: 45 }] },
      { window: [10, 11], units: [{ type: "rifle", x: 15, y: 12, name: "下碣隅里清障分队", equipment: "M1加兰德步枪", exp: 45 }] },
    ],
    objectives: [
      { id: "msr-north-roadblock", name: "MSR北段临时路障", kind: "hold", x: 8, y: 6, owner: "player" },
      { id: "msr-south-roadblock", name: "MSR南段临时路障", kind: "hold", x: 11, y: 7, owner: "player" },
    ],
    evacZone: [
      { x: 2, y: 3 }, { x: 2, y: 4 }, { x: 2, y: 5 }, { x: 2, y: 6 }, { x: 2, y: 7 }, { x: 2, y: 8 },
      { x: 3, y: 3 }, { x: 3, y: 4 }, { x: 3, y: 5 }, { x: 3, y: 6 }, { x: 3, y: 7 },
      { x: 4, y: 5 }, { x: 4, y: 6 }, { x: 5, y: 5 }, { x: 5, y: 6 },
    ],
    itemDrops: [{ x: 5, y: 9, options: ["medkit", "at_charge", "satchel", "field_manual"] }, { x: 13, y: 9, options: ["at_charge"] }],
    places: [
      { x: 7, y: 3, name: "Fox连防御高地" },
      { x: 6, y: 1, name: "柳潭里方向" },
      { x: 15, y: 12, name: "下碣隅里方向" },
      { x: 16, y: 4, name: "长津湖" },
    ],
    supplyPoints: [{ x: 5, y: 7 }, { x: 12, y: 8 }],
    scripted: [
      { kind: "coldAttrition", fromTurn: 4, damage: 1, note: "极寒冻伤：双方持续减员" },
    ],
    // 须击溃 2 个外围单位再撤离，避免只摸掉搜索班后秒撤
    victory: { minEvacuated: 2, evacuateRatio: 0.25, requireKeyUnit: true, minEnemiesRouted: 2 },
  },
  {
    id: "m5-third-offensive",
    name: "突破三八线",
    kind: "breakthrough",
    date: "1950年12月31日—1951年1月8日",
    location: "朝鲜临津江—议政府方向",
    historicalOutcome: "志愿军与朝鲜人民军突破三八线防御，联合国军撤出汉城。",
    historicalNote: "关卡表现第三次战役西线的一段渡河与山口突破。",
    commanders: [
      pva("peng-dehuai", "彭德怀", "司令员兼政治委员", "中国人民志愿军", "peng-dehuai"),
      un("matthew-ridgway", "马修·李奇微", "第8集团军司令", "美国陆军第8集团军", "matthew-ridgway", "中将", "us-lieutenant-general"),
    ],
    brief: "从北岸夜渡临津江，先夺取渡河带，再沿狭窄走廊向南突破议政府北侧山口。守军正向纵深收缩，必须在其完成部署前连续占领两个节点。",
    mapNote: "北在上；玩家由北向南推进。临津江横贯北部，中央公路依次通过渡河带和议政府北侧山口，目标呈前后梯次。",
    weather: { options: ["snow", "clear"], label: "隆冬冻江", detail: "河面部分冻结，夜间严寒，部队体力消耗明显。" },
    enemyDamageMultiplier: 0.9,
    playerEquipment: PVA_EARLY,
    maxTurns: 18,
    map: [
      "...^^F........F^^...",
      "...^^F.==..==.F^^...",
      "...^^F.==..==.F^^...",
      "...F...==..==...F...",
      "...~~~~==~~==~~~~...",
      "...FF^^.==..==.^^FF.",
      "...^F...==..==...F^.",
      "...^^F..==..==..F^^.",
      "...F^^F.==..==.F^^F.",
      "...^^F..=V..=V..F^^.",
      "...F....==..==....F.",
      "...FF^^.==..==.^^FF.",
      "...FF^^.==..==.^^FF.",
      "...FF^^.==..==.^^FF."
    ],
    playerSpawns: [{ x: 7, y: 1 }, { x: 8, y: 1 }, { x: 9, y: 1 }, { x: 10, y: 1 }, { x: 11, y: 1 }, { x: 8, y: 2 }, { x: 10, y: 2 }, { x: 12, y: 2 }],
    storyAllies: [
      { commander: "高玉宝", type: "rifle", level: 3, weapon: "mosin", duty: "第三次战役渡河配属步兵" },
      { commander: "孙生禄", type: "mg", level: 2, weapon: "dp28", duty: "临津江方向火力配属" },
    ],
    equipmentEra: "late" as const,
    weaponRewards: ["dp28"],
    attachmentRewards: ["motor_transport"],
    enemies: [
      { type: "rifle", x: 8, y: 4, name: "联合国军江岸前哨", equipment: "M1加兰德步枪", exp: 62 },
      { type: "rifle", x: 12, y: 9, name: "韩军山口守备队", equipment: "M1卡宾枪", exp: 48 },
      { type: "mg", x: 11, y: 4, name: "渡口机枪阵地", equipment: "勃朗宁M1919机枪", exp: 70, title: "精锐指挥官", dropOptions: ["at_charge", "field_manual"] },
      { type: "mortar", x: 13, y: 7, name: "山口迫击炮组", equipment: "M1型81毫米迫击炮", exp: 55 },
      { type: "artillery", x: 14, y: 12, name: "纵深炮兵阵地", equipment: "M2A1 105毫米榴弹炮", exp: 55 },
      { type: "rifle", x: 9, y: 7, name: "走廊后卫", equipment: "M1加兰德步枪", exp: 50 },
    ],
    variantSlots: [],
    waves: [{ window: [6, 7], units: [{ type: "rifle", x: 10, y: 12, name: "议政府公路后卫", equipment: "M1加兰德步枪", exp: 50 }] }],
    objectives: [
      { id: "imjin-crossing", name: "临津江渡河带", kind: "capture", x: 8, y: 4, owner: "enemy" },
      { id: "uigongbu-pass", name: "议政府北侧山口", kind: "capture", x: 12, y: 9, owner: "enemy" },
    ],
    evacZone: [],
    itemDrops: [{ x: 6, y: 7, options: ["medkit", "bandage", "ration"] }, { x: 13, y: 7, options: ["at_charge", "arty_support"] }],
    places: [
      { x: 8, y: 4, name: "临津江" },
      { x: 12, y: 9, name: "议政府北侧山口" },
      { x: 10, y: 12, name: "议政府方向" },
    ],
    scripted: [
      { kind: "nightAssault", turns: [1, 3], attackBonus: 0.12, note: "三八线夜袭" },
      { kind: "supplyWindow", untilTurn: 7, penalty: 0.14, note: "礼拜攻势：弹药见底" },
    ],
    victory: { requiredCaptures: 2, holdTurns: 3, minSurvivors: 2 },
  },
  {
    id: "m6-hoengsong",
    name: "横城反击",
    kind: "breakthrough",
    date: "1951年2月11—13日",
    location: "韩国横城北部山地",
    historicalOutcome: "志愿军对韩军第8师方向实施反击，联合国军中部战线被迫后撤。",
    historicalNote: "游戏聚焦雪夜穿插和切断横城公路，不把砥平里防御战合并进本关。",
    commanders: [
      pva("wen-yucheng", "温玉成", "第40军军长", "中国人民志愿军第40军"),
      un("edward-almond", "爱德华·阿尔蒙德", "第10军军长", "美国陆军第10军", undefined, "少将（1951年2月）", "us-major-general"),
    ],
    brief: "在雪夜从突出部两翼越过山脊，先切断横城北侧公路节点，再夺南撤公路口。敌军火力强但部署拉长，合围割路比正面硬攻有效。",
    mapNote: "北在上；中央南北公路穿过韩军突出部，南侧道路通向横城—原州撤退轴。玩家从北侧及两翼山路进入，目标沿撤退方向前后排列。",
    weather: { options: ["snow", "fog"], label: "雪夜低云", detail: "积雪与低云降低双方机动和远程观察。" },
    playerEquipment: PVA_EARLY,
    enemyDamageMultiplier: 1.02,
    maxTurns: 18,
    map: [
      "^^^^^F........F^^^^^",
      "^^^^^F...==...F^^^^^",
      "^^^^#F...==...F#^^^^",
      "FFFF^^F..==..F^^FFFF",
      "^^^^^F...==...F^^^^^",
      "FFFF^^...==...^^FFFF",
      "^^^^^FF..=V=..FF^^^^",
      "FFFF^^F..==..F^^FFFF",
      "^^^^^F...==...F^^^^^",
      "FFFF^^...==...^^FFFF",
      "=======V===..F^^FFFF",
      "^^^^^FF...=...FF^^^^",
      "^^^^^FF...=...FF^^^^",
      "^^^^#FF...=...FF#^^^"
    ],
    playerSpawns: [{ x: 6, y: 2 }, { x: 7, y: 3 }, { x: 9, y: 2 }, { x: 12, y: 2 }, { x: 13, y: 3 }, { x: 3, y: 5 }, { x: 16, y: 5 }, { x: 15, y: 6 }],
    storyAllies: [
      { commander: "张桃芳", type: "rifle", level: 3, weapon: "mosin", duty: "横城方向狙击与尖兵配属" },
      { commander: "周厚刚", type: "mortar", level: 3, weapon: "mortar82", duty: "第40军迫击炮配属" },
    ],
    equipmentEra: "late" as const,
    weaponRewards: ["ppsh50", "mortar120"],
    attachmentRewards: ["artillery_tractor"],
    enemies: [
      { type: "rifle", x: 10, y: 6, name: "韩军第8师步兵", equipment: "M1加兰德步枪", exp: 50, commanderId: "edward-almond", title: "敌军主将", dropOptions: ["field_manual", "arty_support"] },
      { type: "rifle", x: 7, y: 10, name: "美军交通警戒队", equipment: "M1卡宾枪", exp: 55 },
      { type: "mg", x: 9, y: 6, name: "突出部公路火力点", equipment: "勃朗宁M1919机枪", exp: 60 },
      { type: "mortar", x: 13, y: 8, name: "美军迫击炮组", equipment: "M1型81毫米迫击炮", exp: 55 },
    
    ],
    variantSlots: [],
    waves: [{ window: [9, 10], units: [{ type: "rifle", x: 10, y: 12, name: "横城后卫", equipment: "M1加兰德步枪", exp: 35 }] }],
    objectives: [
      { id: "hoengsong-north", name: "横城北侧公路节点", kind: "capture", x: 10, y: 6, owner: "enemy" },
      { id: "wonju-road", name: "横城—原州南撤公路口", kind: "capture", x: 7, y: 10, owner: "enemy" },
    ],
    evacZone: [],
    itemDrops: [{ x: 6, y: 8, options: ["medkit", "bandage", "ration"] }, { x: 13, y: 8, options: ["at_charge"] }],
    places: [
      { x: 10, y: 6, name: "横城北侧公路节点" },
      { x: 7, y: 10, name: "原州方向" },
    ],
    scripted: [
      { kind: "nightAssault", turns: [1, 3], attackBonus: 0.14, note: "横城夜袭" },
    ],
    victory: { requiredCaptures: 2, holdTurns: 2, minSurvivors: 2 },
  },
  {
    id: "m7-chipyongni",
    name: "砥平里外线",
    kind: "withdraw",
    date: "1951年2月13—15日",
    location: "韩国砥平里环形阵地外围",
    historicalOutcome: "美23团战斗队与法军营守住砥平里，增援装甲纵队打通通路；志愿军停止进攻并撤出。",
    historicalNote: "本关不允许玩家虚构攻占砥平里；目标是夜间牵制后在白昼空中火力到来前脱离。",
    commanders: [
      pva("wu-xinquan", "吴信泉", "第39军军长", "中国人民志愿军第39军"),
      un("paul-freeman", "保罗·弗里曼", "第23团团长", "美国陆军第2师第23步兵团", undefined, "上校", "us-colonel"),
      un("ralph-monclar", "拉尔夫·蒙克拉尔", "法军营营长", "法国联合国营", undefined, "临时中校", "fr-lieutenant-colonel"),
    ],
    brief: "砥平里守军已构成环形阵地。先击溃至少一个外围火力点完成牵制，再让高大全和至少三分之二的分队从北侧山路撤出。不要攻入核心村镇同炮兵与装甲纵队消耗。",
    mapNote: "村镇与连续堡垒环代表砥平里防御圈；北侧整行是脱离地域，南侧道路是克伦贝装甲特遣队解围方向。",
    weather: { options: ["snow", "overcast"], label: "残雪与低云", detail: "夜间寒冷，天亮后能见度逐步改善。" },
    playerEquipment: PVA_EARLY,
    enemyDamageMultiplier: 1.3,
    maxTurns: 18,
    map: [
      "FF................FF",
      "FF==========^=====FF",
      "FF================FF",
      "FF^^=F....==....F=^^",
      "FF....^^^BBBB^^^....",
      "FF...^^BB....BB^^...",
      "FF..^^BBB.VV.BBB^^..",
      "FF...^^BB....BB^^...",
      "FF....^^^BBBB^^^....",
      "FFFFF^^^..==..^^^FFF",
      "FFFF......==......FF",
      "FF^^F.....==.....F^^",
      "FF^^F.....==.....F^^",
      "FF^^FF....==....FF^^"
    ],
    playerSpawns: [{ x: 3, y: 5 }, { x: 4, y: 6 }, { x: 5, y: 6 }, { x: 14, y: 6 }, { x: 15, y: 6 }, { x: 16, y: 5 }, { x: 4, y: 4 }, { x: 15, y: 4 }],
    storyAllies: [
      { commander: "王兆才", type: "rifle", level: 3, weapon: "mosin", duty: "砥平里外线牵制配属" },
      { commander: "刘维汉", type: "mg", level: 3, weapon: "dp28", duty: "外线掩护火力配属" },
    ],
    equipmentEra: "late" as const,
    weaponRewards: ["bazooka"],
    attachmentRewards: ["scr300_radio"],
    enemies: [
      { type: "mg", x: 7, y: 7, name: "美23团西侧火力点", equipment: "勃朗宁M1919机枪", exp: 110 },
      { type: "mg", x: 12, y: 7, name: "法军营东侧火力点", equipment: "MAC 24/29轻机枪", exp: 110 },
      { type: "rifle", x: 10, y: 6, name: "美23团核心步兵", equipment: "M1加兰德步枪", exp: 83, commanderId: "paul-freeman", title: "敌军主将", dropOptions: ["field_manual", "medkit"], dropWeapons: ["m2_4_2_mortar"] },
    ],
    variantSlots: [],
    waves: [{ window: [8, 9], units: [
      { type: "tank", x: 9, y: 12, name: "克伦贝装甲纵队", equipment: "M4A3E8谢尔曼坦克", exp: 69 },
      { type: "rifle", x: 10, y: 12, name: "美骑5团增援", equipment: "M1加兰德步枪", exp: 69 },
    ] }],
    objectives: [],
    evacZone: Array.from({ length: 20 }, (_, x) => ({ x, y: 0 })),
    itemDrops: [{ x: 7, y: 9, options: ["medkit", "bandage", "ration"] }, { x: 12, y: 9, options: ["medkit", "at_charge", "satchel", "field_manual"] }],
    places: [
      { x: 10, y: 6, name: "砥平里" },
      { x: 10, y: 1, name: "北撤通道" },
    ],
    scripted: [
      { kind: "barrage", turns: [4, 7], damage: 5, note: "联合国军炮兵与空中支援压制" },
      { kind: "supplyWindow", untilTurn: 7, penalty: 0.14, note: "外线弹药耗尽" },
    ],
    victory: { minEvacuated: 4, evacuateRatio: 0.5, requireKeyUnit: true, minEnemiesRouted: 1 },
  },
  {
    id: "m8-imjin",
    name: "临津江渡河",
    kind: "breakthrough",
    date: "1951年4月22—25日",
    location: "韩国临津江—雪马里—235高地",
    historicalOutcome: "志愿军第63军渡过临津江并包围英军格洛斯特营；英29旅迟滞了攻势后南撤。",
    historicalNote: "关卡目标限定为建立桥头堡和夺取235高地，不把整个春季攻势简化为单场胜负。",
    commanders: [
      pva("fu-chongbi", "傅崇碧", "第63军军长", "中国人民志愿军第63军"),
      un("james-carne", "詹姆斯·卡恩", "营长", "英军格洛斯特郡团第1营", undefined, "中校", "uk-lieutenant-colonel"),
    ],
    brief: "从北岸夜渡临津江，夺取南岸桥头后沿雪马里谷地分割英军，最后攻上235高地。三个地段是连续纵深，不要在渡口与高地同时分兵硬冲。",
    mapNote: "北在上；玩家由北向南推进。临津江横在北部，雪马里位于中央谷地，235高地是南端终局据点。",
    weather: { options: ["clear", "fog"], label: "春夜薄雾", detail: "夜间河谷能见度有限，白天气象适合联合国军空中支援。" },
    enemyDamageMultiplier: 1.05,
    playerEquipment: PVA_LATE,
    maxTurns: 17,
    map: [
      "...^^F........F^^...",
      "...^^F...==...F^^...",
      "...^^F...==...F^^...",
      "...FF....==....FF...",
      "...~~~~~~==~~~~~~...",
      "...F^^...=B...^^F...",
      "...^^F...==...F^^...",
      "...F^^F..=V..F^^F...",
      "...^^F...==...F^^...",
      "...F^^F..==..F^^F...",
      "...^^F...==...F^^...",
      "...FFF...=B...FFF...",
      "...FFF...==...FFF...",
      "...FFF...==...FFF..."
    ],
    playerSpawns: [{ x: 7, y: 1 }, { x: 8, y: 1 }, { x: 9, y: 1 }, { x: 10, y: 1 }, { x: 11, y: 1 }, { x: 8, y: 2 }, { x: 10, y: 2 }, { x: 12, y: 2 }],
    storyAllies: [
      { commander: "杨育才", type: "rifle", level: 3, weapon: "ppsh50", duty: "第63军渡河尖兵配属" },
      { commander: "孙生禄", type: "mg", level: 3, weapon: "dp28", duty: "雪马里方向火力配属" },
      { commander: "陈德忠", type: "logistics", level: 2, weapon: "supply_cart", duty: "渡河辎重配属" },
    ],
    equipmentEra: "late" as const,
    weaponRewards: ["mortar82"],
    attachmentRewards: ["rangefinder"],
    enemies: [
      { type: "rifle", x: 10, y: 5, name: "临津江南岸前哨", equipment: "李-恩菲尔德No.4步枪", exp: 75 },
      { type: "rifle", x: 10, y: 11, name: "格洛斯特营235高地守军", equipment: "李-恩菲尔德No.4步枪", exp: 72, commanderId: "james-carne", title: "敌军主将", dropOptions: ["field_manual", "bandage"], dropWeapons: ["qf25"] },
      { type: "mg", x: 9, y: 7, name: "雪马里布伦机枪组", equipment: "布伦轻机枪／维克斯机枪", exp: 80 },
      { type: "artillery", x: 14, y: 12, name: "英军师属炮兵", equipment: "M2A1 105毫米榴弹炮", exp: 65 },
      { type: "rifle", x: 12, y: 9, name: "英军后备步兵", equipment: "李-恩菲尔德No.4步枪", exp: 55 },
    ],
    variantSlots: [],
    waves: [{ window: [8, 9], units: [{ type: "tank", x: 10, y: 12, name: "第8骠骑兵支援", equipment: "百夫长Mk.3坦克", exp: 70 }] }],
    objectives: [
      { id: "imjin-bridgehead", name: "临津江南岸桥头", kind: "capture", x: 10, y: 5, owner: "enemy" },
      { id: "gloster-hill", name: "235高地", kind: "capture", x: 10, y: 11, owner: "enemy" },
    ],
    evacZone: [],
    itemDrops: [{ x: 6, y: 8, options: ["medkit", "bandage", "ration"] }, { x: 13, y: 8, options: ["at_charge", "arty_support"] }],
    places: [
      { x: 10, y: 5, name: "桥头堡" },
      { x: 10, y: 11, name: "235高地" },
      { x: 10, y: 7, name: "雪马里" },
      { x: 5, y: 4, name: "临津江" },
    ],
    scripted: [
      { kind: "barrage", turns: [4, 7], damage: 4, note: "英军炮火拦阻射击" },
      { kind: "supplyWindow", untilTurn: 8, penalty: 0.1, note: "渡河后弹药见底" },
    ],
    victory: { requiredCaptures: 2, holdTurns: 1, minSurvivors: 6 },
  },
  {
    id: "m9-cheorwon",
    name: "铁原阻击",
    kind: "withdraw",
    date: "1951年5月29日—6月10日",
    location: "韩国铁原—涟川交通走廊",
    historicalOutcome: "志愿军第63军在铁原地区实施纵深阻击，为主力完成休整和建立新防线争取时间。",
    historicalNote: "本关强调迟滞与轮换，不以歼灭追击部队为目标。",
    commanders: [
      pva("fu-chongbi", "傅崇碧", "第63军军长", "中国人民志愿军第63军"),
      un("james-van-fleet", "詹姆斯·范弗里特", "第8集团军司令", "美国陆军第8集团军", undefined, "中将（1951年5月）", "us-lieutenant-general"),
    ],
    brief: "依托铁原南北走廊的两道阵地轮换阻击，拖住由涟川方向北上的追击纵队。完成接触迟滞后向北侧纵深撤离，高大全与至少六成部队必须脱离；任务是争取时间而非全歼追兵。",
    mapNote: "北在上；铁原纵深在北，联合国军从南缘沿中央公路向北追击。前沿公路口在南，第二阻击线高地在北，纠正旧图反向。",
    weather: { options: ["rain", "overcast"], label: "初夏阵雨", detail: "道路泥泞，低云抑制远程观察，但装甲仍可沿公路推进。" },
    playerEquipment: PVA_LATE,
    maxTurns: 19,
    map: [
      "^^^^^FF......FF^^^^^",
      "^^^^^FF..==..FF^^^^^",
      "^^^^^FF..==..FF^^^^^",
      "FFFF^^F..==..F^^FFFF",
      "^^^^^F...=B...F^^^^^",
      "FFFF^^F..==..F^^FFFF",
      "^^^^^F.B.==.B.F^^^^^",
      "FFFF^^F..==..F^^FFFF",
      "^^^^^F.^.==...F^^^^^",
      "FFFF^^F..==..F^^FFFF",
      "FFFFF....==....FFFFF",
      "^^^^^F...==...F^^^^^",
      "^^^^^F...==...F^^^^^",
      "^^^^^F...==...F^^^^^"
    ],
    playerSpawns: [{ x: 7, y: 6 }, { x: 8, y: 6 }, { x: 11, y: 6 }, { x: 12, y: 6 }, { x: 7, y: 5 }, { x: 12, y: 5 }, { x: 9, y: 4 }, { x: 11, y: 4 }],
    storyAllies: [
      { commander: "李玉安", type: "rifle", level: 3, weapon: "mosin", duty: "63军铁原阻击配属" },
      { commander: "倪恩德", type: "mg", level: 3, weapon: "dp28", duty: "走廊火力配属" },
      { commander: "高玉宝", type: "logistics", level: 2, weapon: "supply_cart", duty: "北撤辎重配属" },
    ],
    equipmentEra: "late" as const,
    weaponRewards: ["mosin", "zis3"],
    enemies: [
      { type: "rifle", x: 8, y: 11, name: "美3师追击步兵", equipment: "M1加兰德步枪", exp: 55 },
      { type: "rifle", x: 11, y: 11, name: "美骑1师步兵", equipment: "M1加兰德步枪", exp: 55 },
      { type: "mg", x: 9, y: 12, name: "美军支援火力组", equipment: "勃朗宁M1919机枪", exp: 55 },
      { type: "artillery", x: 15, y: 13, name: "追击纵队炮兵", equipment: "M2A1 105毫米榴弹炮", exp: 40, commanderId: "james-van-fleet", title: "敌军主将", dropOptions: ["field_manual", "arty_support"] },
      { type: "rifle", x: 10, y: 10, name: "美军公路步兵", equipment: "M1加兰德步枪", exp: 35 },
    ],
    variantSlots: [],
    waves: [
      { window: [5, 6], units: [{ type: "rifle", x: 9, y: 12, name: "追击步兵", equipment: "M1加兰德步枪", exp: 50 }, { type: "mg", x: 8, y: 12, name: "追击火力", equipment: "勃朗宁M1919机枪", exp: 45 }] },
      { window: [9, 10], units: [{ type: "rifle", x: 10, y: 12, name: "第二梯队", equipment: "M1加兰德步枪", exp: 50 }] },
    ],
    objectives: [],
    evacZone: [
      { x: 6, y: 0 }, { x: 7, y: 0 }, { x: 8, y: 0 }, { x: 9, y: 0 }, { x: 10, y: 0 }, { x: 11, y: 0 }, { x: 12, y: 0 }, { x: 13, y: 0 },
      { x: 7, y: 1 }, { x: 8, y: 1 }, { x: 9, y: 1 }, { x: 10, y: 1 }, { x: 11, y: 1 }, { x: 12, y: 1 },
    ],
    itemDrops: [{ x: 5, y: 7, options: ["medkit", "at_charge", "satchel", "field_manual"] }, { x: 14, y: 7, options: ["at_charge", "arty_support"] }],
    places: [
      { x: 10, y: 4, name: "第二阻击线" },
      { x: 7, y: 6, name: "前沿公路口" },
      { x: 10, y: 12, name: "涟川追击方向" },
    ],
    supplyPoints: [{ x: 9, y: 5 }, { x: 11, y: 3 }],
    scripted: [
      { kind: "barrage", turns: [5, 8], damage: 2, note: "联合国军炮火准备" },
    ],
    // 须南下接触击溃 2 个单位后再北撤；扩大撤离区降低死档同时保留配额压力
    victory: { minEvacuated: 4, evacuateRatio: 0.45, requireKeyUnit: true, minEnemiesRouted: 2 },
  },
  {
    id: "m10-triangle-hill",
    name: "上甘岭坑道",
    kind: "hold",
    date: "1952年10月14日—11月25日",
    location: "朝鲜五圣山前沿597.9与537.7高地",
    historicalOutcome: "志愿军第15军、第12军依托坑道体系守住主要阵地，联合国军停止进攻。",
    historicalNote: "棋盘把两个主要高地、坑道口和补给线压缩在同一战术视图。",
    commanders: [
      pva("qin-jiwei", "秦基伟", "第15军军长", "中国人民志愿军第15军", "qin-jiwei"),
      un("wayne-smith", "韦恩·史密斯", "师长", "美国陆军第7步兵师", undefined, "少将", "us-major-general"),
    ],
    brief: "开局地表阵地已经失守。依托两个坑道后口组织反击，先夺回597.9和537.7北山，再顶住由金化方向分波次压上的敌军；不能只躲在坑道里等待。",
    mapNote: "北在上；五圣山纵深在北，597.9与537.7北山紧凑相邻，堡垒格表示坑道后口；美7师与韩2师从南侧进攻。",
    weather: { options: ["overcast", "rain", "snow"], label: "深秋转初冬", detail: "战斗持续43天，经历阴雨、低云和初雪。" },
    playerEquipment: PVA_LATE,
    enemyDamageMultiplier: 0.75,
    maxTurns: 17,
    map: [
      "FF^^^FFF....FFF^^^FF",
      "FF^^^FFF.==.FFF^^^FF",
      "FF^^^FFF.==.FFF^^^FF",
      "FF^F^^^^.==.^^^^F^FF",
      "FF^..^^^====^^^..^FF",
      "FF^F.^^^B==B^^^F.^FF",
      "FF^FF^^^.==.^^^FF^FF",
      "FF^F^^F..==..F^^F^FF",
      "FF^^^F...==...F^^^FF",
      "FF^F^^F..==..F^^F^FF",
      "FF^FF....==....FF^FF",
      "FF^^^F...==...F^^^FF",
      "FF^^^F...==...F^^^FF",
      "FF^^^F...==...F^^^FF"
    ],
    playerSpawns: [{ x: 8, y: 5 }, { x: 11, y: 5 }, { x: 6, y: 4 }, { x: 13, y: 4 }, { x: 7, y: 5 }, { x: 12, y: 5 }, { x: 9, y: 6 }, { x: 10, y: 6 }],
    storyAllies: [
      { commander: "黄继光", type: "rifle", level: 4, weapon: "ppsh50", duty: "15军45师135团2营通讯员" },
      { commander: "邱少云", type: "mg", level: 4, weapon: "dp28", duty: "15军87团9连战士" },
      { commander: "孙生禄", type: "logistics", level: 3, weapon: "supply_cart", duty: "坑道补给配属" },
    ],
    equipmentEra: "late" as const,
    weaponRewards: [],
    preMissionWeapons: ["m30_122", "bm13", "mosin_m44_marksman"],
    enemies: [
      { type: "rifle", x: 8, y: 11, name: "美7师突击连", equipment: "M1加兰德步枪", exp: 100, commanderId: "wayne-smith", title: "敌军主将", dropOptions: ["field_manual", "satchel"], dropWeapons: ["m1d_sniper"], dropAttachments: ["t52_vest"] },
      { type: "rifle", x: 11, y: 11, name: "韩2师突击连", equipment: "M1加兰德步枪", exp: 95 },
      { type: "mg", x: 9, y: 11, name: "联合国军火力组", equipment: "勃朗宁M1919机枪", exp: 95 },
      { type: "mortar", x: 10, y: 10, name: "联合国军迫击炮组", equipment: "M1型81毫米迫击炮", exp: 85 },
      { type: "artillery", x: 17, y: 13, name: "联合国军炮兵组", equipment: "M2A1 105毫米榴弹炮", exp: 70 },
      { type: "rifle", x: 10, y: 9, name: "坑道口突击队", equipment: "M1加兰德步枪", exp: 90 },
    ],
    variantSlots: [],
    waves: [
      { window: [2, 3], units: [{ type: "rifle", x: 9, y: 11, name: "轮番突击", equipment: "M1加兰德步枪", exp: 90 }] },
      { window: [5, 6], units: [{ type: "mg", x: 8, y: 10, name: "火力增援", equipment: "勃朗宁M1919机枪", exp: 85 }] },
    ],
    objectives: [
      { id: "hill-5979", name: "597.9高地", kind: "hold", x: 7, y: 4, owner: "enemy" },
      { id: "hill-5377", name: "537.7北山", kind: "hold", x: 12, y: 4, owner: "enemy" },
    ],
    evacZone: [],
    itemDrops: [{ x: 8, y: 8, options: ["medkit", "arty_support"] }, { x: 11, y: 8, options: ["medkit", "at_charge", "satchel", "field_manual"] }],
    places: [
      { x: 7, y: 4, name: "597.9高地" },
      { x: 12, y: 4, name: "537.7北山" },
      { x: 8, y: 5, name: "坑道后口" },
      { x: 10, y: 2, name: "五圣山纵深" },
    ],
    supplyPoints: [{ x: 8, y: 5 }, { x: 11, y: 5 }],
    scripted: [
      { kind: "barrage", turns: [3, 6, 9, 12, 15], damage: 5, note: "上甘岭炮火准备" },
      { kind: "supplyWindow", untilTurn: 5, penalty: 0.16, note: "坑道外弹药耗尽" },
    ],
    // 至少守住一处主峰到结束；炮火与弹药窗口压低蹲坑通关率
    victory: { holdUntilEnd: true, minPostsHeld: 1, minSurvivors: 3 },
  },
  {
    id: "m11-pork-chop",
    name: "猪排山争夺",
    kind: "breakthrough",
    date: "1953年7月6—11日",
    location: "朝鲜铁原西北猪排山前哨",
    historicalOutcome: "志愿军攻击猪排山，美军第7师在反复争夺后奉命放弃该前哨阵地。",
    historicalNote: "本关限定为第23军第67师（含第200团）夺取两个前沿支撑点的战术切片；不把前哨得失夸大为战略决战。215号T-34-85以临时配属剧情单位表现有直接史料支持的装甲协同。",
    commanders: [
      pva("zhong-guochu", "钟国楚", "第23军军长", "中国人民志愿军第23军第67师（首攻第200团）"),
      un("arthur-trudeau", "阿瑟·特鲁多", "师长", "美国陆军第7步兵师", undefined, "少将", "us-major-general"),
    ],
    brief: "借雨雾接近猪排山，夺取东、西两个前沿支撑点并顶住反击。壕沟和高地减伤明显，迫击炮与炮火支援是打开缺口的关键。",
    mapNote: "北在上；东西支撑点位于同一条连续猪排山前哨山脊，由壕沟与地堡相连。玩家从志愿军北侧阵地接近，美军由南侧主抵抗线增援。",
    weather: { options: ["rain", "fog"], label: "季风雨雾", detail: "持续降雨与山雾削弱远程火力，谷地泥泞。" },
    enemyDamageMultiplier: 0.75,
    playerEquipment: PVA_LATE_ARMOR,
    maxTurns: 17,
    map: [
      "FF^^^F........F^^^FF",
      "FF^^^F...==...F^^^FF",
      "FF^^^F...==...F^^^FF",
      "FF^F^^F..==..F^^F^FF",
      "FF^^^FF..==..FF^^^FF",
      "FF^F.^^^^^^^^^^.F^FF",
      "FF^..^^B====B^^..^FF",
      "FF^F.^^^^^^^^^^.F^FF",
      "FF^^^FF..==..FF^^^FF",
      "FF^F^^F..==..F^^F^FF",
      "FF^FF....==....FF^FF",
      "FF^^^F...==...F^^^FF",
      "FF^^^F...==...F^^^FF",
      "FF^^^F...==...F^^^FF"
    ],
    playerSpawns: [{ x: 7, y: 1 }, { x: 8, y: 1 }, { x: 9, y: 1 }, { x: 10, y: 1 }, { x: 11, y: 1 }, { x: 8, y: 2 }, { x: 10, y: 2 }, { x: 12, y: 2 }],
    storyAllies: [
      { commander: "杨育才", type: "rifle", level: 4, weapon: "ppsh50", duty: "第23军第200团突击配属" },
      { commander: "张桃芳", type: "mortar", level: 3, weapon: "mortar82", duty: "前哨火力配属" },
      { commander: "215号坦克车组", type: "tank", level: 4, weapon: "t34_85", equipment: "T-34-85（独立坦克第4团第2连）", duty: "独立坦克第4团第2连车组" },
    ],
    equipmentEra: "late" as const,
    weaponRewards: ["dp28"],
    enemies: [
      { type: "rifle", x: 7, y: 6, name: "美7师前哨西连", equipment: "M1加兰德步枪", exp: 72, commanderId: "arthur-trudeau", title: "敌军主将", dropOptions: ["field_manual", "at_charge"], dropWeapons: ["m1d_sniper", "m1_155"] },
      { type: "rifle", x: 12, y: 6, name: "美7师前哨东连", equipment: "M1加兰德步枪", exp: 72 },
      { type: "mg", x: 9, y: 6, name: "前哨机枪阵地", equipment: "勃朗宁M1919机枪", exp: 95 },
      { type: "artillery", x: 14, y: 12, name: "主抵抗线炮兵组", equipment: "M2A1 105毫米榴弹炮", exp: 88 },
      { type: "mortar", x: 10, y: 10, name: "前哨迫击炮组", equipment: "M1型81毫米迫击炮", exp: 75 },
    ],
    variantSlots: [],
    waves: [
      { window: [4, 4], units: [{ type: "rifle", x: 9, y: 12, name: "第一次反击队", equipment: "M1加兰德步枪", exp: 100 }] },
      { window: [6, 6], units: [
        { type: "mg", x: 10, y: 12, name: "反击火力增援", equipment: "勃朗宁M1919机枪", exp: 90 },
        { type: "rifle", x: 11, y: 12, name: "第二次反击队", equipment: "M1加兰德步枪", exp: 85 },
      ] },
    ],
    objectives: [
      { id: "pork-west", name: "猪排山西支撑点", kind: "capture", x: 7, y: 6, owner: "enemy" },
      { id: "pork-east", name: "猪排山东支撑点", kind: "capture", x: 12, y: 6, owner: "enemy" },
    ],
    evacZone: [],
    itemDrops: [{ x: 6, y: 8, options: ["medkit", "arty_support"] }, { x: 13, y: 8, options: ["medkit", "arty_support"] }],
    places: [
      { x: 7, y: 6, name: "西支撑点" },
      { x: 12, y: 6, name: "东支撑点" },
      { x: 10, y: 6, name: "交通壕" },
    ],
    scripted: [
      { kind: "barrage", turns: [1], damage: 7, target: "enemy", note: "第23军第67师三分钟炮火急袭" },
      { kind: "barrage", turns: [3, 6], damage: 8, note: "美7师炮火反击" },
    ],
    victory: { requiredCaptures: 2, holdTurns: 4, minSurvivors: 6 },
  },
  {
    id: "m12-kumsong",
    name: "金城反击",
    kind: "breakthrough",
    date: "1953年7月13日21时—14日10时",
    location: "朝鲜金城以南轿岩山地区",
    historicalOutcome: "第67军第199师经一夜激战于14日午前攻占轿岩山主峰；金城战役其余正面与停战收束仅作背景。",
    historicalNote: "游戏只聚焦第67军第199师攻击韩军第6师轿岩山阵地的第一夜；东翼北汉江方向不压入同一战术棋盘。战役级装甲资料不下放为本切片的确定性坦克单位。",
    commanders: [
      pva("yang-yong", "杨勇", "第20兵团司令员", "中国人民志愿军第20兵团"),
      un("maxwell-taylor", "马克斯韦尔·泰勒", "第8集团军司令", "美国陆军第8集团军", undefined, "中将", "us-lieutenant-general"),
    ],
    brief: "在炮火准备后由北向南突破轿岩山三峰阵地：先撕开中、东峰结合部，再夺主峰。暴雨掩护接近也会拖慢机动；最后一关仍以保存主力为硬约束。",
    mapNote: "北在上；本图仅表现中央集团轿岩山切片。西峰主峰与中、东峰构成连续山体，南侧金城川是战役纵深线；北汉江位于画外东翼。",
    weather: { options: ["rain"], label: "盛夏暴雨", detail: "季风暴雨造成河水上涨、道路泥泞，远程火力效果下降。" },
    enemyDamageMultiplier: 1.05,
    playerEquipment: PVA_LATE,
    maxTurns: 23,
    map: [
      "FF^^^F........F^^^FF",
      "FF^^^F...==...F^^^FF",
      "FF^^^F...==...F^^^FF",
      "FF^F^^F..==..F^^F^FF",
      "FF^^^FF..==..FF^^^FF",
      "FF^F.^^B^^^^^^.F.^FF",
      "FF^..^^B===B^^^..^FF",
      "FF^F.^^B^^^^^^.F.^FF",
      "FF^^^FF..==..FF^^^FF",
      "FF^F^^F..==..F^^F^FF",
      "FF^~~~~~~==~~~~~~^FF",
      "FF^FF....==....FF^FF",
      "FF^FF....==....FF^FF",
      "FF^##F...==...F##^FF"
    ],
    playerSpawns: [{ x: 7, y: 1 }, { x: 8, y: 1 }, { x: 9, y: 1 }, { x: 10, y: 1 }, { x: 11, y: 1 }, { x: 8, y: 2 }, { x: 10, y: 2 }, { x: 12, y: 2 }],
    storyAllies: [
      { commander: "王兆才", type: "rifle", level: 4, weapon: "ppsh50", duty: "第199师轿岩山突击配属" },
      { commander: "唐章洪", type: "mortar", level: 4, weapon: "mortar82", equipment: "82毫米迫击炮", duty: "轿岩山炮火配属" },
    ],
    equipmentEra: "late" as const,
    weaponRewards: [],
    enemies: [
      { type: "rifle", x: 7, y: 7, name: "韩军第6师主峰守备连", equipment: "M1加兰德步枪", exp: 70, commanderId: "maxwell-taylor", title: "敌军主将", dropOptions: ["field_manual", "arty_support"] },
      { type: "rifle", x: 11, y: 6, name: "韩军第6师中东峰守备连", equipment: "M1加兰德步枪", exp: 70 },
      { type: "mg", x: 9, y: 6, name: "韩军地堡火力组", equipment: "勃朗宁M1919机枪", exp: 65 },
      { type: "artillery", x: 15, y: 11, name: "韩军纵深炮兵组", equipment: "M2A1 105毫米榴弹炮", exp: 60 },
      { type: "rifle", x: 10, y: 9, name: "韩军纵深警戒队", equipment: "M1加兰德步枪", exp: 40 },
    ],
    variantSlots: [],
    waves: [{ window: [5, 6], units: [{ type: "rifle", x: 10, y: 12, name: "韩军预备队", equipment: "M1加兰德步枪", exp: 65 }] }, { window: [9, 10], units: [{ type: "mg", x: 9, y: 12, name: "金城川机枪队", equipment: "勃朗宁M1919机枪", exp: 75 }, { type: "rifle", x: 11, y: 12, name: "韩军纵深反击队", equipment: "M1加兰德步枪", exp: 70 }] }],
    objectives: [
      { id: "kyoyam-east", name: "轿岩山中东峰", kind: "capture", x: 11, y: 6, owner: "enemy" },
      { id: "kyoyam-main", name: "轿岩山主峰", kind: "capture", x: 7, y: 7, owner: "enemy" },
    ],
    evacZone: [],
    itemDrops: [{ x: 6, y: 8, options: ["medkit", "arty_support"] }, { x: 13, y: 8, options: ["at_charge", "arty_support"] }],
    places: [
      { x: 7, y: 7, name: "轿岩山主峰" },
      { x: 11, y: 6, name: "轿岩山中东峰" },
      { x: 10, y: 10, name: "金城川" },
    ],
    scripted: [
      { kind: "barrage", turns: [1], damage: 8, target: "enemy", note: "志愿军开局炮火准备" },
      { kind: "barrage", turns: [7, 11], damage: 2, note: "联合国军拦阻炮火" },
      { kind: "supplyWindow", untilTurn: 9, penalty: 0.1, note: "金城反击弹药窗口" },
    ],
    victory: { requiredCaptures: 2, holdTurns: 1, minSurvivors: 2 },
  },
];
