import type { MissionConfig } from "./schema";

const PVA_EARLY = {
  artillery: "75毫米山炮",
  logistics: "辎重分队",
  rifle: "三八式／中正式步枪、手榴弹",
  mg: "捷克式ZB-26轻机枪",
  mortar: "31式60毫米迫击炮",
  tank: "缴获反坦克武器",
} as const;

const PVA_LATE = {
  artillery: "苏制榴弹炮／山炮",
  logistics: "汽车辎重队",
  rifle: "莫辛-纳甘步枪、50式冲锋枪",
  mg: "DP-28轻机枪／24式重机枪",
  mortar: "82毫米迫击炮",
  /** 默认不宣称局部坦克；仅 m11 等有直接史料处改用 PVA_LATE_ARMOR */
  tank: "反坦克火力与炮火支援",
} as const;

const PVA_LATE_ARMOR = {
  ...PVA_LATE,
  tank: "T-34-85装甲支援（独立坦克第4团局部配属）",
} as const;

const pva = (id: string, name: string, role: string, formation: string, portrait?: string) => ({
  id,
  name,
  faction: "player" as const,
  role,
  formation,
  portrait: portrait ?? id,
  historicalRank: "职务制（无军衔徽章）",
});

const un = (
  id: string,
  name: string,
  role: string,
  formation: string,
  portrait: string | undefined,
  historicalRank: string,
  rankInsignia?: string,
) => ({
  id,
  name,
  faction: "enemy" as const,
  role,
  formation,
  portrait: portrait ?? id,
  historicalRank,
  rankInsignia,
});

/**
 * 12关按时间顺序覆盖志愿军入朝、运动战、阵地战与停战前反击。
 * 棋盘是团/营级战术抽象，不宣称按比例复刻整场战役。
 */
export const HISTORICAL_MISSIONS: MissionConfig[] = [
  {
    id: "m1-onjong",
    name: "温井初战",
    kind: "breakthrough",
    date: "1950年10月25日",
    location: "朝鲜温井—北镇公路",
    historicalOutcome: "志愿军第40军在温井地区击破韩军先头部队，第一次战役由此展开。",
    historicalNote: "当面部队为韩国陆军第6师第2团第3营先头部队及炮兵中队；高大全为虚构指挥连接；随行班底与配属多为真实志愿军人物，敌军主将以精英单位上场。",
    commanders: [
      pva("wen-yucheng", "温玉成", "第40军军长", "中国人民志愿军第40军"),
      un("kim-jong-oh", "金钟五", "第6师师长", "韩国陆军第6步兵师", undefined, "准将", "rok-brigadier-general"),
    ],
    brief: "隐蔽进入两水洞两侧林缘，先占领公路西侧封锁点切断温井—北镇公路，再向南夺取温井。敌军会沿公路续进；高大全必须生还。",
    mapNote: "北在上；中央纵路是温井—北镇公路，两侧密林与高地夹出两水洞伏击走廊。西侧林缘是封锁点，温井在河南岸，九龙江限制迂回。",
    weather: { options: ["clear", "overcast"], label: "深秋寒夜", detail: "低温、天黑后能见度下降；长射程火力略受影响。" },
    playerEquipment: PVA_EARLY,
    // 物资精简后林缘伏击仍要可打；侧翼密林必须可走，避免主力被逼上公路秒死。
    enemyDamageMultiplier: 0.82,
    maxTurns: 17,
    map: [
      "^^^FF^^^F..F^^^FF^^^",
      "^^FF^^^^F==F^^^^FF^^",
      "^^F^^^^^F==F^^^^^F^^",
      "^^^^^F...==...F^^^^^",
      "^^^^F....==....F^^^^",
      "^^^F^^F..==..F^^F^^^",
      "^^^^F...=VV=...F^^^^",
      "^^^^^F...==...F^^^^^",
      "FFFF^^F..==..F^^FFFF",
      "FFFF..F..==..F..FFFF",
      "~~~~~~...==...~~~~~~",
      "FFFFF....==....FFFFF",
      "FFFFF...=VV=...FFFFF",
      "FFFFF....==....FFFFF",
    ],
    playerSpawns: [{ x: 4, y: 5 }, { x: 5, y: 5 }, { x: 14, y: 5 }, { x: 15, y: 5 }, { x: 4, y: 7 }, { x: 5, y: 7 }, { x: 14, y: 7 }, { x: 15, y: 7 }],
    storyAllies: [
      { commander: "王兆才", type: "rifle", level: 2, weapon: "type38", duty: "第40军第118师配属尖兵" },
      { commander: "刘维汉", type: "mg", level: 1, weapon: "zb26", duty: "第40军机枪配属分队" },
      { commander: "蒋庆泉", type: "rifle", level: 1, weapon: "type38", duty: "第118师温井方向配属" },
    ],
    equipmentEra: "early" as const,
    weaponRewards: ["zhongzheng", "type92_infantry_gun"],
    attachmentRewards: ["field_telephone"],
    enemies: [
      { type: "rifle", x: 9, y: 4, name: "韩6师2团3营前卫连", equipment: "M1加兰德步枪", exp: 55, commanderId: "kim-jong-oh", title: "敌军主将", dropOptions: ["medkit"] },
      { type: "rifle", x: 10, y: 7, name: "韩6师2团3营先遣连", equipment: "M1卡宾枪", exp: 48 },
      { type: "mg", x: 9, y: 6, name: "韩6师2团3营机枪排", equipment: "勃朗宁M1919机枪", exp: 60 },
      { type: "mortar", x: 11, y: 10, name: "韩6师2团配属炮兵中队", equipment: "M2 60毫米迫击炮", exp: 48 },
      { type: "rifle", x: 10, y: 9, name: "温井警戒排", equipment: "M1加兰德步枪", exp: 40 },
    ],
    variantSlots: [],
    waves: [
      { window: [6, 7], units: [{ type: "rifle", x: 10, y: 2, name: "韩军后续纵队", equipment: "M1加兰德步枪", exp: 40 }] },
    ],
    objectives: [
      { id: "ambush-line", name: "两水洞西侧封锁点", kind: "capture", x: 7, y: 6, owner: "enemy" },
      { id: "onjong", name: "温井", kind: "capture", x: 9, y: 12, owner: "enemy" },
    ],
    evacZone: [],
    itemDrops: [{ x: 6, y: 8, options: ["medkit", "bandage", "ration"] }, { x: 13, y: 8, options: ["medkit", "bandage", "ration"] }],
    places: [
      { id: "onjong", x: 9, y: 12, name: "温井", historicalContext: "温井是第一次战役初期的关键接触地域；本关把战斗收束到先头部队与公路节点。", tacticalHint: "伏击线得手后必须继续南下，不能把歼敌当成占领。" },
      { id: "liangshuidong", x: 7, y: 6, name: "两水洞西侧封锁点", historicalContext: "韩军第6师第2团先头第3营及炮兵中队沿公路进入峡谷地带；封锁点设在公路西侧路肩，机枪仍留在谷底公路上。", tacticalHint: "先占领路肩切断公路，再用两侧火力覆盖谷底纵队，不要把主力堆上公路。" },
      { id: "bukjin-axis", x: 10, y: 2, name: "北镇方向", historicalContext: "北侧公路代表敌军先头与后续部队进入温井地区的轴线。", tacticalHint: "不要把全部兵力压在谷底；保留一支部队监视北向增援。" },
    ],
    scripted: [
      { kind: "nightAssault", turns: [1, 3], attackBonus: 0.18, note: "黄昏夜袭：志愿军近战火力占优" },
    ],
    victory: { requiredCaptures: 2, holdTurns: 2, minSurvivors: 2 },
  },
  {
    id: "m2-unsan",
    name: "云山合围",
    kind: "breakthrough",
    date: "1950年11月1—3日",
    location: "朝鲜云山—城南公路桥",
    historicalOutcome: "志愿军第39军攻入云山并切断南撤通路，美骑兵第1师第8团遭受重创。",
    historicalNote: "美军与韩军正处于换防过程；关卡用两处据点表现云山城与城南撤退公路桥，未核实专名不进入任务。",
    commanders: [
      pva("wu-xinquan", "吴信泉", "第39军军长", "中国人民志愿军第39军", "wu-xinquan"),
      un("hobart-gay", "霍巴特·盖伊", "师长", "美国陆军骑兵第1师", undefined, "少将", "us-major-general"),
      un("paik-sun-yup", "白善烨", "师长", "韩国陆军第1步兵师", undefined, "准将（1950年11月）", "rok-brigadier-general"),
    ],
    brief: "趁美韩换防间隙从北、西北两翼压缩云山，夺取城区后向南封锁公路桥。美军后卫会沿唯一撤退轴接应，必须保留火力封住桥头。",
    mapNote: "北在上；云山城是河谷中的村镇团块，城南唯一公路桥跨过支流；西北山林是接近轴，南岸桥头有地堡。",
    weather: { options: ["clear", "overcast"], label: "寒冷夜战", detail: "入夜后气温下降，山谷间有薄雾。" },
    playerEquipment: PVA_EARLY,
    enemyDamageMultiplier: 0.82,
    // 取消“溃散后自动推进”后，夺取第二个据点需要显式行军；保留两回合机动窗口。
    maxTurns: 24,
    map: [
      "^^^^^FF........F^^^^",
      "^^^^FFF..==..F..F^^^",
      "^^^FF....==....F.^^^",
      "^^F.VVV...=...VVV.F^",
      "FFFVVVV..=V=..VVVFFF",
      "FFFFVV...==...VV.FFF",
      "^^^^^F...==...F^^^^^",
      "FFFF.....==.....FFFF",
      "~~~~~~~~~==~~~~~~~~~",
      "FFFFF^^.B==B.^^FFFFF",
      "FFFF..F..===..F.FFFF",
      "^^^^^....==....^^^^^",
      "^^^^^....==....^^^^^",
      "^^^^^F...==...F^^^^^"
    ],
    playerSpawns: [{ x: 4, y: 2 }, { x: 5, y: 3 }, { x: 7, y: 2 }, { x: 3, y: 4 }, { x: 4, y: 5 }, { x: 6, y: 4 }, { x: 8, y: 3 }, { x: 9, y: 4 }],
    storyAllies: [
      { commander: "曹辉章", type: "rifle", level: 2, weapon: "zhongzheng", attachment: "field_telephone", duty: "第39军云山方向配属步兵" },
      { commander: "张明禄", type: "mortar", level: 2, weapon: "mortar60", duty: "第39军迫击炮配属" },
    ],
    equipmentEra: "early" as const,
    weaponRewards: ["zb26"],
    attachmentRewards: ["ammo_carrier"],
    enemies: [
      { type: "rifle", x: 10, y: 4, name: "美骑8团步兵", equipment: "M1加兰德步枪", exp: 55, commanderId: "hobart-gay", title: "敌军主将", dropOptions: ["field_manual", "at_charge"], dropWeapons: ["bar_m1918a2"] },
      { type: "rifle", x: 12, y: 6, name: "韩军换防部队", equipment: "M1卡宾枪", exp: 48 },
      { type: "mg", x: 9, y: 4, name: "美骑8团火力排", equipment: "勃朗宁M1919机枪", exp: 58 },
      { type: "mg", x: 11, y: 10, name: "桥头机枪班", equipment: "勃朗宁M1919机枪", exp: 45 },
      { type: "mortar", x: 13, y: 7, name: "城南迫击炮组", equipment: "M1型81毫米迫击炮", exp: 42 },
      { type: "artillery", x: 14, y: 12, name: "城南师属炮兵", equipment: "M2A1 105毫米榴弹炮", exp: 50 },
    ],
    variantSlots: [],
    waves: [
      { window: [4, 5], units: [
        { type: "rifle", x: 10, y: 12, name: "美骑5团接应队", equipment: "M1加兰德步枪", exp: 42 },
        { type: "mg", x: 12, y: 11, name: "桥头增援机枪", equipment: "勃朗宁M1919机枪", exp: 40 },
      ] },
    ],
    objectives: [
      { id: "unsan-town", name: "云山城", kind: "capture", x: 10, y: 4, owner: "enemy" },
      { id: "south-road-bridge", name: "城南公路桥", kind: "capture", x: 10, y: 10, owner: "enemy" },
    ],
    evacZone: [],
    itemDrops: [{ x: 5, y: 8, options: ["medkit", "at_charge"] }, { x: 14, y: 8, options: ["at_charge"] }],
    places: [
      { id: "unsan-town", x: 10, y: 4, name: "云山城", historicalContext: "云山战斗发生在美韩换防与接触混乱中，城区是北侧防御与交通的核心。", tacticalHint: "先压缩城区守军，再让步兵占领；远程火力留给桥头反扑。" },
      { id: "unsan-south-bridge", x: 10, y: 10, name: "城南公路桥", historicalContext: "城南道路是守军向南撤出、增援向北接应的共同交通轴。", tacticalHint: "切断桥头比平均消耗敌军更重要；用机枪或迫击炮覆盖道路。" },
      { id: "chongchon-tributary", x: 4, y: 8, name: "清川支流", historicalContext: "河流与道路共同限定云山地区的机动方向，关卡只表达相对地理关系。", tacticalHint: "河流会把机动压向桥梁；提前控制出口可形成围堵。" },
    ],
    supplyPoints: [{ x: 5, y: 5 }, { x: 14, y: 9 }],
    scripted: [
      { kind: "nightAssault", turns: [1, 4], attackBonus: 0.2, note: "夜袭换防间隙：近战加成" },
      { kind: "supplyWindow", untilTurn: 8, penalty: 0.1, note: "合围后弹药见底" },
    ],
    victory: { requiredCaptures: 2, holdTurns: 1, minSurvivors: 2 },
  },
  {
    id: "m3-chongchon",
    name: "清川江穿插",
    kind: "breakthrough",
    date: "1950年11月25日—12月2日",
    location: "朝鲜德川—三所里—龙源里",
    historicalOutcome: "志愿军第二次战役西线突破韩军防线并向三所里穿插，迫使美第8集团军全面后撤。",
    historicalNote: "关卡聚焦第38军第113师向敌后公路穿插的战术片段（约14小时/145华里为战史叙事）；不表现整条清川江渡河战线。",
    commanders: [
      pva("liang-xingchu", "梁兴初", "第38军军长", "中国人民志愿军第38军（含第113师穿插）"),
      un("walton-walker", "沃尔顿·沃克", "第8集团军司令", "美国陆军第8集团军", undefined, "中将", "us-lieutenant-general"),
    ],
    brief: "沿山脊绕开正面火力，抢占三所里与龙源里两个公路节点，截断南撤车队。时间比歼敌更重要，过度恋战会错过窗口。",
    mapNote: "北在上；清川江横在北缘，三所里与龙源里同在一条东西向南撤公路上；志愿军从南山脊穿插，没有贯穿南北的中央大道。",
    weather: { options: ["snow", "overcast"], label: "初雪与冻土", detail: "寒潮到来，山路结冰，部队移动与远射均受影响。" },
    playerEquipment: PVA_EARLY,
    enemyDamageMultiplier: 0.66,
    maxTurns: 17,
    map: [
      "~~~~~~~~~~~~~~~~~~~~",
      "~~~~.....==.....~~~~",
      "~~~~............~~~~",
      "^^^^F..........F^^^^",
      "^^^^^..........^^^^^",
      "=====V========V=====",
      "^^^^^..........^^^^^",
      "^^^^F..........F^^^^",
      "FFFF.=........=.FFFF",
      "^^^^.=........=.^^^^",
      "FFFF.=........=.FFFF",
      "^^^^^=........=.^^^^",
      "^^^^^=........=.^^^^",
      "^^^^^^........^^^^^^"
    ],
    playerSpawns: [{ x: 8, y: 12 }, { x: 9, y: 12 }, { x: 10, y: 12 }, { x: 11, y: 12 }, { x: 7, y: 11 }, { x: 9, y: 11 }, { x: 10, y: 11 }, { x: 12, y: 11 }],
    storyAllies: [
      { commander: "杨育才", type: "rifle", level: 2, weapon: "zhongzheng", duty: "第38军穿插配属尖兵" },
      { commander: "周厚刚", type: "mortar", level: 2, weapon: "mortar60", duty: "第38军迫击炮配属" },
      { commander: "倪恩德", type: "rifle", level: 1, weapon: "type38", duty: "第113师穿插配属" },
    ],
    equipmentEra: "early" as const,
    weaponRewards: ["mortar60"],
    attachmentRewards: ["camouflage_net"],
    enemies: [
      { type: "rifle", x: 5, y: 5, name: "美2师后卫", equipment: "M1加兰德步枪", exp: 85 },
      { type: "rifle", x: 14, y: 5, name: "韩军警戒营", equipment: "M1卡宾枪", exp: 45, title: "精锐指挥官", dropOptions: ["field_manual", "smoke_grenade"], dropWeapons: ["m2hb"] },
      { type: "mg", x: 10, y: 5, name: "公路护卫火力组", equipment: "勃朗宁M1919机枪", exp: 95 },
      { type: "mortar", x: 12, y: 2, name: "美军迫击炮组", equipment: "M1型81毫米迫击炮", exp: 55 },
      { type: "rifle", x: 10, y: 4, name: "军隅里后卫", equipment: "M1加兰德步枪", exp: 50 },
    
    ],
    variantSlots: [],
    waves: [{ window: [3, 4], units: [{ type: "rifle", x: 10, y: 1, name: "南撤公路纵队", equipment: "M1加兰德步枪", exp: 80 }] }],
    objectives: [
      { id: "samsori", name: "三所里", kind: "capture", x: 5, y: 5, owner: "enemy" },
      { id: "yongwon", name: "龙源里", kind: "capture", x: 14, y: 5, owner: "enemy" },
    ],
    evacZone: [],
    itemDrops: [{ x: 4, y: 8, options: ["medkit", "bandage", "smoke_grenade"] }, { x: 15, y: 8, options: ["smoke_grenade"] }],
    places: [
      { id: "samsori", x: 5, y: 5, name: "三所里", historicalContext: "三所里是第38军第113师急行穿插所争夺的敌后公路节点之一。", tacticalHint: "时间优先于歼敌；从山地绕过正面火力后快速占点。" },
      { id: "yongwon", x: 14, y: 5, name: "龙源里", historicalContext: "龙源里与三所里共同构成对南撤道路的截断，本关把两点压缩在同一张战术地图。", tacticalHint: "两翼同时推进，避免占领一端后再横穿整张地图。" },
      { id: "chongchon-front", x: 5, y: 1, name: "清川江战线", historicalContext: "清川江代表更大的战役背景，并不是本关必须占领的单一据点。", tacticalHint: "不要被北缘敌军牵走主力；任务是穿插到道路节点。" },
    ],
    scripted: [
      { kind: "nightAssault", turns: [1, 3], attackBonus: 0.15, note: "穿插夜战：近战加成" },
      { kind: "supplyWindow", untilTurn: 6, penalty: 0.16, note: "携行弹药见底：攻击衰减" },
    ],
    victory: { requiredCaptures: 2, holdTurns: 3, minSurvivors: 2 },
  },
  {
    id: "m4-chosin",
    name: "长津湖断路",
    kind: "withdraw",
    date: "1950年11月27日—12月3日",
    location: "朝鲜长津湖柳潭里—下碣隅里公路",
    historicalOutcome: "志愿军第9兵团围攻美第10军部队；美陆战1师经下碣隅里向兴南有组织撤出，双方均伤亡惨重。",
    historicalNote: "Fox连始终守住死鹰岭通路；本关只抽象志愿军第59师方向在主补给路附近设置的临时路障，结束点是接到脱离命令，不宣称最终控制Toktong Pass。",
    commanders: [
      pva("song-shilun", "宋时轮", "第9兵团司令员", "中国人民志愿军第9兵团", "song-shilun"),
      pva("yang-gensi", "杨根思", "第20军第58师第172团第3连连长", "中国人民志愿军第20军第58师", "yang-gensi"),
      un("oliver-smith", "奥利弗·史密斯", "师长", "美国海军陆战队第1师", "oliver-smith", "少将", "us-major-general"),
      un("edward-almond", "爱德华·阿尔蒙德", "第10军军长", "美国陆军第10军", undefined, "少将（1950年11月）", "us-major-general"),
    ],
    brief: "在极寒中依托主补给路北、南两段临时路障，反复迟滞由柳潭里向下碣隅里收缩的陆战队纵队。敌军会从公路两端夹击清障；坚持到脱离命令下达并保存高大全。",
    mapNote: "北在上；道路由西北柳潭里斜向东南下碣隅里，长津湖占据东侧。两处目标是主补给路沿线临时路障；Fox连控制的死鹰岭高地仍属美军通路防御体系。",
    weather: { options: ["snow"], label: "极寒暴雪", detail: "约零下二三十摄氏度的严寒；积雪降低移动力与远程火力。" },
    enemyDamageMultiplier: 1.18,
    playerEquipment: PVA_EARLY,
    maxTurns: 22,
    map: [
      "FFFF^^....~~~~~~~~~~",
      "FFFF^^=...~~~~~~~~~~",
      "FFFF^^=...~~~~~~~~~~",
      "FFFFF^==..~~~~~~~~~~",
      "FFFF^^.==.~~~~~~~~~~",
      "^^^^^F..==..~~~~~~~~",
      "FFFF^^..B=..~~~~~~~~",
      "FFFFF^^..=B..~~~~~~~",
      "^^^^^FF...==..~~~~~~",
      "FFFF^^FF...==..~~~~~",
      "FFFFF^^FF...==..~~~~",
      "FFFF^^FFF....==..~~~",
      "FFFF^^FFF....==.....",
      "FFFF^^FFF....==....."
    ],
    playerSpawns: [{ x: 5, y: 6 }, { x: 6, y: 6 }, { x: 7, y: 6 }, { x: 11, y: 7 }, { x: 12, y: 7 }, { x: 6, y: 7 }, { x: 7, y: 7 }, { x: 12, y: 8 }],
    storyAllies: [
      { commander: "杨根思", type: "rifle", level: 2, weapon: "zhongzheng", portrait: "yang-gensi", duty: "第20军58师172团3连连长" },
      { commander: "李玉安", type: "mg", level: 2, weapon: "zb26", duty: "冰雕连火力骨干" },
      { commander: "陈德忠", type: "logistics", level: 2, weapon: "supply_cart", duty: "第9兵团极寒辎重配属" },
    ],
    equipmentEra: "early" as const,
    weaponRewards: ["mosin"],
    attachmentRewards: ["winter_kit", "medic_team"],
    enemies: [
      { type: "rifle", x: 6, y: 1, name: "陆战5团先头分队", equipment: "M1加兰德步枪", exp: 75 },
      { type: "rifle", x: 15, y: 12, name: "下碣隅里接应队", equipment: "M1加兰德步枪", exp: 75 },
      { type: "mg", x: 7, y: 3, name: "陆战7团2营F连通路警戒", equipment: "BAR／勃朗宁M1919机枪", exp: 60, commanderId: "oliver-smith", title: "敌军主将", dropOptions: ["medkit", "compressed_ration"] },
      { type: "rifle", x: 8, y: 8, name: "公路搜索班", equipment: "M1卡宾枪", exp: 30 },
    ],
    variantSlots: [],
    waves: [
      { window: [6, 7], units: [{ type: "rifle", x: 6, y: 1, name: "柳潭里撤退纵队", equipment: "M1加兰德步枪", exp: 55 }, { type: "mg", x: 7, y: 3, name: "纵队火力", equipment: "勃朗宁M1919机枪", exp: 45 }] },
      { window: [10, 11], units: [{ type: "rifle", x: 15, y: 12, name: "下碣隅里清障分队", equipment: "M1加兰德步枪", exp: 45 }] },
    ],
    objectives: [
      { id: "msr-north-roadblock", name: "MSR北段临时路障", kind: "hold", x: 8, y: 6, owner: "player" },
      { id: "msr-south-roadblock", name: "MSR南段临时路障", kind: "hold", x: 11, y: 7, owner: "player" },
    ],
    evacZone: [
      { x: 2, y: 3 }, { x: 2, y: 4 }, { x: 2, y: 5 }, { x: 2, y: 6 }, { x: 2, y: 7 }, { x: 2, y: 8 },
      { x: 3, y: 3 }, { x: 3, y: 4 }, { x: 3, y: 5 }, { x: 3, y: 6 }, { x: 3, y: 7 },
      { x: 4, y: 5 }, { x: 4, y: 6 }, { x: 5, y: 5 }, { x: 5, y: 6 },
    ],
    itemDrops: [{ x: 5, y: 9, options: ["compressed_ration", "satchel", "water_purification"] }, { x: 13, y: 9, options: ["satchel"] }],
    places: [
      { id: "fox-hill", x: 7, y: 3, name: "Fox连防御高地", historicalContext: "Fox连守住死鹰岭通路；本关不把这处高地误写成志愿军最终控制目标。", tacticalHint: "这里是敌军火力支撑点，绕行或压制比正面久攻更稳妥。" },
      { id: "yudam-axis", x: 6, y: 1, name: "柳潭里方向", historicalContext: "陆战队纵队由柳潭里方向沿主补给路向南收缩。", tacticalHint: "北段路障只能迟滞，预留脱离路线，避免被后续纵队缠住。" },
      { id: "hagaru-axis", x: 15, y: 12, name: "下碣隅里方向", historicalContext: "下碣隅里是撤退纵队的收拢与接应方向。", tacticalHint: "南侧清障分队会反向夹击；不要让后勤留在公路中心。" },
      { id: "chosin-reservoir", x: 16, y: 4, name: "长津湖", historicalContext: "湖区、山路与极寒共同限制机动；棋盘只表达道路与湖岸的相对关系。", tacticalHint: "雪地高地代价很高，沿道路机动快，但更容易遭受夹击。" },
    ],
    supplyPoints: [{ x: 5, y: 7 }, { x: 12, y: 8 }],
    scripted: [
      { kind: "coldAttrition", fromTurn: 4, damage: 1, note: "极寒冻伤：双方持续减员" },
    ],
    // 须击溃 2 个外围单位再撤离；撤离通道第 8 回合开放，挡住增援前秒撤
    victory: {
      minEvacuated: 2,
      evacuateRatio: 0.25,
      requireKeyUnit: true,
      minEnemiesRouted: 2,
      evacOpensOnTurn: 7,
    },
  },
  {
    id: "m5-third-offensive",
    name: "突破三八线",
    kind: "breakthrough",
    date: "1950年12月31日—1951年1月8日",
    location: "朝鲜临津江—议政府方向",
    historicalOutcome: "志愿军与朝鲜人民军突破三八线防御，联合国军撤出汉城。",
    historicalNote: "关卡表现第三次战役西线的一段渡河与山口突破。",
    commanders: [
      pva("peng-dehuai", "彭德怀", "司令员兼政治委员", "中国人民志愿军", "peng-dehuai"),
      pva("hong-xuezhi", "洪学智", "副司令员兼后方勤务司令", "中国人民志愿军后方勤务司令部", "hong-xuezhi"),
      un("matthew-ridgway", "马修·李奇微", "第8集团军司令", "美国陆军第8集团军", "matthew-ridgway", "中将", "us-lieutenant-general"),
    ],
    brief: "从北岸夜渡临津江，先夺取渡河带，再沿狭窄走廊向南突破议政府北侧山口。守军正向纵深收缩，必须在其完成部署前连续占领两个节点。",
    mapNote: "北在上；临津江以宽河面横贯北部，只有两处徒涉口；南面是议政府北侧山口，没有贯穿全图的中央公路。",
    weather: { options: ["snow", "clear"], label: "隆冬冻江", detail: "河面部分冻结，夜间严寒，部队体力消耗明显。" },
    enemyDamageMultiplier: 0.79,
    playerEquipment: PVA_EARLY,
    maxTurns: 19,
    map: [
      "....^^..........^^..",
      "....^^..........^^..",
      "....^^..........^^..",
      "...~~~~==~~==~~~~...",
      "...~~~~==~~==~~~~...",
      "...~~~~==~~==~~~~...",
      "....^^..==..==..^^..",
      "....^^....==....^^..",
      "....^^^^..==..^^^^..",
      "....^^^^..==V^^.^^^^",
      "....^^^^....^^^^....",
      "....^^^^....^^^^....",
      "....^^^^....^^^^....",
      "....^^^^....^^^^...."
    ],
    playerSpawns: [{ x: 7, y: 1 }, { x: 8, y: 1 }, { x: 9, y: 1 }, { x: 10, y: 1 }, { x: 11, y: 1 }, { x: 8, y: 2 }, { x: 10, y: 2 }, { x: 12, y: 2 }],
    storyAllies: [
      { commander: "高玉宝", type: "rifle", level: 3, weapon: "mosin", duty: "第三次战役渡河配属步兵" },
      { commander: "孙生禄", type: "mg", level: 2, weapon: "dp28", duty: "临津江方向火力配属" },
    ],
    equipmentEra: "late" as const,
    weaponRewards: ["dp28"],
    attachmentRewards: ["motor_transport"],
    enemies: [
      { type: "rifle", x: 8, y: 4, name: "联合国军江岸前哨", equipment: "M1加兰德步枪", exp: 62 },
      { type: "rifle", x: 12, y: 9, name: "韩军山口守备队", equipment: "M1卡宾枪", exp: 48 },
      { type: "mg", x: 11, y: 4, name: "渡口机枪阵地", equipment: "勃朗宁M1919机枪", exp: 70, title: "精锐指挥官", dropOptions: ["at_charge", "field_manual"] },
      { type: "mortar", x: 13, y: 7, name: "山口迫击炮组", equipment: "M1型81毫米迫击炮", exp: 55 },
      { type: "artillery", x: 14, y: 12, name: "纵深炮兵阵地", equipment: "M2A1 105毫米榴弹炮", exp: 55 },
      { type: "rifle", x: 9, y: 7, name: "走廊后卫", equipment: "M1加兰德步枪", exp: 50 },
    ],
    variantSlots: [],
    waves: [{ window: [6, 7], units: [{ type: "rifle", x: 10, y: 12, name: "议政府公路后卫", equipment: "M1加兰德步枪", exp: 50 }] }],
    objectives: [
      { id: "imjin-crossing", name: "临津江渡河带", kind: "capture", x: 8, y: 4, owner: "enemy" },
      { id: "uigongbu-pass", name: "议政府北侧山口", kind: "capture", x: 12, y: 9, owner: "enemy" },
    ],
    evacZone: [],
    itemDrops: [{ x: 6, y: 7, options: ["ammo_crate", "bandage"] }, { x: 13, y: 7, options: ["ammo_crate"] }],
    places: [
      { id: "imjin-crossing", x: 8, y: 4, name: "临津江", historicalContext: "第三次战役西线由临津江方向突破，关卡以一处渡河带表现夜间渡江。", tacticalHint: "先用近战夜袭压制渡口，再把远程单位送过河。" },
      { id: "uigongbu-pass", x: 12, y: 9, name: "议政府北侧山口", historicalContext: "山口代表突破后向议政府方向发展的纵深节点，而非把整场战役压缩为攻占汉城。", tacticalHint: "渡河后不要停在开阔走廊；用两翼高地掩护步兵占点。" },
      { id: "uigongbu-axis", x: 10, y: 12, name: "议政府方向", historicalContext: "南向道路连接后续战役发展方向，只作为地图边界与历史坐标。", tacticalHint: "纵深炮兵会覆盖道路，分散队形后再接近终点。" },
    ],
    scripted: [
      { kind: "nightAssault", turns: [1, 3], attackBonus: 0.12, note: "三八线夜袭" },
      { kind: "supplyWindow", untilTurn: 7, penalty: 0.14, note: "礼拜攻势：弹药见底" },
    ],
    // 新版包围与控制区规则会放大前沿压力；保留连续坚守，要求夺点后再顶住四回合。
    victory: { requiredCaptures: 2, holdTurns: 4, minSurvivors: 2 },
  },
  {
    id: "m6-hoengsong",
    name: "横城反击",
    kind: "breakthrough",
    date: "1951年2月11—13日",
    location: "韩国横城北部山地",
    historicalOutcome: "志愿军对韩军第8师方向实施反击，联合国军中部战线被迫后撤。",
    historicalNote: "游戏聚焦雪夜穿插和切断横城公路，不把砥平里防御战合并进本关。",
    commanders: [
      pva("wen-yucheng", "温玉成", "第40军军长", "中国人民志愿军第40军"),
      un("edward-almond", "爱德华·阿尔蒙德", "第10军军长", "美国陆军第10军", undefined, "少将（1951年2月）", "us-major-general"),
    ],
    brief: "在雪夜从突出部两翼越过山脊，先切断横城北侧公路节点，再夺南撤公路口。敌军火力强但部署拉长，合围割路比正面硬攻有效。",
    mapNote: "北在上；西侧山脊与峭壁是穿插轴，东侧相对开阔；南缘东西向公路通向横城—原州，没有贯穿南北的中央大道。",
    weather: { options: ["snow", "fog"], label: "雪夜低云", detail: "积雪与低云降低双方机动和远程观察。" },
    playerEquipment: PVA_EARLY,
    enemyDamageMultiplier: 1.1,
    maxTurns: 18,
    map: [
      "^^^^^............^^^",
      "^^^^#F..........F^^^",
      "^^^##F..........^^^^",
      "^^###F..........F^^^",
      "^^#F^^..........^^^^",
      "^^#F^^..........F^^^",
      "^^^^#F...=V=....^^^^",
      "^^^##F..........F^^^",
      "^^###F..........^^^^",
      "^####^^.........F^^^",
      "=======V===......FFF",
      "^^^^^F...........^^^",
      "^^^^^F...........^^^",
      "^^^^#F...........#^^"
    ],
    playerSpawns: [{ x: 6, y: 2 }, { x: 7, y: 3 }, { x: 9, y: 2 }, { x: 12, y: 2 }, { x: 13, y: 3 }, { x: 3, y: 5 }, { x: 16, y: 5 }, { x: 15, y: 6 }],
    storyAllies: [
      { commander: "张桃芳", type: "rifle", level: 3, weapon: "mosin", duty: "横城方向狙击与尖兵配属" },
      { commander: "周厚刚", type: "mortar", level: 3, weapon: "mortar82", duty: "第40军迫击炮配属" },
    ],
    equipmentEra: "late" as const,
    weaponRewards: ["ppsh50", "mortar120"],
    attachmentRewards: ["artillery_tractor"],
    enemies: [
      { type: "rifle", x: 10, y: 6, name: "韩军第8师步兵", equipment: "M1加兰德步枪", exp: 50, commanderId: "edward-almond", title: "敌军主将", dropOptions: ["field_manual", "grenade_bundle"] },
      { type: "rifle", x: 7, y: 10, name: "美军交通警戒队", equipment: "M1卡宾枪", exp: 55 },
      { type: "mg", x: 9, y: 6, name: "突出部公路火力点", equipment: "勃朗宁M1919机枪", exp: 60 },
      { type: "mortar", x: 13, y: 8, name: "美军迫击炮组", equipment: "M1型81毫米迫击炮", exp: 55 },
    
    ],
    variantSlots: [],
    waves: [{ window: [9, 10], units: [{ type: "rifle", x: 10, y: 12, name: "横城后卫", equipment: "M1加兰德步枪", exp: 35 }] }],
    objectives: [
      { id: "hoengsong-north", name: "横城北侧公路节点", kind: "capture", x: 10, y: 6, owner: "enemy" },
      { id: "wonju-road", name: "横城—原州南撤公路口", kind: "capture", x: 7, y: 10, owner: "enemy" },
    ],
    evacZone: [],
    itemDrops: [{ x: 6, y: 8, options: ["grenade_bundle", "ration"] }, { x: 13, y: 8, options: ["grenade_bundle"] }],
    places: [
      { id: "hoengsong-north-road", x: 10, y: 6, name: "横城北侧公路节点", historicalContext: "横城反击中，雪夜突破与切断撤退轴比正面逐点消耗更关键。", tacticalHint: "从两翼山路接近，在公路节点两侧形成对向控制。" },
      { id: "wonju-axis", x: 7, y: 10, name: "原州方向", historicalContext: "东南道路代表联合国军向原州方向后撤和重新组织防线的轴线。", tacticalHint: "道路出口是天然瓶颈；先封出口，再处理被隔开的火力点。" },
    ],
    scripted: [
      { kind: "nightAssault", turns: [1, 3], attackBonus: 0.14, note: "横城夜袭" },
    ],
    victory: { requiredCaptures: 2, holdTurns: 3, minSurvivors: 2 },
  },
  {
    id: "m7-chipyongni",
    name: "砥平里外线",
    kind: "withdraw",
    date: "1951年2月13—15日",
    location: "韩国砥平里环形阵地外围",
    historicalOutcome: "美23团战斗队与法军营守住砥平里，增援装甲纵队打通通路；志愿军停止进攻并撤出。",
    historicalNote: "本关不允许玩家虚构攻占砥平里；目标是夜间牵制后在白昼空中火力到来前脱离。",
    commanders: [
      pva("wu-xinquan", "吴信泉", "第39军军长", "中国人民志愿军第39军"),
      un("paul-freeman", "保罗·弗里曼", "第23团团长", "美国陆军第2师第23步兵团", undefined, "上校", "us-colonel"),
      un("ralph-monclar", "拉尔夫·蒙克拉尔", "法军营营长", "法国联合国营", undefined, "临时中校", "fr-lieutenant-colonel"),
    ],
    brief: "砥平里守军已构成环形阵地。先击溃至少一个外围火力点完成牵制，再让高大全和至少三分之二的分队从北侧山路撤出。不要攻入核心村镇同炮兵与装甲纵队消耗。",
    mapNote: "村镇与连续堡垒环代表砥平里防御圈；北侧整行是脱离地域，南侧道路是克伦贝装甲特遣队解围方向。",
    weather: { options: ["snow", "overcast"], label: "残雪与低云", detail: "夜间寒冷，天亮后能见度逐步改善。" },
    playerEquipment: PVA_EARLY,
    enemyDamageMultiplier: 0.89,
    maxTurns: 18,
    map: [
      "FF................FF",
      "FF==========^=====FF",
      "FF================FF",
      "FF^^=F....==....F=^^",
      "FF....^^^BBBB^^^....",
      "FF...^^BB....BB^^...",
      "FF..^^BBB.VV.BBB^^..",
      "FF...^^BB....BB^^...",
      "FF....^^^BBBB^^^....",
      "FFFFF^^^..==..^^^FFF",
      "FFFF......==......FF",
      "FF^^F.....==.....F^^",
      "FF^^F.....==.....F^^",
      "FF^^FF....==....FF^^"
    ],
    playerSpawns: [{ x: 3, y: 5 }, { x: 4, y: 6 }, { x: 5, y: 6 }, { x: 14, y: 6 }, { x: 15, y: 6 }, { x: 16, y: 5 }, { x: 4, y: 4 }, { x: 15, y: 4 }],
    storyAllies: [
      { commander: "王兆才", type: "rifle", level: 3, weapon: "mosin", duty: "砥平里外线牵制配属" },
      { commander: "刘维汉", type: "mg", level: 3, weapon: "dp28", duty: "外线掩护火力配属" },
    ],
    equipmentEra: "late" as const,
    weaponRewards: ["bazooka"],
    attachmentRewards: ["scr300_radio"],
    enemies: [
      { type: "mg", x: 7, y: 7, name: "美23团西侧火力点", equipment: "勃朗宁M1919机枪", exp: 110 },
      { type: "mg", x: 12, y: 7, name: "法军营东侧火力点", equipment: "MAC 24/29轻机枪", exp: 110 },
      { type: "rifle", x: 10, y: 6, name: "美23团核心步兵", equipment: "M1加兰德步枪", exp: 83, commanderId: "paul-freeman", title: "敌军主将", dropOptions: ["field_manual", "medkit"], dropWeapons: ["m2_4_2_mortar"] },
    ],
    variantSlots: [],
    waves: [{ window: [8, 9], units: [
      { type: "tank", x: 9, y: 12, name: "克伦贝装甲纵队", equipment: "M4A3E8谢尔曼坦克", exp: 69 },
      { type: "rifle", x: 10, y: 12, name: "美骑5团增援", equipment: "M1加兰德步枪", exp: 69 },
    ] }],
    objectives: [],
    evacZone: Array.from({ length: 20 }, (_, x) => ({ x, y: 0 })),
    itemDrops: [{ x: 7, y: 9, options: ["signal_flare", "medkit"] }, { x: 12, y: 9, options: ["medkit", "signal_flare"] }],
    places: [
      { id: "chipyongni", x: 10, y: 6, name: "砥平里", historicalContext: "砥平里是道路枢纽，守军依托周围丘陵形成环形阵地并获得炮兵、空中与后续装甲支援。", tacticalHint: "本关不要求占领城镇；只需外线牵制后及时脱离。" },
      { id: "chipyongni-withdrawal", x: 10, y: 1, name: "北撤通道", historicalContext: "志愿军在攻击受挫、补给压力增加后脱离接触；关卡把保存部队写进胜利条件。", tacticalHint: "达到最低交战要求后分批北撤，利用控制区拖慢追兵。" },
    ],
    scripted: [
      { kind: "barrage", turns: [4, 7], damage: 4, note: "联合国军炮兵与空中支援压制" },
      { kind: "supplyWindow", untilTurn: 7, penalty: 0.14, note: "外线弹药耗尽" },
    ],
    victory: {
      minEvacuated: 4,
      evacuateRatio: 0.5,
      requireKeyUnit: true,
      minEnemiesRouted: 1,
      evacOpensOnTurn: 6,
    },
  },
  {
    id: "m8-imjin",
    name: "临津江渡河",
    kind: "breakthrough",
    date: "1951年4月22—25日",
    location: "韩国临津江—雪马里—235高地",
    historicalOutcome: "志愿军第63军渡过临津江并包围英军格洛斯特营；英29旅迟滞了攻势后南撤。",
    historicalNote: "关卡目标限定为建立桥头堡和夺取235高地，不把整个春季攻势简化为单场胜负。",
    commanders: [
      pva("fu-chongbi", "傅崇碧", "第63军军长", "中国人民志愿军第63军"),
      un("james-carne", "詹姆斯·卡恩", "营长", "英军格洛斯特郡团第1营", undefined, "中校", "uk-lieutenant-colonel"),
    ],
    brief: "从北岸夜渡临津江，夺取南岸桥头后沿雪马里谷地分割英军，最后攻上235高地。三个地段是连续纵深，不要在渡口与高地同时分兵硬冲。",
    mapNote: "北在上；三段纵深分开：北岸与宽河、中央雪马里谷地、南端 235 高地山体。没有一条贯穿全图的中央公路。",
    weather: { options: ["clear", "fog"], label: "春夜薄雾", detail: "夜间河谷能见度有限，白天气象适合联合国军空中支援。" },
    enemyDamageMultiplier: 0.88,
    playerEquipment: PVA_LATE,
    maxTurns: 17,
    map: [
      "....^^..........^^..",
      "....^^..........^^..",
      "....^^..........^^..",
      "..~~~~~~~~==~~~~~~..",
      "..~~~~~~~~==~~~~~~..",
      "..~~~~~..=B=~~~~~~..",
      "....^^....==....^^..",
      "....^^...=V=...^^...",
      "....^^....==....^^..",
      "....^^^^..==.^^.^^..",
      "...^^^^^^.==.^^^^^^.",
      "...^^^^^B==B^^^^^...",
      "...^^^^^^^^^^^^^....",
      "...^^^^^^^^^^^^^...."
    ],
    playerSpawns: [{ x: 7, y: 1 }, { x: 8, y: 1 }, { x: 9, y: 1 }, { x: 10, y: 1 }, { x: 11, y: 1 }, { x: 8, y: 2 }, { x: 10, y: 2 }, { x: 12, y: 2 }],
    storyAllies: [
      { commander: "杨育才", type: "rifle", level: 3, weapon: "ppsh50", duty: "第63军渡河尖兵配属" },
      { commander: "孙生禄", type: "mg", level: 3, weapon: "dp28", duty: "雪马里方向火力配属" },
      { commander: "陈德忠", type: "logistics", level: 2, weapon: "supply_cart", duty: "渡河辎重配属" },
    ],
    equipmentEra: "late" as const,
    weaponRewards: ["mortar82"],
    attachmentRewards: ["rangefinder"],
    enemies: [
      { type: "rifle", x: 10, y: 5, name: "临津江南岸前哨", equipment: "李-恩菲尔德No.4步枪", exp: 75 },
      { type: "rifle", x: 10, y: 11, name: "格洛斯特营235高地守军", equipment: "李-恩菲尔德No.4步枪", exp: 72, commanderId: "james-carne", title: "敌军主将", dropOptions: ["field_manual", "bandage"], dropWeapons: ["qf25"] },
      { type: "mg", x: 9, y: 7, name: "雪马里布伦机枪组", equipment: "布伦轻机枪／维克斯机枪", exp: 80 },
      { type: "artillery", x: 14, y: 12, name: "英军师属炮兵", equipment: "M2A1 105毫米榴弹炮", exp: 65 },
      { type: "rifle", x: 12, y: 9, name: "英军后备步兵", equipment: "李-恩菲尔德No.4步枪", exp: 55 },
    ],
    variantSlots: [],
    waves: [{ window: [8, 9], units: [{ type: "tank", x: 10, y: 12, name: "第8骠骑兵支援", equipment: "百夫长Mk.3坦克", exp: 70 }] }],
    objectives: [
      { id: "imjin-bridgehead", name: "临津江南岸桥头", kind: "capture", x: 10, y: 5, owner: "enemy" },
      { id: "gloster-hill", name: "235高地", kind: "capture", x: 10, y: 11, owner: "enemy" },
    ],
    evacZone: [],
    itemDrops: [{ x: 6, y: 8, options: ["arty_support", "at_charge"] }, { x: 13, y: 8, options: ["arty_support"] }],
    places: [
      { id: "imjin-bridgehead", x: 10, y: 5, name: "桥头堡", historicalContext: "渡过临津江后，桥头堡决定后续兵力能否进入南岸纵深。", tacticalHint: "先建立连续阵线，不要让单支步兵孤立在南岸。" },
      { id: "gloster-hill", x: 10, y: 11, name: "235高地", historicalContext: "235高地与英格洛斯特郡团收缩防御相关，是本关纵深终点。", tacticalHint: "高地守军互相掩护强；先断开侧翼，再集中火力占领。" },
      { id: "solma-ri", x: 10, y: 7, name: "雪马里", historicalContext: "雪马里谷地连接渡河轴与高地防御区，地形把战斗压缩在狭窄纵深。", tacticalHint: "控制谷地两侧比挤在中央道路更能阻断增援。" },
      { id: "imjin-river", x: 5, y: 4, name: "临津江", historicalContext: "临津江是战役地理骨架；关卡只表现一段渡河与南岸推进。", tacticalHint: "河流限制横向换线，过河前先确定每支部队的进攻轴。" },
    ],
    scripted: [
      { kind: "barrage", turns: [4, 7], damage: 4, note: "英军炮火拦阻射击" },
      { kind: "supplyWindow", untilTurn: 8, penalty: 0.1, note: "渡河后弹药见底" },
    ],
    victory: { requiredCaptures: 2, holdTurns: 1, minSurvivors: 6 },
  },
  {
    id: "m9-cheorwon",
    name: "铁原阻击",
    kind: "withdraw",
    date: "1951年5月29日—6月10日",
    location: "韩国铁原—涟川交通走廊",
    historicalOutcome: "志愿军第63军在铁原地区实施纵深阻击，为主力完成休整和建立新防线争取时间。",
    historicalNote: "本关强调迟滞与轮换，不以歼灭追击部队为目标。",
    commanders: [
      pva("fu-chongbi", "傅崇碧", "第63军军长", "中国人民志愿军第63军"),
      un("james-van-fleet", "詹姆斯·范弗里特", "第8集团军司令", "美国陆军第8集团军", undefined, "中将（1951年5月）", "us-lieutenant-general"),
    ],
    brief: "依托铁原南北走廊的两道阵地轮换阻击，拖住由涟川方向北上的追击纵队。完成接触迟滞后向北侧纵深撤离，高大全与至少六成部队必须脱离；任务是争取时间而非全歼追兵。",
    mapNote: "北在上；铁原是开阔交通走廊，森林极少。联合国军沿中央公路由南向北追击；北缘是脱离带，两道阻击线是孤立堡垒而不是密林夹道。",
    weather: { options: ["rain", "overcast"], label: "初夏阵雨", detail: "道路泥泞，低云抑制远程观察，但装甲仍可沿公路推进。" },
    playerEquipment: PVA_LATE,
    enemyDamageMultiplier: 1.16,
    maxTurns: 19,
    map: [
      "....................",
      "....................",
      ".........==.........",
      ".........===........",
      ".........=B=........",
      "........====........",
      ".......B====B.......",
      ".....F...==...F.....",
      ".........==.........",
      ".........==.........",
      ".........==.........",
      ".........==.........",
      ".........==.........",
      ".........==........."
    ],
    playerSpawns: [{ x: 7, y: 6 }, { x: 8, y: 6 }, { x: 11, y: 6 }, { x: 12, y: 6 }, { x: 7, y: 5 }, { x: 12, y: 5 }, { x: 9, y: 4 }, { x: 11, y: 4 }],
    storyAllies: [
      { commander: "李玉安", type: "rifle", level: 3, weapon: "mosin", duty: "63军铁原阻击配属" },
      { commander: "倪恩德", type: "mg", level: 3, weapon: "dp28", duty: "走廊火力配属" },
      { commander: "高玉宝", type: "logistics", level: 2, weapon: "supply_cart", duty: "北撤辎重配属" },
    ],
    equipmentEra: "late" as const,
    weaponRewards: ["mosin", "zis3"],
    enemies: [
      { type: "rifle", x: 8, y: 11, name: "美3师追击步兵", equipment: "M1加兰德步枪", exp: 55 },
      { type: "rifle", x: 11, y: 11, name: "美骑1师步兵", equipment: "M1加兰德步枪", exp: 55 },
      { type: "mg", x: 9, y: 12, name: "美军支援火力组", equipment: "勃朗宁M1919机枪", exp: 55 },
      { type: "artillery", x: 15, y: 13, name: "追击纵队炮兵", equipment: "M2A1 105毫米榴弹炮", exp: 40, commanderId: "james-van-fleet", title: "敌军主将", dropOptions: ["field_manual", "arty_support"] },
      { type: "rifle", x: 10, y: 10, name: "美军公路步兵", equipment: "M1加兰德步枪", exp: 35 },
    ],
    variantSlots: [],
    waves: [
      { window: [8, 9], units: [{ type: "rifle", x: 9, y: 12, name: "追击步兵", equipment: "M1加兰德步枪", exp: 50 }, { type: "mg", x: 8, y: 12, name: "追击火力", equipment: "勃朗宁M1919机枪", exp: 45 }] },
      { window: [12, 13], units: [{ type: "rifle", x: 10, y: 12, name: "第二梯队", equipment: "M1加兰德步枪", exp: 50 }] },
    ],
    objectives: [],
    evacZone: [
      { x: 6, y: 0 }, { x: 7, y: 0 }, { x: 8, y: 0 }, { x: 9, y: 0 }, { x: 10, y: 0 }, { x: 11, y: 0 }, { x: 12, y: 0 }, { x: 13, y: 0 },
      { x: 7, y: 1 }, { x: 8, y: 1 }, { x: 9, y: 1 }, { x: 10, y: 1 }, { x: 11, y: 1 }, { x: 12, y: 1 },
      { x: 9, y: 2 }, { x: 10, y: 2 },
    ],
    itemDrops: [{ x: 5, y: 7, options: ["ammo_crate", "grenade_bundle"] }, { x: 14, y: 7, options: ["arty_support"] }],
    places: [
      { id: "cheorwon-second-line", x: 10, y: 4, name: "第二阻击线", historicalContext: "铁原方向的防御以逐次迟滞和保存主力为目的，不是守住单一格位到最后。", tacticalHint: "第一线接敌后退到这里重组，避免同时被多支敌军控制。" },
      { id: "cheorwon-road-mouth", x: 7, y: 6, name: "前沿公路口", historicalContext: "公路口代表联合国军追击兵力进入阻击地域的主要轴线。", tacticalHint: "用机枪和远程火力封口，步兵不要过早越过公路。" },
      { id: "yeoncheon-axis", x: 10, y: 12, name: "涟川追击方向", historicalContext: "南侧边界表示联合国军由涟川方向北进的追击轴。", tacticalHint: "增援会沿道路集中出现，炮兵应预先覆盖而不是临时转场。" },
    ],
    supplyPoints: [{ x: 9, y: 5 }, { x: 11, y: 3 }],
    scripted: [
      { kind: "barrage", turns: [5, 8], damage: 2, note: "联合国军炮火准备" },
    ],
    // 须南下接触击溃 2 个单位后再北撤；撤离通道第 7 回合开放，避免接敌前北撤
    victory: {
      minEvacuated: 4,
      evacuateRatio: 0.4,
      requireKeyUnit: true,
      minEnemiesRouted: 2,
      evacOpensOnTurn: 5,
    },
  },
  {
    id: "m10-triangle-hill",
    name: "上甘岭坑道",
    kind: "hold",
    date: "1952年10月14日—11月25日",
    location: "朝鲜五圣山前沿597.9与537.7高地",
    historicalOutcome: "志愿军第15军、第12军依托坑道体系守住主要阵地，联合国军停止进攻。",
    historicalNote: "棋盘把两个主要高地、坑道口和补给线压缩在同一战术视图。",
    commanders: [
      pva("qin-jiwei", "秦基伟", "第15军军长", "中国人民志愿军第15军", "qin-jiwei"),
      pva("cui-jianggong", "崔建功", "第45师师长", "中国人民志愿军第15军第45师", "cui-jianggong"),
      pva("huang-jiguang", "黄继光", "第45师第135团第2营通讯员", "中国人民志愿军第15军第45师", "huang-jiguang"),
      un("wayne-smith", "韦恩·史密斯", "师长", "美国陆军第7步兵师", undefined, "少将", "us-major-general"),
    ],
    brief: "开局地表阵地已经失守。依托两个坑道后口组织反击，先夺回597.9和537.7北山，再顶住由金化方向分波次压上的敌军；不能只躲在坑道里等待。",
    mapNote: "北在上；五圣山纵深在北，597.9 与 537.7 是紧邻的坑道堡垒，中间只有短交通壕。南侧是破碎高地，没有贯穿南北的公路脊柱。",
    weather: { options: ["overcast", "rain", "snow"], label: "深秋转初冬", detail: "战斗持续43天，经历阴雨、低云和初雪。" },
    playerEquipment: PVA_LATE,
    enemyDamageMultiplier: 1.26,
    maxTurns: 17,
    map: [
      "FF^^^^^^^^^^^^^^^^FF",
      "FF^^^^^^....^^^^^^FF",
      "FF^^^^^^....^^^^^^FF",
      "FF^^^^...==...^^^^FF",
      "FF^^.^^B.==.B^^.^^FF",
      "FF^^.^^BB==BB^^.^^FF",
      "FF^^^...====...^^^FF",
      "FF^^^^..====..^^^^FF",
      "FF^^^^^..==..^^^^^FF",
      "FF^^^^^^.==.^^^^^^FF",
      "FF^^^^^^.==.^^^^^^FF",
      "FF^^^^^^^^.^^^F^^^FF",
      "FF^^^^^^^^^^^^^^^^FF",
      "FF^^^^^^^^^^^^^^^^FF"
    ],
    playerSpawns: [{ x: 8, y: 5 }, { x: 11, y: 5 }, { x: 6, y: 4 }, { x: 13, y: 4 }, { x: 7, y: 5 }, { x: 12, y: 5 }, { x: 9, y: 6 }, { x: 10, y: 6 }],
    storyAllies: [
      { commander: "黄继光", type: "rifle", level: 4, weapon: "ppsh50", portrait: "huang-jiguang", duty: "15军45师135团2营通讯员" },
      { commander: "胡修道", type: "mg", level: 4, weapon: "dp28", duty: "12军31师91团机枪班长" },
      { commander: "孙生禄", type: "logistics", level: 3, weapon: "supply_cart", duty: "坑道补给配属" },
    ],
    equipmentEra: "late" as const,
    weaponRewards: [],
    preMissionWeapons: ["m30_122", "bm13", "mosin_m44_marksman"],
    enemies: [
      { type: "rifle", x: 8, y: 11, name: "美7师突击连", equipment: "M1加兰德步枪", exp: 100, commanderId: "wayne-smith", title: "敌军主将", dropOptions: ["field_manual", "satchel"], dropWeapons: ["m1d_sniper"], dropAttachments: ["t52_vest"] },
      { type: "rifle", x: 11, y: 11, name: "韩2师突击连", equipment: "M1加兰德步枪", exp: 95 },
      { type: "mg", x: 9, y: 11, name: "联合国军火力组", equipment: "勃朗宁M1919机枪", exp: 95 },
      { type: "mortar", x: 10, y: 10, name: "联合国军迫击炮组", equipment: "M1型81毫米迫击炮", exp: 85 },
      { type: "artillery", x: 17, y: 13, name: "联合国军炮兵组", equipment: "M2A1 105毫米榴弹炮", exp: 70 },
      { type: "rifle", x: 10, y: 9, name: "坑道口突击队", equipment: "M1加兰德步枪", exp: 90 },
    ],
    variantSlots: [],
    waves: [
      { window: [2, 3], units: [{ type: "rifle", x: 9, y: 11, name: "轮番突击", equipment: "M1加兰德步枪", exp: 90 }] },
      { window: [5, 6], units: [{ type: "mg", x: 8, y: 10, name: "火力增援", equipment: "勃朗宁M1919机枪", exp: 85 }] },
    ],
    objectives: [
      { id: "hill-5979", name: "597.9高地", kind: "hold", x: 7, y: 4, owner: "enemy" },
      { id: "hill-5377", name: "537.7北山", kind: "hold", x: 12, y: 4, owner: "enemy" },
    ],
    evacZone: [],
    itemDrops: [{ x: 8, y: 8, options: ["satchel", "medkit"] }, { x: 11, y: 8, options: ["satchel"] }],
    places: [
      { id: "hill-597", x: 7, y: 4, name: "597.9高地", historicalContext: "597.9高地与537.7北山构成上甘岭战场的核心前沿阵地。", tacticalHint: "不要把全部单位堆在山顶；坑道与侧后阵地需要保留预备队。" },
      { id: "hill-537", x: 12, y: 4, name: "537.7北山", historicalContext: "双方围绕表面阵地反复争夺，炮火与坑道体系决定持续作战能力。", tacticalHint: "在炮击回合前分散，炮击后再从坑道方向补入前沿。" },
      { id: "tunnel-rear", x: 8, y: 5, name: "坑道后口", historicalContext: "坑道使守军在强烈炮火后仍能保存人员、补充前沿并组织反击。", tacticalHint: "把后勤和重伤单位留在这里，作为前沿轮换的安全节点。" },
      { id: "wushengshan", x: 10, y: 2, name: "五圣山纵深", historicalContext: "五圣山方向是上甘岭阵地体系的纵深背景，本关不把整个山系压成一个目标格。", tacticalHint: "纵深不是退缩失败；保持一条可轮换的补给线比死守前沿更重要。" },
    ],
    supplyPoints: [{ x: 8, y: 5 }, { x: 11, y: 5 }],
    scripted: [
      { kind: "barrage", turns: [3, 6, 9, 12, 15], damage: 5, note: "上甘岭炮火准备" },
      { kind: "supplyWindow", untilTurn: 5, penalty: 0.16, note: "坑道外弹药耗尽" },
    ],
    // 至少守住一处主峰到结束；炮火与弹药窗口压低蹲坑通关率
    victory: { holdUntilEnd: true, minPostsHeld: 1, minSurvivors: 3 },
  },
  {
    id: "m11-pork-chop",
    name: "猪排山争夺",
    kind: "breakthrough",
    date: "1953年7月6—11日",
    location: "朝鲜铁原西北猪排山前哨",
    historicalOutcome: "志愿军攻击猪排山，美军第7师在反复争夺后奉命放弃该前哨阵地。",
    historicalNote: "本关限定为第23军第67师（含第200团）夺取两个前沿支撑点的战术切片；不把前哨得失夸大为战略决战。215号T-34-85以临时配属剧情单位表现有直接史料支持的装甲协同。",
    commanders: [
      pva("zhong-guochu", "钟国楚", "第23军军长", "中国人民志愿军第23军第67师（首攻第200团）"),
      un("arthur-trudeau", "阿瑟·特鲁多", "师长", "美国陆军第7步兵师", undefined, "少将", "us-major-general"),
    ],
    brief: "借雨雾接近猪排山，夺取东、西两个前沿支撑点并顶住反击。壕沟和高地减伤明显，迫击炮与炮火支援是打开缺口的关键。",
    mapNote: "北在上；东西两个支撑点是同一条猪排山脊上的地堡，中间交通壕相连；南北都是接近地，没有贯穿全图的密林夹道。",
    weather: { options: ["rain", "fog"], label: "季风雨雾", detail: "持续降雨与山雾削弱远程火力，谷地泥泞。" },
    enemyDamageMultiplier: 1.5,
    playerEquipment: PVA_LATE_ARMOR,
    maxTurns: 17,
    map: [
      "....^^..........^^..",
      "....^^..........^^..",
      "....^^..........^^..",
      "....^^^^^^^^^^^^^^..",
      "....^^^^^^^^^^^^^^..",
      "....^^^^^^..^^^^^^..",
      "......BB====BB......",
      "....^^^^^^..^^^^^^..",
      ".....^^^^....^^^^...",
      "......^^......^^....",
      ".........==.........",
      "....^^^^....^^^^....",
      "....^^^^....^^^^....",
      "....^^^^....^^^^...."
    ],
    playerSpawns: [{ x: 7, y: 1 }, { x: 8, y: 1 }, { x: 9, y: 1 }, { x: 10, y: 1 }, { x: 11, y: 1 }, { x: 8, y: 2 }, { x: 10, y: 2 }, { x: 12, y: 2 }],
    storyAllies: [
      { commander: "杨育才", type: "rifle", level: 4, weapon: "ppsh50", duty: "第23军第200团突击配属" },
      { commander: "张桃芳", type: "mortar", level: 3, weapon: "mortar82", duty: "前哨火力配属" },
      { commander: "215号坦克车组", type: "tank", level: 4, weapon: "t34_85", equipment: "T-34-85（独立坦克第4团第2连）", duty: "独立坦克第4团第2连车组" },
    ],
    equipmentEra: "late" as const,
    weaponRewards: ["dp28"],
    enemies: [
      { type: "rifle", x: 7, y: 6, name: "美7师前哨西连", equipment: "M1加兰德步枪", exp: 72, commanderId: "arthur-trudeau", title: "敌军主将", dropOptions: ["field_manual", "at_charge"], dropWeapons: ["m1d_sniper", "m1_155"] },
      { type: "rifle", x: 12, y: 6, name: "美7师前哨东连", equipment: "M1加兰德步枪", exp: 72 },
      { type: "mg", x: 9, y: 6, name: "前哨机枪阵地", equipment: "勃朗宁M1919机枪", exp: 95 },
      { type: "artillery", x: 14, y: 12, name: "主抵抗线炮兵组", equipment: "M2A1 105毫米榴弹炮", exp: 88 },
      { type: "mortar", x: 10, y: 10, name: "前哨迫击炮组", equipment: "M1型81毫米迫击炮", exp: 75 },
    ],
    variantSlots: [],
    waves: [
      { window: [4, 4], units: [{ type: "rifle", x: 9, y: 12, name: "第一次反击队", equipment: "M1加兰德步枪", exp: 100 }] },
      { window: [6, 6], units: [
        { type: "mg", x: 10, y: 12, name: "反击火力增援", equipment: "勃朗宁M1919机枪", exp: 90 },
        { type: "rifle", x: 11, y: 12, name: "第二次反击队", equipment: "M1加兰德步枪", exp: 85 },
      ] },
    ],
    objectives: [
      { id: "pork-west", name: "猪排山西支撑点", kind: "capture", x: 7, y: 6, owner: "enemy" },
      { id: "pork-east", name: "猪排山东支撑点", kind: "capture", x: 12, y: 6, owner: "enemy" },
    ],
    evacZone: [],
    itemDrops: [{ x: 6, y: 8, options: ["arty_support", "at_charge"] }, { x: 13, y: 8, options: ["arty_support"] }],
    places: [
      { id: "pork-chop-west", x: 7, y: 6, name: "西支撑点", historicalContext: "石岘洞北山争夺围绕相互支撑的山脊阵地展开，而不是单一山头的一次冲锋。", tacticalHint: "先压制一侧火力，再沿交通壕转向另一侧，避免兵力平均分散。" },
      { id: "pork-chop-east", x: 12, y: 6, name: "东支撑点", historicalContext: "东西支撑点共同维持前哨阵地；任一侧孤立都会削弱相互掩护。", tacticalHint: "利用包围机制切断两点之间的覆盖，再完成连续占领。" },
      { id: "pork-chop-trench", x: 10, y: 6, name: "交通壕", historicalContext: "交通壕连接前沿支撑点，承担隐蔽机动和补充作用。", tacticalHint: "控制中间通路可以阻止守军横向增援。" },
    ],
    scripted: [
      { kind: "barrage", turns: [1], damage: 7, target: "enemy", note: "第23军第67师三分钟炮火急袭" },
      { kind: "barrage", turns: [3, 6], damage: 8, note: "美7师炮火反击" },
    ],
    // 新版包围火力会提高前沿伤亡；保留夺点与坚守要求，但允许一个分队减员。
    victory: { requiredCaptures: 2, holdTurns: 4, minSurvivors: 6 },
  },
  {
    id: "m12-kumsong",
    name: "金城反击",
    kind: "breakthrough",
    date: "1953年7月13日21时—14日10时",
    location: "朝鲜金城以南轿岩山地区",
    historicalOutcome: "第67军第199师经一夜激战于14日午前攻占轿岩山主峰；金城战役其余正面与停战收束仅作背景。",
    historicalNote: "游戏只聚焦第67军第199师攻击韩军第6师轿岩山阵地的第一夜；东翼北汉江方向不压入同一战术棋盘。战役级装甲资料不下放为本切片的确定性坦克单位。",
    commanders: [
      pva("yang-yong", "杨勇", "第20兵团司令员", "中国人民志愿军第20兵团"),
      un("maxwell-taylor", "马克斯韦尔·泰勒", "第8集团军司令", "美国陆军第8集团军", undefined, "中将", "us-lieutenant-general"),
    ],
    brief: "在炮火准备后由北向南突破轿岩山三峰阵地：先撕开中、东峰结合部，再夺主峰。暴雨掩护接近也会拖慢机动；最后一关仍以保存主力为硬约束。",
    mapNote: "北在上；轿岩山主峰与中东峰错落，南侧金城川横贯；北汉江在画外。三峰不是对称双墙，也没有贯穿南北的密林夹道。",
    weather: { options: ["rain"], label: "盛夏暴雨", detail: "季风暴雨造成河水上涨、道路泥泞，远程火力效果下降。" },
    // 金城反击的基础策略在新敌方集火规则下难以突破，保留纵深火力但给正面突击留出可玩窗口。
    enemyDamageMultiplier: 0.64,
    playerEquipment: PVA_LATE,
    maxTurns: 23,
    map: [
      "....^^..........^^..",
      "....^^..........^^..",
      "....^^..........^^..",
      "...^^^^........^^^^.",
      "..^^^^^......^^^^^..",
      "...^^^^^....^^^^^...",
      "....^^^^B^^B^^^^....",
      ".....^^B^^.^^^^^....",
      "....^^^^^..^^^^^....",
      "....^^^^^..^^^^^....",
      "FF^~~~~~~==~~~~~~^FF",
      "FF^FF....==....FF^FF",
      "FF^FF....==....FF^FF",
      "FF^##F...==...F##^FF"
    ],
    playerSpawns: [{ x: 7, y: 1 }, { x: 8, y: 1 }, { x: 9, y: 1 }, { x: 10, y: 1 }, { x: 11, y: 1 }, { x: 8, y: 2 }, { x: 10, y: 2 }, { x: 12, y: 2 }],
    storyAllies: [
      { commander: "王兆才", type: "rifle", level: 4, weapon: "ppsh50", duty: "第199师轿岩山突击配属" },
      { commander: "唐章洪", type: "mortar", level: 4, weapon: "mortar82", equipment: "82毫米迫击炮", duty: "轿岩山炮火配属" },
    ],
    equipmentEra: "late" as const,
    weaponRewards: [],
    enemies: [
      { type: "rifle", x: 7, y: 7, name: "韩军第6师主峰守备连", equipment: "M1加兰德步枪", exp: 70, commanderId: "maxwell-taylor", title: "敌军主将", dropOptions: ["field_manual", "arty_support"] },
      { type: "rifle", x: 11, y: 6, name: "韩军第6师中东峰守备连", equipment: "M1加兰德步枪", exp: 70 },
      { type: "mg", x: 9, y: 6, name: "韩军地堡火力组", equipment: "勃朗宁M1919机枪", exp: 65 },
      { type: "artillery", x: 15, y: 11, name: "韩军纵深炮兵组", equipment: "M2A1 105毫米榴弹炮", exp: 60 },
      { type: "rifle", x: 10, y: 9, name: "韩军纵深警戒队", equipment: "M1加兰德步枪", exp: 40 },
    ],
    variantSlots: [],
    waves: [{ window: [5, 6], units: [{ type: "rifle", x: 10, y: 12, name: "韩军预备队", equipment: "M1加兰德步枪", exp: 65 }] }, { window: [9, 10], units: [{ type: "mg", x: 9, y: 12, name: "金城川机枪队", equipment: "勃朗宁M1919机枪", exp: 75 }, { type: "rifle", x: 11, y: 12, name: "韩军纵深反击队", equipment: "M1加兰德步枪", exp: 70 }] }],
    objectives: [
      { id: "kyoyam-east", name: "轿岩山中东峰", kind: "capture", x: 11, y: 6, owner: "enemy" },
      { id: "kyoyam-main", name: "轿岩山主峰", kind: "capture", x: 7, y: 7, owner: "enemy" },
    ],
    evacZone: [],
    itemDrops: [{ x: 6, y: 8, options: ["medkit", "ration"] }, { x: 13, y: 8, options: ["at_charge", "arty_support"] }],
    places: [
      { id: "kyoryang-main", x: 7, y: 7, name: "轿岩山主峰", historicalContext: "轿岩山位于联合国军前沿防御地带，主峰与中、东峰共同构成制高点体系。", tacticalHint: "开局炮火后立刻抢占接近路线，避免守军恢复完整掩护。" },
      { id: "kyoryang-east", x: 11, y: 6, name: "轿岩山中东峰", historicalContext: "中东峰与主峰相互支撑，本关以双目标表现连续攻坚。", tacticalHint: "先切断峰间通路再逐点夺取，三面控制能显著提高突破效率。" },
      { id: "kumsong-river", x: 10, y: 10, name: "金城川", historicalContext: "金城川划分突出部纵深并限制部队横向机动，是战役地理的重要组成。", tacticalHint: "雨天河谷机动缓慢；预先分配两翼部队，减少临场横移。" },
    ],
    scripted: [
      { kind: "barrage", turns: [1], damage: 8, target: "enemy", note: "志愿军开局炮火准备" },
      { kind: "barrage", turns: [7, 11], damage: 2, note: "联合国军拦阻炮火" },
      { kind: "supplyWindow", untilTurn: 9, penalty: 0.1, note: "金城反击弹药窗口" },
    ],
    victory: { requiredCaptures: 2, holdTurns: 1, minSurvivors: 2 },
  },
];
