import type { MissionConfig } from "./schema";

const PVA_EARLY = {
  rifle: "三八式／中正式步枪、手榴弹",
  mg: "捷克式ZB-26轻机枪",
  mortar: "31式60毫米迫击炮",
  tank: "缴获反坦克武器",
} as const;

const PVA_LATE = {
  rifle: "莫辛-纳甘步枪、50式冲锋枪",
  mg: "DP-28轻机枪／24式重机枪",
  mortar: "82毫米迫击炮",
  tank: "T-34-85装甲支援",
} as const;

const pva = (id: string, name: string, role: string, formation: string, portrait?: string) => ({
  id,
  name,
  faction: "player" as const,
  role,
  formation,
  ...(portrait ? { portrait } : {}),
});

const un = (id: string, name: string, role: string, formation: string, portrait?: string) => ({
  id,
  name,
  faction: "enemy" as const,
  role,
  formation,
  ...(portrait ? { portrait } : {}),
});

/**
 * 12关按时间顺序覆盖志愿军入朝、运动战、阵地战与停战前反击。
 * 棋盘是团/营级战术抽象，不宣称按比例复刻整场战役。
 */
export const HISTORICAL_MISSIONS: MissionConfig[] = [
  {
    id: "m1-onjong",
    name: "温井初战",
    kind: "breakthrough",
    date: "1950年10月25日",
    location: "朝鲜温井—北镇公路",
    historicalOutcome: "志愿军第40军在温井地区击破韩军先头部队，第一次战役由此展开。",
    historicalNote: "玩家指挥的是虚构的志司直属加强营；高大全及其部队不对应任何真实番号。",
    commanders: [
      pva("wen-yucheng", "温玉成", "第40军军长", "中国人民志愿军第40军"),
      un("paik-sun-yup", "白善烨", "第1师师长", "韩国陆军第1步兵师"),
    ],
    brief: "黄昏前封住北镇公路，在山谷两侧穿插，夺取温井和公路岔口。敌军机械化程度有限，但可能沿公路快速增援。高大全必须生还。",
    mapNote: "北在上；中央纵向道路模拟温井—北镇公路，西侧村落为温井，东侧高地控制岔路。",
    weather: { options: ["clear", "overcast"], label: "深秋寒夜", detail: "低温、天黑后能见度下降；长射程火力略受影响。" },
    playerEquipment: PVA_EARLY,
    maxTurns: 13,
    map: [
      "^^FFF.==..FF^^",
      "^.FF^.==F.F#.^",
      "F..B#.==.F^.F.",
      ".FFFF.==.^^^.F",
      ".#F...==.^.F#.",
      "~~~F..==.F.~~~",
      ".FF.F.==..FF.F",
      "..#.^F==.^.F^#",
      "F..F^.==.F.^F.",
      "...^..==......",
    ],
    playerSpawns: [{ x: 5, y: 9 }, { x: 6, y: 9 }, { x: 7, y: 9 }, { x: 8, y: 9 }, { x: 5, y: 8 }, { x: 6, y: 8 }, { x: 7, y: 8 }, { x: 8, y: 8 }],
    storyAllies: [
      { commander: "韩卫东", type: "rifle", level: 2, weapon: "type38" },
      { commander: "吕四海", type: "mg", level: 1, weapon: "zb26" },
    ],
    equipmentEra: "early" as const,
    weaponRewards: ["zhongzheng" as const],
    enemies: [
      { type: "rifle", x: 3, y: 2, name: "韩军步兵连", equipment: "M1加兰德步枪", exp: 50 },
      { type: "rifle", x: 9, y: 4, name: "韩军先遣连", equipment: "M1卡宾枪", exp: 42 },
      { type: "mg", x: 6, y: 3, name: "韩军机枪排", equipment: "勃朗宁M1919机枪", exp: 55 },
      { type: "rifle", x: 7, y: 1, name: "北镇警戒队", equipment: "M1加兰德步枪", exp: 38 },
      { type: "mortar", x: 8, y: 2, name: "韩军迫击炮组", equipment: "M1型60毫米迫击炮", exp: 40 },
    ],
    variantSlots: [{ index: 3, options: ["rifle", "mg"] }],
    waves: [
      { window: [3, 4], units: [{ type: "rifle", x: 7, y: 0, name: "韩军公路增援", equipment: "M1加兰德步枪", exp: 40 }] },
      { window: [6, 7], units: [{ type: "mg", x: 9, y: 2, name: "岔口机枪班", equipment: "勃朗宁M1919机枪", exp: 45 }] },
    ],
    objectives: [
      { id: "onjong", name: "温井", kind: "capture", x: 3, y: 2, owner: "enemy" },
      { id: "road-junction", name: "北镇公路岔口", kind: "capture", x: 9, y: 4, owner: "enemy" },
    ],
    evacZone: [],
    itemDrops: [{ x: 4, y: 6, options: ["medkit", "bandage", "ration"] }, { x: 9, y: 6, options: ["medkit", "bandage", "ration"] }],
    places: [
      { x: 3, y: 2, name: "温井" },
      { x: 9, y: 4, name: "北镇岔口" },
      { x: 6, y: 0, name: "北镇公路" },
    ],
    scripted: [
      { kind: "nightAssault", turns: [1, 3], attackBonus: 0.18, note: "黄昏夜袭：志愿军近战火力占优" },
    ],
    victory: { requiredCaptures: 2, holdTurns: 2, minSurvivors: 2 },
  },
  {
    id: "m2-unsan",
    name: "云山合围",
    kind: "breakthrough",
    date: "1950年11月1—3日",
    location: "朝鲜云山—诸仁桥",
    historicalOutcome: "志愿军第39军攻入云山并切断南撤通路，美骑兵第1师第8团遭受重创。",
    historicalNote: "美军与韩军正处于换防过程；关卡用两处据点表现云山城和诸仁桥。",
    commanders: [
      pva("wu-xinquan", "吴信泉", "第39军军长", "中国人民志愿军第39军", "wu-xinquan"),
      un("hobart-gay", "霍巴特·盖伊", "师长", "美国陆军骑兵第1师"),
      un("paik-sun-yup", "白善烨", "师长", "韩国陆军第1步兵师"),
    ],
    brief: "趁换防间隙从东北、西北两翼压缩云山，先占云山城，再封锁诸仁桥。美军坦克会沿公路突围，反坦克爆破必须留到关键时刻。",
    mapNote: "北在上；云山城在河谷北岸，诸仁桥在河南公路折点，中央道路是唯一快速南撤通道。",
    weather: { options: ["clear", "overcast"], label: "寒冷夜战", detail: "入夜后气温下降，山谷间有薄雾。" },
    playerEquipment: PVA_EARLY,
    maxTurns: 13,
    map: [
      "^^F^^F==FF^^^^",
      "^F.FF.==.F^^F^",
      ".F.BF.==..FF.^",
      "^^FF..==F.FF^^",
      "~~~~F.==.F~~~~",
      "..F^#.==.#^F..",
      ".FF.^.==..VFB.",
      "F.#F^.==.^F#.^",
      "..#...==.^....",
      ".^....==......",
    ],
    playerSpawns: [{ x: 5, y: 9 }, { x: 6, y: 9 }, { x: 7, y: 9 }, { x: 8, y: 9 }, { x: 4, y: 8 }, { x: 6, y: 8 }, { x: 7, y: 8 }, { x: 9, y: 8 }],
    storyAllies: [
      { commander: "方成林", type: "rifle", level: 2, weapon: "zhongzheng" },
      { commander: "白峻峰", type: "mortar", level: 2, weapon: "mortar60" },
    ],
    equipmentEra: "early" as const,
    weaponRewards: ["zb26" as const],
    enemies: [
      { type: "rifle", x: 3, y: 2, name: "美骑8团步兵", equipment: "M1加兰德步枪", exp: 55 },
      { type: "rifle", x: 10, y: 6, name: "韩军换防部队", equipment: "M1卡宾枪", exp: 48 },
      { type: "mg", x: 6, y: 3, name: "美骑8团火力排", equipment: "勃朗宁M1919机枪", exp: 58 },
      { type: "mg", x: 7, y: 1, name: "美骑8团机枪班", equipment: "勃朗宁M1919机枪", exp: 45 },
      { type: "mortar", x: 10, y: 5, name: "诸仁桥迫击炮", equipment: "M1型81毫米迫击炮", exp: 42 },
    ],
    variantSlots: [{ index: 1, options: ["rifle", "mg"] }],
    waves: [
      { window: [4, 5], units: [
        { type: "rifle", x: 7, y: 0, name: "美骑5团援军", equipment: "M1加兰德步枪", exp: 42 },
        { type: "mg", x: 10, y: 4, name: "桥头机枪", equipment: "勃朗宁M1919机枪", exp: 40 },
      ] },
      { window: [7, 8], units: [{ type: "rifle", x: 3, y: 1, name: "云山反扑队", equipment: "M1加兰德步枪", exp: 38 }] },
    ],
    objectives: [
      { id: "unsan-town", name: "云山城", kind: "capture", x: 3, y: 2, owner: "enemy" },
      { id: "cho-in-bridge", name: "诸仁桥", kind: "capture", x: 10, y: 6, owner: "enemy" },
    ],
    evacZone: [],
    itemDrops: [{ x: 3, y: 7, options: ["medkit", "at_charge", "satchel", "field_manual"] }, { x: 10, y: 7, options: ["at_charge"] }],
    places: [
      { x: 3, y: 2, name: "云山城" },
      { x: 10, y: 6, name: "诸仁桥" },
      { x: 6, y: 4, name: "清川支流" },
    ],
    scripted: [
      { kind: "nightAssault", turns: [1, 4], attackBonus: 0.2, note: "夜袭换防间隙：近战加成" },
    ],
    victory: { requiredCaptures: 2, holdTurns: 1, minSurvivors: 2 },
  },
  {
    id: "m3-chongchon",
    name: "清川江穿插",
    kind: "breakthrough",
    date: "1950年11月25日—12月2日",
    location: "朝鲜德川—三所里—龙源里",
    historicalOutcome: "志愿军第二次战役西线突破韩军防线并向三所里穿插，迫使美第8集团军全面后撤。",
    historicalNote: "关卡聚焦第38军向敌后公路穿插的战术片段，不表现整条清川江战线。",
    commanders: [
      pva("liang-xingchu", "梁兴初", "第38军军长", "中国人民志愿军第38军"),
      un("walton-walker", "沃尔顿·沃克", "第8集团军司令", "美国陆军第8集团军"),
    ],
    brief: "沿山脊绕开正面火力，抢占三所里与龙源里两个公路节点，截断南撤车队。时间比歼敌更重要，过度恋战会错过窗口。",
    mapNote: "北在上；清川江横贯中部成阻隔，东西公路节点三所里与龙源里夹住南撤走廊。",
    weather: { options: ["snow", "overcast"], label: "初雪与冻土", detail: "寒潮到来，山路结冰，部队移动与远射均受影响。" },
    playerEquipment: PVA_EARLY,
    maxTurns: 12,
    map: [
      "F^^^#.==.^F^^F",
      "^^FBF.==.FVF^F",
      ".F....==....F.",
      "^^^^F.==.F#^^^",
      "~~~========~~~",
      "F#^^..==..^^#F",
      "..F^#.==.#^F..",
      ".F.FF.==..F.F.",
      "^.....==......",
      "F..F..==.F..F.",
    ],
    playerSpawns: [{ x: 5, y: 9 }, { x: 6, y: 9 }, { x: 7, y: 9 }, { x: 8, y: 9 }, { x: 4, y: 8 }, { x: 6, y: 8 }, { x: 7, y: 8 }, { x: 9, y: 8 }],
    storyAllies: [
      { commander: "路远征", type: "rifle", level: 2, weapon: "zhongzheng" },
      { commander: "岳长弓", type: "mortar", level: 2, weapon: "mortar60" },
    ],
    equipmentEra: "early" as const,
    weaponRewards: ["mortar60" as const],
    enemies: [
      { type: "rifle", x: 3, y: 1, name: "美2师后卫", equipment: "M1加兰德步枪", exp: 80 },
      { type: "rifle", x: 10, y: 1, name: "韩军警戒营", equipment: "M1卡宾枪", exp: 50 },
      { type: "mg", x: 6, y: 3, name: "公路护卫火力组", equipment: "勃朗宁M1919机枪", exp: 80 },
      { type: "mortar", x: 8, y: 0, name: "美军迫击炮组", equipment: "M1型81毫米迫击炮", exp: 65 },
      { type: "rifle", x: 7, y: 2, name: "清川江警戒", equipment: "M1加兰德步枪", exp: 55 },
    ],
    variantSlots: [{ index: 1, options: ["rifle", "mg"] }],
    waves: [{ window: [5, 6], units: [{ type: "rifle", x: 7, y: 0, name: "南撤公路纵队", equipment: "M1加兰德步枪", exp: 50 }] }, { window: [8, 9], units: [{ type: "mg", x: 6, y: 0, name: "后卫火力", equipment: "勃朗宁M1919机枪", exp: 45 }] }],
    objectives: [
      { id: "samsori", name: "三所里", kind: "capture", x: 3, y: 1, owner: "enemy" },
      { id: "yongwon", name: "龙源里", kind: "capture", x: 10, y: 1, owner: "enemy" },
    ],
    evacZone: [],
    itemDrops: [{ x: 3, y: 6, options: ["medkit", "bandage", "ration"] }, { x: 10, y: 6, options: ["at_charge", "arty_support"] }],
    places: [
      { x: 3, y: 1, name: "三所里" },
      { x: 10, y: 1, name: "龙源里" },
      { x: 6, y: 4, name: "清川江" },
    ],
    scripted: [
      { kind: "nightAssault", turns: [1, 3], attackBonus: 0.15, note: "穿插夜战：近战加成" },
      { kind: "supplyWindow", untilTurn: 6, penalty: 0.16, note: "携行弹药见底：攻击衰减" },
    ],
    victory: { requiredCaptures: 2, holdTurns: 2, minSurvivors: 2 },
  },
  {
    id: "m4-chosin",
    name: "长津湖断路",
    kind: "hold",
    date: "1950年11月27日—12月13日",
    location: "朝鲜长津湖柳潭里—下碣隅里公路",
    historicalOutcome: "志愿军第9兵团围攻美第10军部队；美陆战1师经下碣隅里向兴南有组织撤出，双方均伤亡惨重。",
    historicalNote: "不采用“全歼陆战1师”的虚构目标；玩家任务是阻断道路并迟滞撤退。",
    commanders: [
      pva("song-shilun", "宋时轮", "第9兵团司令员", "中国人民志愿军第9兵团", "song-shilun"),
      un("oliver-smith", "奥利弗·史密斯", "师长", "美国海军陆战队第1师", "oliver-smith"),
      un("edward-almond", "爱德华·阿尔蒙德", "第10军军长", "美国陆军第10军"),
    ],
    brief: "在极寒中守住死鹰岭与公路垭口，迟滞陆战1师向下碣隅里的撤退。敌军拥有装甲、炮兵和空中支援；保存高大全比追击更重要。",
    mapNote: "北在上；东侧大片水域抽象长津湖，西岸公路是柳潭里至下碣隅里唯一退路，两处高地卡口。",
    weather: { options: ["snow"], label: "极寒暴雪", detail: "约零下二三十摄氏度的严寒；积雪降低移动力与远程火力。" },
    playerEquipment: PVA_EARLY,
    maxTurns: 9,
    map: [
      ".F..F.==..~~~~",
      "..F...==.#F~~~",
      "^^^^^.==.F~~~~",
      ".F^^F.==..^^.~",
      "~~~~..==.^~~~~",
      "F^.F^^==^^..F.",
      "^F.^^.==.^^B.F",
      ".#F.^^==^^.F#^",
      "F..F..==.F..F.",
      "......==...^..",
    ],
    playerSpawns: [{ x: 4, y: 6 }, { x: 9, y: 6 }, { x: 5, y: 5 }, { x: 8, y: 5 }, { x: 4, y: 7 }, { x: 9, y: 7 }, { x: 6, y: 7 }, { x: 7, y: 7 }],
    storyAllies: [
      { commander: "冰河清", type: "rifle", level: 2, weapon: "zhongzheng" },
      { commander: "雪原声", type: "mg", level: 2, weapon: "zb26" },
    ],
    equipmentEra: "early" as const,
    weaponRewards: ["mosin" as const],
    enemies: [
      { type: "rifle", x: 5, y: 1, name: "陆战5团步兵", equipment: "M1加兰德步枪", exp: 100 },
      { type: "rifle", x: 8, y: 1, name: "陆战7团步兵", equipment: "M1加兰德步枪", exp: 100 },
      { type: "mg", x: 6, y: 0, name: "陆战队火力组", equipment: "BAR／勃朗宁M1919机枪", exp: 120 },
      { type: "rifle", x: 7, y: 0, name: "陆战队公路警戒队", equipment: "M1加兰德步枪", exp: 70 },
    ],
    variantSlots: [{ index: 1, options: ["rifle", "mg"] }],
    waves: [
      { window: [2, 3], units: [{ type: "rifle", x: 4, y: 0, name: "下碣隅里纵队", equipment: "M1加兰德步枪", exp: 90 }, { type: "mg", x: 5, y: 0, name: "纵队火力", equipment: "勃朗宁M1919机枪", exp: 80 }] },
      { window: [5, 6], units: [{ type: "rifle", x: 7, y: 0, name: "陆战队后卫分队", equipment: "M1加兰德步枪", exp: 75 }] },
      { window: [7, 8], units: [{ type: "mg", x: 8, y: 0, name: "后卫火力", equipment: "勃朗宁M1919机枪", exp: 70 }] },
    ],
    objectives: [
      { id: "toktong-pass", name: "死鹰岭", kind: "hold", x: 4, y: 6, owner: "player" },
      { id: "road-pass", name: "公路垭口", kind: "hold", x: 9, y: 6, owner: "player" },
    ],
    evacZone: [],
    itemDrops: [{ x: 3, y: 6, options: ["medkit", "at_charge", "satchel", "field_manual"] }, { x: 10, y: 6, options: ["at_charge"] }],
    places: [
      { x: 4, y: 6, name: "死鹰岭" },
      { x: 9, y: 6, name: "公路垭口" },
      { x: 6, y: 0, name: "下碣隅里方向" },
      { x: 12, y: 2, name: "长津湖" },
    ],
    scripted: [
      { kind: "coldAttrition", fromTurn: 1, damage: 5, note: "极寒冻伤：双方持续减员" },
    ],
    victory: { holdUntilEnd: true, minPostsHeld: 2, minSurvivors: 2 },
  },
  {
    id: "m5-third-offensive",
    name: "突破三八线",
    kind: "breakthrough",
    date: "1950年12月31日—1951年1月8日",
    location: "朝鲜临津江—议政府方向",
    historicalOutcome: "志愿军与朝鲜人民军突破三八线防御，联合国军撤出汉城。",
    historicalNote: "关卡表现第三次战役西线的一段渡河与山口突破。",
    commanders: [
      pva("peng-dehuai", "彭德怀", "司令员兼政治委员", "中国人民志愿军", "peng-dehuai"),
      un("matthew-ridgway", "马修·李奇微", "第8集团军司令", "美国陆军第8集团军", "matthew-ridgway"),
    ],
    brief: "夜渡临津江，夺取议政府北侧山口和公路站。守军正收缩到纵深阵地，必须在其完成部署前连续占领两个节点。",
    mapNote: "横向河流模拟临津江，纵向道路指向议政府；高地控制渡口与公路。",
    weather: { options: ["snow", "clear"], label: "隆冬冻江", detail: "河面部分冻结，夜间严寒，部队体力消耗明显。" },
    playerEquipment: PVA_EARLY,
    maxTurns: 12,
    map: [
      "..^^^F==..^^.#",
      "F..B..==.FV.F.",
      ".FFFF.==.^FF.F",
      "^^^^..==..^^^^",
      "~~~~~~==~~~~~~",
      "#FF.F.==..FF.F",
      "..F.^.==.^.F^.",
      "F.FF^.==.F.FF.",
      "...^..==......",
      "......==.^....",
    ],
    playerSpawns: [{ x: 5, y: 9 }, { x: 6, y: 9 }, { x: 7, y: 9 }, { x: 8, y: 9 }, { x: 4, y: 8 }, { x: 6, y: 8 }, { x: 7, y: 8 }, { x: 9, y: 8 }],
    storyAllies: [
      { commander: "江渡舟", type: "rifle", level: 3, weapon: "mosin" },
      { commander: "岭上松", type: "mg", level: 2, weapon: "dp28" },
    ],
    equipmentEra: "late" as const,
    weaponRewards: ["dp28" as const],
    enemies: [
      { type: "rifle", x: 3, y: 1, name: "联合国军前哨", equipment: "M1加兰德步枪", exp: 58 },
      { type: "rifle", x: 10, y: 1, name: "韩军山口守备队", equipment: "M1卡宾枪", exp: 42 },
      { type: "mg", x: 6, y: 3, name: "渡口机枪阵地", equipment: "勃朗宁M1919机枪", exp: 65 },
      { type: "mortar", x: 8, y: 2, name: "纵深迫击炮组", equipment: "M1型81毫米迫击炮", exp: 50 },
      { type: "rifle", x: 7, y: 2, name: "江岸步兵", equipment: "M1加兰德步枪", exp: 45 },
    ],
    variantSlots: [{ index: 1, options: ["rifle", "mg"] }],
    waves: [{ window: [6, 7], units: [{ type: "rifle", x: 7, y: 0, name: "公路后卫", equipment: "M1加兰德步枪", exp: 50 }] }],
    objectives: [
      { id: "uigongbu-pass", name: "议政府山口", kind: "capture", x: 3, y: 1, owner: "enemy" },
      { id: "road-station", name: "公路站", kind: "capture", x: 10, y: 1, owner: "enemy" },
    ],
    evacZone: [],
    itemDrops: [{ x: 4, y: 6, options: ["medkit", "bandage", "ration"] }, { x: 9, y: 6, options: ["at_charge", "arty_support"] }],
    places: [
      { x: 3, y: 1, name: "议政府山口" },
      { x: 10, y: 1, name: "公路站" },
    ],
    scripted: [
      { kind: "nightAssault", turns: [1, 3], attackBonus: 0.12, note: "三八线夜袭" },
      { kind: "supplyWindow", untilTurn: 7, penalty: 0.14, note: "礼拜攻势：弹药见底" },
    ],
    victory: { requiredCaptures: 2, holdTurns: 2, minSurvivors: 2 },
  },
  {
    id: "m6-hoengsong",
    name: "横城反击",
    kind: "breakthrough",
    date: "1951年2月11—13日",
    location: "韩国横城北部山地",
    historicalOutcome: "志愿军对韩军第8师方向实施反击，联合国军中部战线被迫后撤。",
    historicalNote: "游戏聚焦雪夜穿插和切断横城公路，不把砥平里防御战合并进本关。",
    commanders: [
      pva("wen-yucheng", "温玉成", "第40军军长", "中国人民志愿军第40军"),
      un("edward-almond", "爱德华·阿尔蒙德", "第10军军长", "美国陆军第10军"),
    ],
    brief: "在雪夜从两翼越过山脊，夺取横城北站和砥平里公路口。敌军火力强但部署拉长，集中兵力逐段切断比正面硬攻有效。",
    mapNote: "村庄代表横城北缘，东南道路通往砥平里；山地间只有少数可快速机动的谷道。",
    weather: { options: ["snow", "fog"], label: "雪夜低云", detail: "积雪与低云降低双方机动和远程观察。" },
    playerEquipment: PVA_EARLY,
    maxTurns: 14,
    map: [
      "^^FF..==.#FF^^",
      "^F#FF.==^.F..^",
      "^.FB.F==..VF..",
      "F.^^..==.F^^F^",
      ".F.#^.==.^F.^F",
      "..FF^.==..FF..",
      "~~~F..==.F^~~~",
      ".F^.^.==.^F..F",
      ".^....==......",
      "F..F..==.F..#.",
    ],
    playerSpawns: [{ x: 5, y: 9 }, { x: 6, y: 9 }, { x: 7, y: 9 }, { x: 8, y: 9 }, { x: 4, y: 8 }, { x: 6, y: 8 }, { x: 7, y: 8 }, { x: 9, y: 8 }],
    storyAllies: [
      { commander: "山口猛", type: "rifle", level: 3, weapon: "mosin" },
      { commander: "雪原炮", type: "mortar", level: 3, weapon: "mortar82" },
    ],
    equipmentEra: "late" as const,
    weaponRewards: ["ppsh50" as const],
    enemies: [
      { type: "rifle", x: 3, y: 2, name: "韩军第8师步兵", equipment: "M1加兰德步枪", exp: 35 },
      { type: "rifle", x: 10, y: 2, name: "美军交通警戒队", equipment: "M1卡宾枪", exp: 45 },
      { type: "mg", x: 6, y: 3, name: "横城北站火力点", equipment: "勃朗宁M1919机枪", exp: 55 },
      { type: "mortar", x: 8, y: 1, name: "美军迫击炮组", equipment: "M1型81毫米迫击炮", exp: 45 },
    ],
    variantSlots: [{ index: 0, options: ["rifle", "mg"] }],
    waves: [{ window: [8, 9], units: [{ type: "rifle", x: 7, y: 0, name: "横城后卫", equipment: "M1加兰德步枪", exp: 40 }] }],
    objectives: [
      { id: "hoengsong-north", name: "横城北站", kind: "capture", x: 3, y: 2, owner: "enemy" },
      { id: "chipyong-road", name: "砥平里公路口", kind: "capture", x: 10, y: 2, owner: "enemy" },
    ],
    evacZone: [],
    itemDrops: [{ x: 4, y: 6, options: ["medkit", "bandage", "ration"] }, { x: 9, y: 6, options: ["at_charge"] }],
    places: [
      { x: 3, y: 2, name: "横城北站" },
      { x: 10, y: 2, name: "砥平里方向" },
    ],
    scripted: [
      { kind: "nightAssault", turns: [1, 3], attackBonus: 0.14, note: "横城夜袭" },
    ],
    victory: { requiredCaptures: 2, holdTurns: 1, minSurvivors: 2 },
  },
  {
    id: "m7-chipyongni",
    name: "砥平里外线",
    kind: "withdraw",
    date: "1951年2月13—15日",
    location: "韩国砥平里环形阵地外围",
    historicalOutcome: "美23团战斗队与法军营守住砥平里，增援装甲纵队打通通路；志愿军停止进攻并撤出。",
    historicalNote: "本关不允许玩家虚构攻占砥平里；目标是夜间牵制后在白昼空中火力到来前脱离。",
    commanders: [
      pva("wu-xinquan", "吴信泉", "第39军军长", "中国人民志愿军第39军"),
      un("paul-freeman", "保罗·弗里曼", "第23团团长", "美国陆军第2师第23步兵团"),
      un("ralph-monclar", "拉尔夫·蒙克拉尔", "法军营营长", "法国联合国营"),
    ],
    brief: "砥平里守军已构成环形阵地。夜间压迫外围、牵制其火力；天亮前让高大全和至少半数部队从北侧山路撤出。不要在开阔地同炮兵与装甲纵队消耗。",
    mapNote: "村庄与环形高地代表砥平里防御圈；北侧整行是预定脱离地域，南侧公路为敌装甲增援方向。",
    weather: { options: ["snow", "overcast"], label: "残雪与低云", detail: "夜间寒冷，天亮后能见度逐步改善。" },
    playerEquipment: PVA_EARLY,
    maxTurns: 8,
    map: [
      "==============",
      "..^^..==.#^^..",
      "F^FF..==.FFF^#",
      ".F^^FB==V.^^.F",
      "..F^^^==^^#F..",
      "~~~~..==.F~~~~",
      ".FF.F.==..FF.F",
      "#.F...==...#..",
      "F.^F..==.F.^F^",
      ".....^==....^.",
    ],
    playerSpawns: [{ x: 5, y: 7 }, { x: 6, y: 7 }, { x: 7, y: 7 }, { x: 8, y: 7 }, { x: 5, y: 8 }, { x: 6, y: 8 }, { x: 7, y: 8 }, { x: 8, y: 8 }],
    storyAllies: [
      { commander: "外线鹰", type: "rifle", level: 3, weapon: "mosin" },
      { commander: "掩护盾", type: "mg", level: 3, weapon: "dp28" },
    ],
    equipmentEra: "late" as const,
    weaponRewards: ["bazooka" as const],
    enemies: [
      { type: "mg", x: 4, y: 3, name: "美23团西侧火力点", equipment: "勃朗宁M1919机枪", exp: 110 },
      { type: "mg", x: 9, y: 3, name: "法军营东侧火力点", equipment: "MAC 24/29轻机枪", exp: 110 },
      { type: "mortar", x: 6, y: 2, name: "环形阵地迫击炮组", equipment: "M1型81毫米迫击炮", exp: 96 },
      { type: "rifle", x: 7, y: 3, name: "美23团步兵", equipment: "M1加兰德步枪", exp: 83 },
    ],
    variantSlots: [{ index: 3, options: ["rifle", "mg"] }],
    waves: [{ window: [2, 3], units: [
      { type: "tank", x: 6, y: 9, name: "克伦贝装甲纵队", equipment: "M4A3E8谢尔曼坦克", exp: 69 },
      { type: "rifle", x: 7, y: 9, name: "美骑5团增援", equipment: "M1加兰德步枪", exp: 69 },
    ] }],
    objectives: [],
    evacZone: Array.from({ length: 14 }, (_, x) => ({ x, y: 0 })),
    itemDrops: [{ x: 5, y: 6, options: ["medkit", "bandage", "ration"] }, { x: 8, y: 6, options: ["medkit", "at_charge", "satchel", "field_manual"] }],
    places: [
      { x: 6, y: 3, name: "砥平里" },
      { x: 6, y: 0, name: "北撤通道" },
    ],
    scripted: [
      { kind: "barrage", turns: [2, 4, 5], damage: 10, note: "法军炮火与空中支援压制" },
      { kind: "supplyWindow", untilTurn: 5, penalty: 0.18, note: "外线弹药耗尽" },
    ],
    victory: { minEvacuated: 4, evacuateRatio: 0.6, requireKeyUnit: true },
  },
  {
    id: "m8-imjin",
    name: "临津江渡河",
    kind: "breakthrough",
    date: "1951年4月22—25日",
    location: "韩国临津江—雪马里—235高地",
    historicalOutcome: "志愿军第63军渡过临津江并包围英军格洛斯特营；英29旅迟滞了攻势后南撤。",
    historicalNote: "关卡目标限定为建立桥头堡和夺取235高地，不把整个春季攻势简化为单场胜负。",
    commanders: [
      pva("fu-chongbi", "傅崇碧", "第63军军长", "中国人民志愿军第63军"),
      un("james-carne", "詹姆斯·卡恩", "营长", "英军格洛斯特郡团第1营"),
    ],
    brief: "夜间泅渡临津江，抢占渡口桥头堡和235高地。英军据点分散但自动武器与炮兵强，利用高地间隙分割而不是沿公路正冲。",
    mapNote: "北在上；临津江横断中部，西岸雪马里村落与东北235高地形成渡河后的两个支点。",
    weather: { options: ["clear", "fog"], label: "春夜薄雾", detail: "夜间河谷能见度有限，白天气象适合联合国军空中支援。" },
    playerEquipment: PVA_LATE,
    maxTurns: 13,
    map: [
      ".#^^F.==F.^^#.",
      "F.VB^#==.^F^^F",
      ".FFFF.==.#FF.F",
      "^^^^..==.^^^^^",
      "~~~~~~==~~~~~~",
      "^FF.F.==..#F.F",
      "..F#^F==.^.F.^",
      "F.FF..==.F.FF.",
      "......==...#..",
      "...^#.==..^...",
    ],
    playerSpawns: [{ x: 5, y: 9 }, { x: 6, y: 9 }, { x: 7, y: 9 }, { x: 8, y: 9 }, { x: 4, y: 8 }, { x: 6, y: 8 }, { x: 7, y: 8 }, { x: 9, y: 8 }],
    storyAllies: [
      { commander: "渡口狼", type: "rifle", level: 3, weapon: "ppsh50" },
      { commander: "高地鹰", type: "mg", level: 3, weapon: "dp28" },
    ],
    equipmentEra: "late" as const,
    weaponRewards: ["mortar82" as const],
    enemies: [
      { type: "rifle", x: 3, y: 1, name: "格洛斯特营前哨", equipment: "李-恩菲尔德No.4步枪", exp: 96 },
      { type: "rifle", x: 10, y: 1, name: "诺森伯兰燧发枪营", equipment: "李-恩菲尔德No.4步枪", exp: 89 },
      { type: "mg", x: 6, y: 3, name: "英军布伦机枪组", equipment: "布伦轻机枪／维克斯机枪", exp: 110 },
      { type: "rifle", x: 8, y: 2, name: "英军后备步兵", equipment: "李-恩菲尔德No.4步枪", exp: 62 },
    ],
    variantSlots: [{ index: 1, options: ["rifle", "mg"] }],
    waves: [{ window: [6, 7], units: [{ type: "tank", x: 7, y: 0, name: "第8骠骑兵支援", equipment: "百夫长Mk.3坦克", exp: 85 }] }],
    objectives: [
      { id: "imjin-bridgehead", name: "临津江桥头堡", kind: "capture", x: 3, y: 1, owner: "enemy" },
      { id: "gloster-hill", name: "235高地", kind: "capture", x: 10, y: 1, owner: "enemy" },
    ],
    evacZone: [],
    itemDrops: [{ x: 4, y: 6, options: ["medkit", "bandage", "ration"] }, { x: 9, y: 6, options: ["at_charge", "arty_support"] }],
    places: [
      { x: 3, y: 1, name: "桥头堡" },
      { x: 10, y: 1, name: "235高地" },
      { x: 2, y: 1, name: "雪马里" },
      { x: 6, y: 4, name: "临津江" },
    ],
    scripted: [
      { kind: "barrage", turns: [3, 5, 7], damage: 8, note: "英军炮火拦阻射击" },
    ],
    victory: { requiredCaptures: 2, holdTurns: 2, minSurvivors: 2 },
  },
  {
    id: "m9-cheorwon",
    name: "铁原阻击",
    kind: "hold",
    date: "1951年5月29日—6月10日",
    location: "韩国铁原—涟川交通走廊",
    historicalOutcome: "志愿军第63军在铁原地区实施纵深阻击，为主力完成休整和建立新防线争取时间。",
    historicalNote: "本关强调迟滞与轮换，不以歼灭追击部队为目标。",
    commanders: [
      pva("fu-chongbi", "傅崇碧", "第63军军长", "中国人民志愿军第63军"),
      un("james-van-fleet", "詹姆斯·范弗里特", "第8集团军司令", "美国陆军第8集团军"),
    ],
    brief: "依托铁原以北山地轮换阻击，守住西高地和东公路口到回合结束。敌军会以步坦协同持续施压，阵地间相互支援比死守单点重要。",
    mapNote: "北在上；铁原—涟川公路被东西两道山脊夹住，联合国军沿中央走廊由北向南追击。",
    weather: { options: ["rain", "overcast"], label: "初夏阵雨", detail: "道路泥泞，低云抑制远程观察，但装甲仍可沿公路推进。" },
    playerEquipment: PVA_LATE,
    maxTurns: 12,
    map: [
      "F.#F..==.F^.#.",
      ".#F.F.==.^FF#F",
      ".^^^..==F.^^..",
      "^^^^F.==.#^^^^",
      ".F^^F.==..^^.#",
      "..F.BV==VV.F^.",
      "F.FF^.==.FFFF.",
      ".F.#^^==^^F..F",
      "......==.^....",
      "#^.F..==.F..F.",
    ],
    playerSpawns: [{ x: 4, y: 5 }, { x: 9, y: 5 }, { x: 5, y: 4 }, { x: 8, y: 4 }, { x: 4, y: 6 }, { x: 9, y: 6 }, { x: 6, y: 6 }, { x: 7, y: 6 }],
    storyAllies: [
      { commander: "阻击磐", type: "rifle", level: 3, weapon: "mosin" },
      { commander: "走廊枪", type: "mg", level: 3, weapon: "dp28" },
    ],
    equipmentEra: "late" as const,
    weaponRewards: ["mosin" as const],
    enemies: [
      { type: "rifle", x: 5, y: 1, name: "美3师追击步兵", equipment: "M1加兰德步枪", exp: 85 },
      { type: "rifle", x: 8, y: 1, name: "美骑1师步兵", equipment: "M1加兰德步枪", exp: 85 },
      { type: "mg", x: 6, y: 0, name: "美军支援火力组", equipment: "勃朗宁M1919机枪", exp: 95 },
      { type: "rifle", x: 7, y: 0, name: "美军公路步兵", equipment: "M1加兰德步枪", exp: 65 },
    ],
    variantSlots: [{ index: 0, options: ["rifle", "mg"] }],
    waves: [
      { window: [3, 4], units: [{ type: "rifle", x: 6, y: 0, name: "追击步兵", equipment: "M1加兰德步枪", exp: 90 }, { type: "mg", x: 5, y: 0, name: "追击火力", equipment: "勃朗宁M1919机枪", exp: 75 }] },
      { window: [6, 7], units: [{ type: "rifle", x: 7, y: 0, name: "第二梯队", equipment: "M1加兰德步枪", exp: 80 }] },
      { window: [8, 9], units: [{ type: "mg", x: 8, y: 0, name: "终局机枪", equipment: "勃朗宁M1919机枪", exp: 70 }] },
    ],
    objectives: [
      { id: "cheorwon-west", name: "铁原西高地", kind: "hold", x: 4, y: 5, owner: "player" },
      { id: "cheorwon-road", name: "铁原公路口", kind: "hold", x: 9, y: 5, owner: "player" },
    ],
    evacZone: [],
    itemDrops: [{ x: 3, y: 5, options: ["medkit", "at_charge", "satchel", "field_manual"] }, { x: 10, y: 5, options: ["at_charge", "arty_support"] }],
    places: [
      { x: 4, y: 5, name: "铁原西高地" },
      { x: 9, y: 5, name: "公路口" },
      { x: 6, y: 1, name: "联合国军追击轴" },
    ],
    scripted: [
      { kind: "barrage", turns: [3, 7], damage: 4, note: "联合国军炮火准备" },
    ],
    victory: { holdUntilEnd: true, minPostsHeld: 2, minSurvivors: 2 },
  },
  {
    id: "m10-triangle-hill",
    name: "上甘岭坑道",
    kind: "hold",
    date: "1952年10月14日—11月25日",
    location: "朝鲜五圣山前沿597.9与537.7高地",
    historicalOutcome: "志愿军第15军、第12军依托坑道体系守住主要阵地，联合国军停止进攻。",
    historicalNote: "棋盘把两个主要高地、坑道口和补给线压缩在同一战术视图。",
    commanders: [
      pva("qin-jiwei", "秦基伟", "第15军军长", "中国人民志愿军第15军", "qin-jiwei"),
      un("wayne-smith", "韦恩·史密斯", "师长", "美国陆军第7步兵师"),
    ],
    brief: "依托坑道守住597.9和537.7两处高地。敌军炮火会分波次压上，医疗与炮火支援必须集中使用；地表失守一处仍可反击，但不能同时丢掉两处。",
    mapNote: "北在上；597.9与537.7两峰对峙，山脚村庄格为坑道口，中央道路是夜间补给线。",
    weather: { options: ["overcast", "rain", "snow"], label: "深秋转初冬", detail: "战斗持续43天，经历阴雨、低云和初雪。" },
    playerEquipment: PVA_LATE,
    maxTurns: 12,
    map: [
      ".F..#.==..F..F",
      "^.F...==...F..",
      "F#^^^#==#^^^#^",
      ".^^^^.==.^^^^F",
      "..^^^B==F^^^..",
      "F.^^V.==.V^^F#",
      ".FFFF.==.^FF.F",
      ".^F.^^==^^#F..",
      "F..#..==.F..F.",
      "......==......",
    ],
    playerSpawns: [{ x: 3, y: 4 }, { x: 10, y: 4 }, { x: 4, y: 4 }, { x: 9, y: 4 }, { x: 4, y: 5 }, { x: 9, y: 5 }, { x: 6, y: 6 }, { x: 7, y: 6 }],
    storyAllies: [
      { commander: "坑道龙", type: "rifle", level: 4, weapon: "ppsh50" },
      { commander: "山顶虎", type: "mg", level: 4, weapon: "dp28" },
    ],
    equipmentEra: "late" as const,
    weaponRewards: ["t34_85" as const],
    enemies: [
      { type: "rifle", x: 5, y: 1, name: "美7师突击连", equipment: "M1加兰德步枪", exp: 115 },
      { type: "rifle", x: 8, y: 1, name: "韩2师突击连", equipment: "M1加兰德步枪", exp: 100 },
      { type: "mg", x: 6, y: 0, name: "联合国军火力组", equipment: "勃朗宁M1919机枪", exp: 115 },
      { type: "mortar", x: 7, y: 0, name: "联合国军迫击炮组", equipment: "M1型81毫米迫击炮", exp: 115 },
      { type: "rifle", x: 6, y: 3, name: "坑道突击队", equipment: "M1加兰德步枪", exp: 105 },
    ],
    variantSlots: [{ index: 1, options: ["rifle", "mg"] }],
    waves: [
      { window: [3, 4], units: [{ type: "rifle", x: 6, y: 0, name: "轮番突击", equipment: "M1加兰德步枪", exp: 90 }] },
      { window: [6, 7], units: [{ type: "rifle", x: 7, y: 0, name: "二梯队", equipment: "M1加兰德步枪", exp: 80 }] },
      { window: [9, 10], units: [{ type: "mg", x: 6, y: 0, name: "三梯队火力", equipment: "勃朗宁M1919机枪", exp: 70 }] },
    ],
    objectives: [
      { id: "hill-5979", name: "597.9高地", kind: "hold", x: 3, y: 4, owner: "player" },
      { id: "hill-5377", name: "537.7高地", kind: "hold", x: 10, y: 4, owner: "player" },
    ],
    evacZone: [],
    itemDrops: [{ x: 5, y: 6, options: ["medkit", "arty_support"] }, { x: 8, y: 6, options: ["medkit", "at_charge", "satchel", "field_manual"] }],
    places: [
      { x: 3, y: 4, name: "597.9高地" },
      { x: 10, y: 4, name: "537.7高地" },
      { x: 5, y: 5, name: "坑道口" },
      { x: 9, y: 5, name: "坑道口" },
    ],
    scripted: [
      { kind: "barrage", turns: [3, 7], damage: 4, note: "上甘岭炮火准备" },
    ],
    victory: { holdUntilEnd: true, minPostsHeld: 2, minSurvivors: 3 },
  },
  {
    id: "m11-pork-chop",
    name: "猪排山争夺",
    kind: "breakthrough",
    date: "1953年7月6—11日",
    location: "朝鲜铁原西北猪排山前哨",
    historicalOutcome: "志愿军攻击猪排山，美军第7师在反复争夺后奉命放弃该前哨阵地。",
    historicalNote: "本关限定为夺取两个前沿支撑点；不把战术前哨得失夸大为战略决战。",
    commanders: [
      pva("wu-ruilin", "吴瑞林", "第24军军长", "中国人民志愿军第24军"),
      un("arthur-trudeau", "阿瑟·特鲁多", "师长", "美国陆军第7步兵师"),
    ],
    brief: "借雨雾接近猪排山，夺取东、西两个前沿支撑点并顶住反击。壕沟和高地减伤明显，迫击炮与炮火支援是打开缺口的关键。",
    mapNote: "两个凸出的高地构成猪排山前哨；中央谷地与交通壕连接后方。",
    weather: { options: ["rain", "fog"], label: "季风雨雾", detail: "持续降雨与山雾削弱远程火力，谷地泥泞。" },
    playerEquipment: PVA_LATE,
    maxTurns: 14,
    map: [
      "#.^^..==..^^.^",
      "F^^^^.==.^^^^.",
      ".F^B^.==.^V^.F",
      ".#^^..==..^^#.",
      "F.FF..==.FFFF.",
      "~~~.F.==.#F~~~",
      "^.#.^.==F^.F.#",
      "F.FF..==.F.FF^",
      "......==....^.",
      "....^.==......",
    ],
    playerSpawns: [{ x: 5, y: 9 }, { x: 6, y: 9 }, { x: 7, y: 9 }, { x: 8, y: 9 }, { x: 4, y: 8 }, { x: 6, y: 8 }, { x: 7, y: 8 }, { x: 9, y: 8 }],
    storyAllies: [
      { commander: "前哨剑", type: "rifle", level: 4, weapon: "ppsh50" },
      { commander: "夜夺峰", type: "mortar", level: 3, weapon: "mortar82" },
    ],
    equipmentEra: "late" as const,
    weaponRewards: ["dp28" as const],
    enemies: [
      { type: "rifle", x: 3, y: 2, name: "美7师前哨西连", equipment: "M1加兰德步枪", exp: 62 },
      { type: "rifle", x: 10, y: 2, name: "美7师前哨东连", equipment: "M1加兰德步枪", exp: 62 },
      { type: "mg", x: 6, y: 1, name: "前哨机枪阵地", equipment: "勃朗宁M1919机枪", exp: 89 },
      { type: "mortar", x: 8, y: 1, name: "前哨迫击炮组", equipment: "M1型81毫米迫击炮", exp: 83 },
    ],
    variantSlots: [{ index: 1, options: ["rifle", "mg"] }],
    waves: [{ window: [5, 6], units: [{ type: "rifle", x: 6, y: 0, name: "反复争夺队", equipment: "M1加兰德步枪", exp: 100 }] }, { window: [8, 9], units: [{ type: "mg", x: 7, y: 0, name: "火力增援", equipment: "勃朗宁M1919机枪", exp: 90 }] }],
    objectives: [
      { id: "pork-west", name: "猪排山西支撑点", kind: "capture", x: 3, y: 2, owner: "enemy" },
      { id: "pork-east", name: "猪排山东支撑点", kind: "capture", x: 10, y: 2, owner: "enemy" },
    ],
    evacZone: [],
    itemDrops: [{ x: 4, y: 6, options: ["medkit", "arty_support"] }, { x: 9, y: 6, options: ["medkit", "arty_support"] }],
    places: [
      { x: 3, y: 2, name: "西支撑点" },
      { x: 10, y: 2, name: "东支撑点" },
    ],
    scripted: [
      { kind: "barrage", turns: [3, 6], damage: 8, note: "美7师炮火反击" },
    ],
    victory: { requiredCaptures: 2, holdTurns: 1, minSurvivors: 2 },
  },
  {
    id: "m12-kumsong",
    name: "金城反击",
    kind: "breakthrough",
    date: "1953年7月13—27日",
    location: "朝鲜金城以南—北汉江地区",
    historicalOutcome: "志愿军在25公里正面发起停战前最后一次大规模进攻，突破韩军防线；随后双方稳定战线并停战。",
    historicalNote: "游戏聚焦某一突击集团的第一夜突破，不模拟整场20余万人的战役。",
    commanders: [
      pva("yang-yong", "杨勇", "第20兵团司令员", "中国人民志愿军第20兵团"),
      un("maxwell-taylor", "马克斯韦尔·泰勒", "第8集团军司令", "美国陆军第8集团军"),
    ],
    brief: "在炮火准备后突破金城南侧韩军阵地，夺取轿岩山和北汉江公路桥。暴雨会限制视野和机动，但也掩护接近。最后一关仍以保存主力为硬约束。",
    mapNote: "北在上；东侧河流代表北汉江，中央道路连接韩军纵深阵地，两处目标控制突破口。",
    weather: { options: ["rain"], label: "盛夏暴雨", detail: "季风暴雨造成河水上涨、道路泥泞，远程火力效果下降。" },
    playerEquipment: PVA_LATE,
    maxTurns: 13,
    map: [
      "^^FF^.==.FFF^^",
      "^F.BF.==..V#.^",
      "..^^#.==.^^^..",
      "F^FF..==#FFFF.",
      "~~~.F.==..F~~~",
      "..F.^.==.^.F.^",
      "F.FF..==..FFF.",
      ".F#.^.==.^F^.#",
      "...^..==..^...",
      "F.^F..==.F..F.",
    ],
    playerSpawns: [{ x: 5, y: 9 }, { x: 6, y: 9 }, { x: 7, y: 9 }, { x: 8, y: 9 }, { x: 4, y: 8 }, { x: 6, y: 8 }, { x: 7, y: 8 }, { x: 9, y: 8 }],
    storyAllies: [
      { commander: "金城破", type: "rifle", level: 4, weapon: "ppsh50" },
      { commander: "北汉桥", type: "tank", level: 3, weapon: "t34_85" },
    ],
    equipmentEra: "late" as const,
    weaponRewards: ["t34_85" as const],
    enemies: [
      { type: "rifle", x: 3, y: 1, name: "韩军首都师前沿连", equipment: "M1加兰德步枪", exp: 70 },
      { type: "rifle", x: 10, y: 1, name: "韩军第6师守备连", equipment: "M1加兰德步枪", exp: 70 },
      { type: "mg", x: 6, y: 2, name: "韩军地堡火力组", equipment: "勃朗宁M1919机枪", exp: 80 },
      { type: "mortar", x: 8, y: 2, name: "韩军迫击炮组", equipment: "M1型81毫米迫击炮", exp: 60 },
      { type: "rifle", x: 7, y: 0, name: "韩军纵深警戒队", equipment: "M1加兰德步枪", exp: 40 },
    ],
    variantSlots: [{ index: 1, options: ["rifle", "mg"] }],
    waves: [{ window: [4, 5], units: [{ type: "rifle", x: 6, y: 0, name: "预备队", equipment: "M1加兰德步枪", exp: 100 }] }, { window: [7, 8], units: [{ type: "mg", x: 5, y: 0, name: "公路机枪", equipment: "勃朗宁M1919机枪", exp: 80 }, { type: "tank", x: 7, y: 0, name: "北汉江坦克", equipment: "M4A3E8谢尔曼", exp: 40 }] }],
    objectives: [
      { id: "kumsong-hill", name: "轿岩山", kind: "capture", x: 3, y: 1, owner: "enemy" },
      { id: "pukhan-bridge", name: "北汉江公路桥", kind: "capture", x: 10, y: 1, owner: "enemy" },
    ],
    evacZone: [],
    itemDrops: [{ x: 4, y: 6, options: ["medkit", "arty_support"] }, { x: 9, y: 6, options: ["at_charge", "arty_support"] }],
    places: [
      { x: 3, y: 1, name: "轿岩山" },
      { x: 10, y: 1, name: "北汉江桥" },
    ],
    scripted: [
      { kind: "barrage", turns: [2, 5], damage: 8, note: "联合国军拦阻炮火" },
      { kind: "supplyWindow", untilTurn: 9, penalty: 0.1, note: "金城反击弹药窗口" },
    ],
    victory: { requiredCaptures: 2, holdTurns: 1, minSurvivors: 2 },
  },
];
